### ISSUE TITLE
​/validator​/attestation  (get) endpoint

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1181]
​/validator​/attestation

Produce an attestation, without signature

**Comment by rolfyone** [comment]
lighthouse: https://lighthouse-book.sigmaprime.io/http_validator.html#validatorattestation
eth2-spec: https://github.com/ethereum/eth2.0-specs/blob/v0.10.1/specs/phase0/beacon-chain.md#attestation
eth2-api: https://ethereum.github.io/eth2.0-APIs/#/MinimalSet/get_validator_attestation

teku: tech.pegasys.artemis.datastructures.operations.AttestationData

Basically creating the AttestationData object, and returning it. The object creation should live outside the interface, the interfaces concern is taking parameters and serializing the result. We'll have to find a home for the service.

@ajsutton and I talked, and it is probably worth delaying work on this until we are able to restructure things and not make a mess for adding the /validator endpoints. There will need to be a meeting around the desired architecture.

**Comment by rolfyone** [comment]
From discussions, we can proceed to generate an unsigned attestation without too much of an issue.

It didn't sound like a lot of work, the normal endpoint work and a test is the basics, so i think it's probably bigger than that because there's a small amount of implementation potentially to take the generic attestation and insert data from the request parameters.

**Comment by rolfyone** [comment]
I had started this but not got far, and i've other things still, so i'll unassign from myself.
