### ISSUE TITLE
/beacon/validators/all endpoint

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1196]
/beacon/validators/all

Get all validators, active or not. There is another endpoint (/beacon/validators/active) that will list only active validators.

**Comment by rolfyone** [comment]
prysm: https://api.prylabs.net/#/BeaconChain/ListValidators
lighthouse: https://lighthouse-book.sigmaprime.io/http_beacon.html#beaconvalidatorsall

We basically want
GET on /beacon/validators

 - Supports no query parameters
 - supports query by active
 - Supports query by epoch, genesis
 - Supports paginated response, 250 default would be good in the same way that prysm works (so would need pageToken and pageSize)

there will be a POST on the same route, but this task only deals with GET.

BeaconState has a getValidators function, which is a list. We'll be returning a page of elements in that list, at a given state.

To get consistent results, you'd be querying on epoch and pageSize, and keep iterating that until you get to the end of the list.
Because of pagination, might want to test trying to index outside of the list (like 100 elements in validators, get page 100 of 100 elements)
Try to keep the query out of the interface so that we can re-use when we build gRPC or another interface.

**Comment by macfarla** [comment]
return entire list of validators #1242

**Comment by macfarla** [comment]
We are not adding the genesis parameter, it's not needed. If you specify epoch param of zero, then return genesis validators, and if you omit the epoch param, you will get current validators.
