### ISSUE TITLE
​/validator​/duties endpoint - MVP

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1203]
​/validator​/duties
Get validator duties for the requested validators.

This issue has been broken down into separate tickets. This first ticket is to 
* add the ValidatorDutiesHandler
* take epoch and list of keys params
* return List of ValidatorDuties objects which will contain a subset of the required info initially, namely:
      "committeeIndex": "2",
      "publicKey": "qHXe4LiVDU6D3BfGr/21cicoeJO6MclyF/kkq/4zfAO6vJuWJOozRzTB8eG6VwMC",
      "validatorIndex": "0"
* if a particular key (value in list) is not found or is invalid, return (same as prysm)
      "committeeIndex": "0",
      "publicKey": "qHXe4LiVDU6D3BfGr/21cicoeJO6MclyF/kkq/4zfAO6vJuWJOozRzTB8eG6VwMC",
      "validatorIndex": "0"

implemented a deserializer for pubkey

**Comment by rolfyone** [comment]
after we've talked with Adrian, should be in a better place to estimate, but until then, flagging as blocked

**Comment by rolfyone** [comment]
lighthouse: https://lighthouse-book.sigmaprime.io/http_validator.html#validatorduties
prysm: https://api.prylabs.net/#/BeaconNodeValidator/GetDuties
eth2-api:https://ethereum.github.io/eth2.0-APIs/#/MinimalSet/get_validator_duties

all take an epoch and a list. 
Lighthouse: pubkeys - hex encoding BLS public keys
prysm: publicKeys - byte encoded BLS public keys.
eth2-api: validator_pubkeys - hex encoded BLS public keys

an interesting issue raised: https://github.com/ethereum/eth2.0-APIs/issues/12

Something similar to the prysm structure being returned is ideal, no pagination because requesting specific validators by public key.

remember - stakes are out, committees are in.

we'll need to limit the list of public keys supplied to something sane. lighthouse uses a POST now to allow it to pass large numbers of validators in via the message content rather than url query parameters. they reported breaking if there were 100 public keys when using GET. Do we have an idea of how many validators we may want to query on per call @arash009 ?

**Comment by arash009** [comment]
To complicate things further, there are 3 variations of results:
​/validator​/duties
/validator/duties/all
/validator/duties/active

We could potentially combine all into the single /duties endpoint, but I would expect the result for all to return all validators, regardless of number.

**Comment by tapanshah21** [comment]
@macfarla as discussed, here is a draft mindmap of the scenarios we discussed this morning.
![Screen Shot 2020-03-10 at 8.30.54 pm.png](https://images.zenhubusercontent.com/5e54a80986e704ce306373a7/a8b42621-2d5e-4944-9cfe-4a931b7e8e1f)

Please let me know if I've missed anything.

**Comment by rolfyone** [comment]
are we talking about testing all of that at the interface level? Id like to have an understanding of the plan re. testing, or we should really re-estimate this task...

**Comment by tapanshah21** [comment]
Happy to help with the re-estimation..
Well these are all the scenarios that I could come up with after a discussion with Sally and Arash yesterday.
