### ISSUE TITLE
/beacon/validators POST 

### ISSUE THREAD

**Issue by macfarla** [Consensys-Incorporated/teku#1349]
### Description
As an blockchain explorer, I want the same functionality as lighthouse so that I don't lose my mind. 

Do what lighthouse does https://lighthouse-book.sigmaprime.io/http_beacon.html#beaconvalidators
* has a message body with optional state root and list of validator keys

see #1203 which also takes a list of keys param -> which will have implemented a deserializer for pubkey

Return a list of ValidatorWithIndex object - may have to add extra nullable fields to it

**Comment by macfarla** [comment]
note that lighthouse has extra fields balance and pubkey outside the Validator spec

    {
        "pubkey": "0x98f87bc7c8fa10408425bbeeeb3dc387e3e0b4bd92f57775b60b39156a16f9ec80b273a64269332d97bdb7d93ae05a16",
        "validator_index": 14935,
        "balance": 3228885987,
        "validator": {
            "pubkey": "0x98f87bc7c8fa10408425bbeeeb3dc387e3e0b4bd92f57775b60b39156a16f9ec80b273a64269332d97bdb7d93ae05a16",
            "withdrawal_credentials": "0x00b7bec22d5bda6b2cca1343d4f640d0e9ccc204a06a73703605c590d4c0d28e",
            "effective_balance": 3200000000,
            "slashed": false,
            "activation_eligibility_epoch": 0,
            "activation_epoch": 0,
            "exit_epoch": 18446744073709551615,
            "withdrawable_epoch": 18446744073709551615
        }
    },

**Comment by rolfyone** [comment]
summary from zoom.

 - yes we're different to lighthouses implementation as it turns out, because we would need to allow search on state_root.
 - state_root is not currently a search index we have, though it's possible to create if needed at some point
 - block_root and slot is less helpful because its yet another disparate implementation.

Parking the implementation of state_root as an option, and we'll revisit it later if required.
