### ISSUE TITLE
/validator/participation endpoint

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1363]
GET /validator/participation endpoint

Lighthouse: https://lighthouse-book.sigmaprime.io/http_consensus.html#consensusglobal_votes
https://app.swaggerhub.com/apis/spble/lighthouse_rest_api/0.2.0#/RFC/get_beacon_validators_participation

Prysm: https://api.prylabs.net/#/BeaconChain/GetValidatorParticipation

So from what I can see what we really need is the current value of votes vs possible value at an epoc

**Comment by rolfyone** [comment]
need more information about this one

**Comment by mark-terry** [comment]
We're looking to produce a response that looks like:
```
{
  "epoch": "string",
  "finalized": true,
  "global_participation_rate": 0,
  "voted_ether": 0,
  "eligible_ether": 0
}
```

where:
- epoch: the epoch for which the data is being provided
- finalized: Whether the epoch is finalized or not
- global_participation_rate: The participation rate of all validators - 0.0 (0%) -> 1.0 (100%)
- voted_ether: The total amount of ether (in Gwei) that has been used to vote in the specified epoch
- eligible_ether: The total amount of ether (in Gwei) that was eligible for voting in the specified epoch

**Comment by rolfyone** [comment]
putting this back and looking at a bug... attaching a patch of where i got to...[https://app.zenhub.com/files/147802356/f5a30e48-3d98-420f-af81-40c9336dac25/download](https://app.zenhub.com/files/147802356/f5a30e48-3d98-420f-af81-40c9336dac25/download)

**Comment by rolfyone** [comment]
Beacon state has current epoch pending attestations, and previous epoch pending attestations, but only previous epoch pending attestations gets persisted. once the epoch is past, 'current epoch pending attestations' are zero'd out by the looks.

It means most of what I can currently provide is very limited. I can calculate active gwei just by checking active validators at an epoch, so that's fine. I can do that for any epoch, but the attesting values are close to not usable.

To do this properly calculations will have to be made and stored, so that they can be later retrieved.  The current epoch values can probably be done on the fly, but after the epoch is done these values 'disappear', so all previous epoch stats really need to be cached.

I've committed where i'm up to on a local branch, but I'm not sure there's enough value in what's there now (active gwei, previous epoch attestations) to actually merge... I'll wait to see what @arash009 decides before proceeding.

**Comment by rolfyone** [comment]
this can be closed because we're going to be doing standard api, and this isn't explicitly on the list.
