### ISSUE TITLE
Changes to log4j config are not picked up at runtime

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#1526]
### Description
When running teku (version at https://github.com/PegaSysEng/teku/commit/4e3281b18dfe36a94c8ca4fb84704e9b3408935b), it appears that updates to my `log4j2.xml` file are not being picked up at runtime.  Previously, when updating log levels etc, changes would be picked up immediately.

I am setting an env var `LOG4J_CONFIGURATION_FILE` pointing to my log4j config and it appears this is getting picked up:
```
2020-04-02 22:19:13,560 main INFO Custom logging configuration applied from: /home/ec2-user/log4j2.xml
```

I am not setting any logging options via CLI args or my config.toml.  

My config consists of: 
```
data-path = "/data/data"
data-storage-mode = "prune"
network="/data/config/config.yaml"
Xinterop-enabled=true
Xinterop-start-state="/data/config/genesis.ssz"
Xinterop-genesis-time=0
p2p-discovery-bootnodes=["-Iu4QGuiaVXBEoi4kcLbsoPYX7GTK9ExOODTuqYBp9CyHN_PSDtnLMCIL91ydxUDRPZ-jem-o0WotK6JoZjPQWhTfEsTgmlkgnY0gmlwhDbOLfeJc2VjcDI1NmsxoQLVqNEoCVTC74VmUx25USyFe7lL0TgpXHaCX9CDy9H6boN0Y3CCIyiDdWRwgiMo","-Iu4QLNTiVhgyDyvCBnewNcn9Wb7fjPoKYD2NPe-jDZ3_TqaGFK8CcWr7ai7w9X8Im_ZjQYyeoBP_luLLBB4wy39gQ4JgmlkgnY0gmlwhCOhiGqJc2VjcDI1NmsxoQMrmBYg_yR_ZKZKoLiChvlpNqdwXwodXmgw_TRow7RVwYN0Y3CCIyiDdWRwgiMo","-Iu4QLpJhdfRFsuMrAsFQOSZTIW1PAf7Ndg0GB0tMByt2-n1bwVgLsnHOuujMg-YLns9g1Rw8rfcw1KCZjQrnUcUdekNgmlkgnY0gmlwhA01ZgSJc2VjcDI1NmsxoQPk2OMW7stSjbdcMgrKEdFOLsRkIuxgBFryA3tIJM0YxYN0Y3CCIyiDdWRwgiMo"]
```

And I'm running teku with just the `config-file` CLI arg:
```
teku --config-file=config.toml
```

**Comment by CjHare** [comment]
What does the log4j config file look like, specifically does it contain the `monitorInterval` in the `Configuration` element?

```
<Configuration monitorInterval="30">
```

**Comment by CjHare** [comment]
Locally, log4j scanning of custom config file occurs, with the following output to console
```
2020-04-03 16:04:44,723 main INFO Custom logging configuration applied from: ./../../custom.xml
```
then after a change to `custom.xml` this output follows and the change is applied
```
2020-04-03 16:05:29,093 Log4j2-TF-3-Scheduled-1 INFO Source '/Users/chris.hare/Documents/code/pegasys/teku/./../../custom.xml' was modified on Fri Apr 03 16:05:25 AEST 2020 (1585893925377), previous modification was on Fri Mar 13 18:30:23 AEST 2020 (1584088223982)
2020-04-03 16:05:29,096 Log4j2-TF-1-ConfiguratonFileWatcher-2 INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
```

**Comment by mbaxter** [comment]
@CjHare - I did not have the `monitorInterval` attribute in my log4j config.  After adding that, it does look like my changes are getting picked up.

Should we add a default `monitorInterval` value?  It seems like previously we were picking up changes without explicitly defining the `monitorInterval`.

**Comment by CjHare** [comment]
>“If the monitorInterval attribute is specified on the configuration element and is set to a non-zero value then the file will be checked the next time a log event is evaluated and/or logged and the monitorInterval has elapsed since the last check”

https://logging.apache.org/log4j/2.x/manual/configuration.html

The price for having `monitorInterval` active is additional read ops.


> Should we add a default monitorInterval value?

Leaning towards probably not.

There is now an endpoint available (same functionality as Besu) that can be used to change log levels on demand.

For users falling back on the default Log4j2.xml, I’m imagining that feature is unlikely to be used (I’m thinking deployed app, file bound up in a JAR).
For users applying their own custom Lo4j2.xml and wanting that feature (as you were), then using the ‘monitorInterval’ seems a reasonable remedy.

The other challenge with applying a default value being the lack of ability to set that on the Log4j2 `Configuration`. The variable exists only as a method scoped variable in the parsing method on the concrete configuration class (e.g. `XmlConfiguration` constructor).


> It seems like previously we were picking up changes without explicitly defining the monitorInterval.

I’m not entirely sure why this would be. However over the course of the changes the Log4j2 version has been updated, so that might have been a fixed bug in Log4j2 🤔

**Comment by mbaxter** [comment]
Sounds good.  Thanks for investigating @CjHare!
