### ISSUE TITLE
Metrics CLI options - identify dependencies

### ISSUE THREAD

**Issue by macfarla** [Consensys-Incorporated/teku#1637]
### Description
As a Teku User, I want dependencies between options to be clear so that when I specify an option that requires another option to be specified, this is clearly identified. 

eg currently can specify --metrics-port WITHOUT specifying --metrics-enabled 
in which case the port is ignored

### Acceptance criteria
* if I specify any other --metrics option without --metrics-enabled I get an error with explanation and Teku does not start
* if I specify --metrics-enabled and there are other options required, then I get an error message saying any --metrics options that are required (I think for metrics they all have defaults so this may not be an issue)

**Comment by rolfyone** [comment]
metrics-enabled needs to be set for any metrics options to be looked at, but having said that, if metrics-enabled is not set, we don't want to fail to start, and its likely to not be worth the effort of raising log errors, because it's actually expected a lot of the time (like in devops scenarios).

There aren't any other obvious dependencies, because all other dependencies have predefined default values that are sensible.
