### ISSUE TITLE
Rest API CLI options - identify dependencies 

### ISSUE THREAD

**Issue by macfarla** [Consensys-Incorporated/teku#1638]
### Description
As a Teku User, I want dependencies between options to be clear so that when I specify an option that requires another option to be specified, this is clearly identified. 

eg currently can specify --rest-api-port WITHOUT specifying --rest-api-enabled 
in which case the port is ignored

### Acceptance criteria
* if I specify any other --rest-api option without --rest-api-enabled I get an error with explanation and Teku does not start
* if I specify --rest-api-enabled and there are other options required, then I get an error message saying any --rest-api options that are required (I think for rest API they all have defaults so this may not be an issue)

**Comment by rolfyone** [comment]
rest-api-enabled needs to be set for any rest-api options to be looked at, but having said that, if rest-api-enabled is not set, we don't want to fail to start, and its likely to not be worth the effort of raising log errors, because it's actually expected a lot of the time (like in devops scenarios).

There aren't any other obvious dependencies, because all other dependencies have predefined default values that are sensible.
