### ISSUE TITLE
P2P CLI options - identify dependencies

### ISSUE THREAD

**Issue by macfarla** [Consensys-Incorporated/teku#1639]
### Description
As a Teku User, I want dependencies between options to be clear so that when I specify an option that requires another option to be specified, this is clearly identified. 

eg can you currently specify --p2p-port WITHOUT --p2p-enabled (or p2p-enabled set to false) 
in which case the port is ignored

### Acceptance criteria
* if I specify any other --p2p option without --p2p-enabled I get an error with explanation and Teku does not start
* if I specify --p2p-enabled and there are other options required, then I get an error message saying any --p2p options that are required (I think for p2p they all have defaults so this may not be an issue)

**Comment by rolfyone** [comment]
p2p-enabled needs to be set for any p2p options to be looked at, but having said that, if p2p-enabled is not set, we don't want to fail to start, and its likely to not be worth the effort of raising log errors, because it's actually expected a lot of the time (like in devops scenarios).

There aren't any other obvious dependencies, because all other dependencies have predefined default values that are sensible.
