### ISSUE TITLE
[bug/fuzzing] Incorrect validation of pre-state attestation & malformed block signature during state transition (teku)

### ISSUE THREAD

**Issue by pventuzelo** [Consensys-Incorporated/teku#1686]
Hi guys, 

After fuzzing with [beacon-fuzz](https://github.com/sigp/beacon-fuzz), we found an issue in prysm and I reported it here:
[[bug/fuzzing] Incorrect validation of pre-state attestation & malformed block signature during state transition](https://github.com/prysmaticlabs/prysm/issues/5658).

Download: [incorrect_ssz_validation_prysm.zip](https://github.com/PegaSysEng/teku/files/4545575/incorrect_ssz_validation_prysm.zip)

Based on testing with `teku`, you also have the same issues:
``` sh
# install
$  ./gradlew distTar installDist

# go to build folder
$ cd build/install/

$ ./bin/teku transition blocks --pre=incorrect_ssz_validation_state_prysm.ssz  --network=mainnet incorrect_ssz_validation_block_prysm.ssz
...
# process continued without any errors
```

### Versions

* Github branch: `master`
* Github commit: 1cc346671521a4381776bb9145af1be3b290fe8b
* Java version: `openjdk version "11.0.7" 2020-04-14`
* OS Name & Version: `Ubuntu 18.04.4 LTS`
* Kernel Version: `4.15.0-96-generic`

**Comment by ajsutton** [comment]
With #1693 in place we reject the block because the attestation aggregation bits are the wrong size.

As far as I can tell we consider the signature invalid.  We are currently only checking the signature after processing the state and the block is about 1970324836982784 slots in the future so we take forever trying to process slots to get the pre state.  It may make sense to perform that check earlier to avoid doing a lot of work for a block that wasn't even from a real validator - the impact is significantly reduced normally though because the block can't be ahead of the current slot so definitely won't be that many slots in the future.

**Comment by ajsutton** [comment]
I'm confident that if you waited long enough for Teku to process all those empty slots, it would then validate the signature and reject the block.

Additionally, in the full Teku setup the block would have to be between the last finalised slot and the current slot so we wouldn't have tried to process the empty slots for this block and would have wound up discarding the block because it's too far in the future.

So now that #1693 is merged, I'm going to consider this fixed and close the issue.
