### ISSUE TITLE
Improve default value reporting in `--help`

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#1746]
### Description
As a user, I want `--help` to show default values for all options where it makes sense, especially the boolean ones, so that I know exactly what is enabled and what isn't.

For example `--eth1-enabled` defaults to `true`, whereas `--rest-api-docs-enabled` seems to default to `false`. But there is no way to know this.

(Related: although the docs for `--rest-api-docs-enabled` in [the code](https://github.com/PegaSysEng/teku/blob/81deceb0070d240768fe3a43fa833fbb3604e9e2/teku/src/main/java/tech/pegasys/teku/cli/options/BeaconRestApiOptions.java#L27) seem to give `true` for the `fallbackValue`, the default appears to be `false`.)

### Acceptance Criteria
* running `teku --help` shows the correct default settings for all relevant options.

**Expected behavior:** [What you expect to happen]
```
      --eth1-enabled[=<BOOLEAN>]
                             Whether to connect to the ETH1 chain
                             Default: true
```

**Actual behavior:** [What actually happens]
```
      --eth1-enabled[=<BOOLEAN>]
                             Whether to connect to the ETH1 chain
```

### Versions (Add all that apply)
* Software version: [`teku --version`]
  - teku/v0.11.0-dev-e3ad800d/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13

**Comment by benjaminion** [comment]
Default values are also missing for `--p2p-private-key-file` and `--validators-graffiti`, and maybe others.

**Comment by systemfreund** [comment]
> --p2p-private-key-file

I wonder what should be displayed here as the default value. If not specified then the key is read from the KV-Store (i.e. `<beacon-data-dir>/kvstore/generated-node-key.dat`). However that file cannot be specified as a value to this argument.

**Comment by ajsutton** [comment]
Ah yes, it would be really nice if `--p2p-private-key-file` could read either the current text based hex format or the binary format used for `generated-node-key.dat`.

I think the default however is none and it probably just needs a note stating that one will be generated and stored in the beacon node data directory if not specified.  I believe if you specify a value for this we expect it to be present which seems like a useful feature (if you intended to use a specific node key, then you wouldn't want us to silently generate a new one if you happened to get the path wrong).

**Comment by ermyas** [comment]
Hi,

I would like to take this up if no one else is currently working on it. 

_Initial thoughts:_
The reason why the default values for boolean options are currently not being displayed appears to be because Picocli [ignores the `Command.showDefaultValues` flag for boolean options](https://picocli.info/apidocs/picocli/CommandLine.Command.html#showDefaultValues--). The rationale for this is mentioned [here](https://github.com/remkop/picocli/issues/1414) and is based on the assumption that boolean options would default to `false`, which isn’t the case in this instance. 

There are probably two ways to get around this 1) specifically set `Option.showDefaultValue = Visibility.ALWAYS` for each non-hidden boolean option specifically 2) Interpolate the default value of an option into its description ([${DEFAULT-VALUE} variable](https://picocli.info/#_default_value_variable) ). The first approach is perhaps slightly more consistent with the current use of `Command.showDefaultValues`, so I might use that unless you have other thoughts.

If I am not mistaken, the second point raised here seems to be that some non-boolean options don’t have specific default values that can be specified, even though there is some mechanism being employed to obtain their value if one isn't explicitly provided. For such options, I assume the consensus is to update the descriptions and note this behavior?

**Comment by ajsutton** [comment]
> I would like to take this up if no one else is currently working on it.

That would be fantastic.

> There are probably two ways to get around this 1) specifically set `Option.showDefaultValue = Visibility.ALWAYS` for each non-hidden boolean option specifically 2) Interpolate the default value of an option into its description ([${DEFAULT-VALUE} variable](https://picocli.info/#_default_value_variable) ). The first approach is perhaps slightly more consistent with the current use of `Command.showDefaultValues`, so I might use that unless you have other thoughts.

I didn't realise setting `Visibility.ALWAYS` worked for booleans (I'm not deeply familiar with PicoCLI).  If it does that sounds like a great solution so the formatting of showing the defaults is consistent.  We already habitually add a couple of flags particularly for boolean fields so that would be easy to add as well.  Actually now I think about it we probably should write a custom error-prone check to enforce those options are always set for boolean options, but that's a separate thing. :)

> If I am not mistaken, the second point raised here seems to be that some non-boolean options don’t have specific default values that can be specified, even though there is some mechanism being employed to obtain their value if one isn't explicitly provided. For such options, I assume the consensus is to update the descriptions and note this behavior?

Yes, there's a few options where the default is platform dependent or depends on other values.  Just ensuring the description explains how the default is calculated is the right approach for those.

**Comment by ermyas** [comment]
Thanks, @ajsutton. I will work on making the changes for the first part, then come back to confirm the details of the second.

**Comment by ermyas** [comment]
I've submitted PR #4272  with the changes for both parts. The changes are mostly minor and address the following:
- fixed the issue where boolean command options were not displaying in the usage help message
- fixed an issue where a couple of subcommands weren't displaying default values for any option in their usage help messages
- updated the descriptions of options whose defaults can't automatically be inferred by Picocli. This is based on what I could infer from the code and the docs. Let me know if I missed anything.
- other minor improvements to the descriptions of commands and options

On a related note, it looks like the [CLI reference docs](https://docs.teku.consensys.net/en/latest/Reference/CLI) are a bit out of sync with the code. I am not sure if this is already being addressed, but if not, I can raise a separate issue in the docs repo for this. I've listed below some of the minor discrepancies I could see on a quick pass. 

*[Teku command - `teku`](https://docs.teku.consensys.net/en/latest/Reference/CLI/CLI-Syntax/)*
— `--log-file-name-pattern` documentation should perhaps show the default pattern used `<data-path>/logs/teku_%d{yyyy-MM-dd}.log`
— `—metrics-categories` missing `DISCOVERY` category (i.e. `TekuMetricCategory.DISCOVERY`)
— `—validators-external-signer-timeout` defaults to 5000 in code, but docs state 1000
—  `--p2p-private-key-file`  documentation should describe what happens when this value is not provided.

*[Slashing-protection subcommand - `teku slashing-protection`](https://docs.teku.consensys.net/en/latest/Reference/CLI/Subcommands/Slashing-Protection/)*
— Documentation for `ImportCommand` and `ExportCommand` should  mention `—data-base-path` as an alias to `—data-path` 
— `data-validator-path` option not present in the documentation

*[Validator-client subcommand - `teku validator-client`](https://docs.teku.consensys.net/en/latest/Reference/CLI/Subcommands/Validator-Client/)*
— `—log-include-validator-duties-enabled` default to `true` in code but the docs report the default as `false`  [Validator client subcommand options](https://docs.teku.consensys.net/en/latest/Reference/CLI/Subcommands/Validator-Client/#log-include-events-enabled) 
—`--log-file-name-pattern` documentation should show the default pattern used `<data-path>/logs/teku_%d{yyyy-MM-dd}.log`
— `—metrics-categories` missing `DISCOVERY` category
— `—metrics-interface` defaults to “127.0.0.1” in code, but docs note “0.0.0.0” 
— `--validators-early-attestations-enabled` option not present in the documentation
— `--validators-external-signer-keystore` and `--validators-external-signer-keystore-password-file` options not present in the documentation
— `—validators-external-signer-timeout` defaults to 5000 in code, but docs state 1000
—`--validators-external-signer-truststore` and `—--validators-external-signer-truststore-password-file` options not present in the documentation
— `--validators-graffiti-file` option not present in the documentation

*[Voluntary-exit subcommand -- `teku voluntary-exit`](https://docs.teku.consensys.net/en/latest/Reference/CLI/Subcommands/Voluntary-Exit/)*
— `--validators-external-signer-keystore` and `--validators-external-signer-keystore-password-file` options not present in the documentation
—`--validators-external-signer-truststore` and `—--validators-external-signer-truststore-password-file` options not present in the documentation
— `—validators-external-signer-timeout` defaults to 5000 in code, but docs state 1000
