### ISSUE TITLE
Cannot read eth1 data when fast synced

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1781]
Having Teku running before my eth1 chain had finished syncing resulted in my validator not being able to sign any attestations. Unfortunately, my laptop restarted after my eth1 chain sync so don't have the error logs, but it was something about "eth1 chain data not available for block xxxxxxx". Once I had passed the fast sync pivot block, it could reach the chain and produce attestations as expected.

**Comment by cemozerr** [comment]
Thanks @arash009. We’re aware of this issue and currently working on a fix. The main problem is that currently Teku uses archival function calls on its Eth1 node to retrieve deposit contract merkle tree root and deposit count. What you’re seeing is what happens when Teku makes an archival function call at a block height that the Eth1 node doesn’t have in its recent archival memory. 

Teku does work when the Eth1 node is set to store archival information for about 9 hours instead of the default 4 hours, but we’re hoping to get rid of this requirement asap.

**Comment by ajsutton** [comment]
This error is slightly different to that - we should be able to produce attestations and blocks even if the eth1 chain data isn't available - but currently both stop being produced (and nothing is printed to the console logs).

**Comment by ajsutton** [comment]
This appears to be fixed now.  The restriction is that it's not possible to create blocks if there are deposits which could be included but our node doesn't yet have them (valid blocks must include as many deposits as possible).  Otherwise validation continues to occur even when the ETH1 chain is unavailable.
