### ISSUE TITLE
Avoid getting slashed as a validator

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1887]
A possible approach: https://www.google.com/url?q=https://hackmd.io/u8MTIe5IRmybzVz38-sGdQ?view&sa=D&ust=1571951893619000&usg=AFQjCNFFjXa5kqQhxkT0p2bjLTpUmd_wTw

Strongly suggest we create a component that’s specifically responsible for signing and is the only component to have access to the private key. It would then implement the process above to ensure it never signs anything that may create a slashing condition.

**Comment by benjaminion** [comment]
Irrespective of whether signing is done by the validator or elsewhere, we should implement a degree of protection against getting slashed at the validator end of things.

In principle it is fairly easy:
  - Persist the number of the slot I last proposed a block in, and the block root
  - Persist the last source and last target I attested to along with the attestation root

Using these data it is simple to avoid sending for signing anything that might get me slashed. We store the previous roots, because we _are_ allowed to re-sign/re-broadcast the same block/attestation if we wish.

We should also make these values (maybe excluding the hashes) exportable/importable so that we can safely move keys between validator processes potentially on different hardware.

**Comment by benjaminion** [comment]
Also see: https://github.com/ethereum/eth2.0-APIs/issues/64

The idea is not to rely solely on a validator's own journal of its history. The beacon node it is attached to sees what's on the network and will know if there is some other validator out there using the same public key by looking at what gets into blocks.

**Comment by ajsutton** [comment]
@benjaminion We now record the last values in a yaml file so they're human readable and can be copied or even manually created for a different client.  I could see some benefit in creating Cli options to specify  values and have it create the file automatically (though the syntax would be awkward) or have a subcommand to import slashing protection which copies over files and picks the higher value if there are some overlapping validators.

I'm not sure either of those are actually worth it at the moment though.  How far do you think we should go at the moment to support moving these validator records around?

**Comment by ajsutton** [comment]
This is as far as we'll take this for now, so closing.

Logged https://github.com/PegaSysEng/doc.teku/issues/136 to add this to the docs.
