### ISSUE TITLE
Better options for managing large numbers of keys

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2003]
### Description

From  @protolambda

> Hey, is there some better way to run multiple validators with Teku. Instead of passing a huge list to `--validators-key-files` in the CLI? Lighthouse does something neat where you specify just a secrets dir, and each password file is named by pubkey, so the client can find them.
>
> Or maybe use a csv or json of account -> password mappings? If a directory is too complicated to implement on what's already there?
>
> I'll try generating the CLI argument, but it would be neat to just have Teku resolve where to find the passphrases for the key files

**Comment by rolfyone** [comment]
after talking to @ajsutton :
 - provide a new option `--validator-keys` - this option accepts `key:secret,key2:secret2`
 - the key:secret pair could be a directory, in which case files in `key/*` match files in `secret/*` 
 - existing option can be deprecated and removed in future
 - changelog entry to notify of the new behaviour
 - `key/:key/`
     - `key/filename.json`, (`key/filename` or `key/filename.txt`)

**Comment by protolambda** [comment]
This may be useful for context and testing: https://github.com/protolambda/eth2-val-tools

I was trying to get it to work for Teku, but putting hundreds of key references in a cli command was not going to work nicely.

**Comment by ajsutton** [comment]
@protolambda For the record any command line option in Teku can also be put in a YAML config file.  But it's still annoying to have to list every key individually.

**Comment by protolambda** [comment]
Thanks, forgot about that. Still nice to refer to just the directories though, and that proposed approach is even better than in lighthouse, which still has data-dir customization issues.

**Comment by rolfyone** [comment]
so for workflow. i run a command to generate validator and withdrawal keys...
```
./build/install/teku/bin/teku validator generate \
    --deposit-amount-gwei 32000000000 \
    --eth1-endpoint=http://localhost:8545 \
    --eth1-deposit-contract-address=0xdddddddddddddddddddddddddddddddddddddddd \
    --eth1-private-key=0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3 \
    --number-of-validators=64 --network minimal  --keys-output-path ~/out
```

that gives me a folder full of keys:
```
➜  ~ ls ~/out/validator_917179e
validator_917179e.json
withdrawal_8804460.json
```

the password was requested on the console for both the validator and for the withdrawal key...

at this point i'd have to move my validator key, withdrawal key, and create a password file for each...

so then i have 
```
validator/validator_917179e.json
validator/validator__917179e
withdrawal/withdrawal_8804460.json
withdrawal/withdrawal_8804460
```

or 
```
validator/validator_917179e.json
withdrawal/withdrawal_8804460.json
secrets/validator_917179e
secrets/withdrawal_8804460
```

and now to run teku, i want to be able to specify my validators and keys at least, so i have this new option which i use by:

```
teku --validator-keys validator/:secrets/
```

and it will find `validator/validator_917179e.json` then look in the secrets folder for `secrets/validator_917179e`

Does that summarise the intent for this ticket for the workflow that's expected?

**Comment by ajsutton** [comment]
I would say we should also change the generate commands so that they put all generated keys in one directory rather than a separate directory per validator which will make this a bit easier.  I really don't think we should be writing the password to disk unless we add a specific option to do so (default to off).  Writing passwords unencrypted to disk is a very bad idea.

What should happen in a production situation is that the keys would be generated somewhere secure and the passwords added to a credentials manager (eg kubernetes secrets) which are often then exposed to the running host as a directory of files.

For the just trying it out kind of stuff then yeah you'd have to write the password to a file and copy it to the right name for each validator.

Ideally I'd love to be able to recommend an external tool like ethdo to create the keys and send the deposit contract, then just export them ready for Teku to load.  Launchpad is also being developed to be "the way" people deposit for main net but not sure of the details of that either (https://github.com/ethereum/eth2.0-deposit).

**Comment by rolfyone** [comment]
to flatten the folder structure, we'll change:
```
├── validator_814a1a6
│   ├── validator_814a1a6.json
│   └── withdrawal_8b3ad4d.json
├── validator_81ee3ca
│   ├── validator_81ee3ca.json
│   └── withdrawal_8077d79.json
```

for validator 814a1a6 (pubkey), we will generate
```
key/814a1a6_validator.json
key/814a1a6_withdrawal.json
```
and its password would be in 
```
secrets/814a1a6_validator
secrets/814a1a6_withdrawal
```

then part 2 is specifying the key folder and secrets folder to make this all work... they could easily be broken into separate concerns and worked on independent of each other at this point.
