### ISSUE TITLE
Support passphrase as bytes when reading from a file

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2004]
### Description

From @protolambda, the context being loading validator keys into Teku on the command line:

> the passphrase is handled as string instead of byte array. Maybe it's better to support any passphrase bytes, if it's read from a file anyway?

**Comment by protolambda** [comment]
Related:

I think lighthouse reads the full file, including any whitespace: https://github.com/sigp/lighthouse/blob/ad4e5adabc7b68a9e06ffc17a2df20575100e283/common/validator_dir/src/validator_dir.rs#L235

While teku only reads the first line: https://github.com/PegaSysEng/teku/blob/4239bddd68c45aa0bcce6d7a6f7c3392c3f465b9/teku/src/main/java/tech/pegasys/teku/cli/deposit/KeystorePasswordOptions.java#L35

cc @paulhauner we should standardize how passwords are read and written, so that a user does not get surprised when their password with whitespace from teku is invalid in lighthouse, or similar things the other way around (teku reading passwords as utf-8, while we could support raw bytes). There's already someone in the lighthouse discord who has this problem I think.

**Comment by ajsutton** [comment]
We trim line ending data because of lessons learnt with Besu and EthSigner which didn't trim passwords and we kept getting reports from users that their password wasn't working because the way they created the file just happened to append a line ending.

The big question is what the final recommended workflow will be for generating these files.  Currently Teku generates a keystore but deliberately doesn't write the password to disk because hopefully you're going to put it into something like k8s secrets.  But for a lot of users they wind up just creating a text file with the password right next to the keystore which works but rather defeats the point of encryption which leads to a high likelihood that there'll be a line ending added.  If keys are generated in a wallet and always exported with keystore and password files generated then we wouldn't normally get extra line endings and could just use the file as-is.

**Comment by benjaminion** [comment]
See recent changes around this in https://github.com/ethereum/EIPs/pull/2749

**Comment by ajsutton** [comment]
So with the changes to EIP2335 linked above, the password is explicitly a string of unicode characters.  It doesn't specify what unicode encoding is used when storing on disk which still leaves room for incompatibility between clients - Teku will continue to use UTF-8.

EIP2335 now requires all control characters to be stripped, so line endings at the end of the file should now be stripped by all clients (as would line endings in the middle of the file).  Teku will change to read the entire file for simplicity and the normalisation process will strip any trailing line endings.

Raised https://github.com/PegaSysEng/signers/pull/59 to implement these changes and will then need to pull that into Teku.
