### ISSUE TITLE
Reported discv5 bug: Nodes responses with a total greater than 5

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2095]
@AgeManning [on the Witti Discord](https://discord.com/channels/595666850260713488/707233122097299496/719798016277741592), referring to my Teku Witti node:
> If that's the case, then Teku's discv5 has a small bug. It sends Nodes responses with a total greater than 5 (which shouldn't happen)

**Comment by AgeManning** [comment]
To add further detail here. See this section of the spec: https://github.com/ethereum/devp2p/blob/master/discv5/discv5-wire.md#udp-communication

Because an ENR can be at most 300 bytes and the max packet size is 1280 bytes, we can fit at most 4 ENR's per Nodes response. Any request should return at most 16 peers, so accounting for extra encoding bytes etc a Nodes response shouldn't have or need a total > 5. 

I guess in principle you could follow the spec and just send a single ENR per Nodes response, but this would be fairly inefficient and they should probably be grouped.

**Comment by ajsutton** [comment]
Right that makes sense - we're limiting to 4 ENRs per Nodes response, but not limiting to 16 peers.

**Comment by AgeManning** [comment]
Thats kind of interesting. A Nodes response asks for a specific distance, and I'd expect you should just grab all the nodes in your bucket. A bucket should have a max of 16 peers. It's surprising that you store more peers than that for any given distance.

EDIT: Just looked at the PR, its a sync issue. Makes sense
