### ISSUE TITLE
Teku start script Win10: Syntax error. Command too long.

### ISSUE THREAD

**Issue by xtc0r** [Consensys-Incorporated/teku#2133]
### Description
* Using Windows 10 x64 with teku-0.12.0-SNAPSHOT
* Running bin\teku.bat throws a syntax error. The command is too long.

### Acceptance Criteria
* Start up scripts gets executed without error

### Steps to Reproduce (Bug)
1. Use Win10
2. Download teku-0.12.0-SNAPSHOT
3. run command: bin\teku

**Expected behavior:** [What you expect to happen]
Start up scripts gets executed without error

**Actual behavior:** [What actually happens]
syntax error. The command is too long

**Frequency:** [What percentage of the time does it occur?]
100%

### Versions (Add all that apply)
* Software version: [`teku --version`]
teku-0.12.0-SNAPSHOT
* Java version: [`java -version`]
jdk-14.0.1
* OS Name & Version: [`cat /etc/*release`]
Windows 10 64bit

**Comment by ajsutton** [comment]
Thanks for reporting this.  Could you confirm the build at https://28753-147802356-gh.circle-artifacts.com/0/distributions/teku-0.11.4-SNAPSHOT.zip works for you please?  

This is from the master branch so will be compatible with witti, but not Prysm's new Onyx testnet.  We regularly merge changes from master over to our v0.12 branch so 0.12.0 builds with this fix should come through within a few days of this being merged.

**Comment by xtc0r** [comment]
I can confirm https://28753-147802356-gh.circle-artifacts.com/0/distributions/teku-0.11.4-SNAPSHOT.zip is working and doesn't show this behavior.

So I should wait for a release of 0.12 and do not grab the snapshot?

**Comment by ajsutton** [comment]
Which version to use depends on which testnet you're trying to connect to. There are two incompatible versions of the beacon chain spec currently in use (because not all clients are ready for the new version and some testnets are still running the older one).

So:
- The Witti testnet uses beacon chain spec 0.11.3, which is supported by the 0.11.x series of Teku releases and our master branch.  The build I linked to above is fine to use to connect to Witti.
- Prysm's new Onyx testnet uses beacon chain spec 0.12.1 which is supported by the 0.12.x series of Teku releases and our 0.12.1-integration branch.  Our v0.12.1 support is very new and still untested (not even sure if we agree on the Onyx genesis state yet).

So my recommendation would be to use the build I link above and connect to the Witti testnet (`bin\teku.bat --network witti`) which we know works well.  The fix will find it's way into both master and 0.12.1-integration branch in time and both should get a release put out later this week.   Because things are changing so rapidly we recommend that most people use the very latest -SNAPSHOT builds of either the 0.11 or 0.12 streams and not wait for a release.  You may hit a few more unexpected bumps doing that but finding issues is the aim of these testnets so it would really help us with getting ready for the real beacon chain main net.

**Comment by xtc0r** [comment]
Sorry that I wasn't clear. I want to use the latest version reflecting 0.12.1 spec.
I'll wait until teku is ready for Onyx or Altona. Thanks!

**Comment by ajsutton** [comment]
For the record, this fix has now been merged into the 0.12.1-integration branch.  We're still primarily focussed on Witti though so haven't done any significant work to investigating compatibility with Onyx.  It's likely to be unstable at this point.
