### ISSUE TITLE
Test interop on Onyx testnet

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2158]
### Description
Ensure Teku connects to and follows the Onyx testnet well.

**Comment by Nashatyrev** [comment]
Oh yeah, epoch transition is 114sec instead of 400ms on `main` branch. Looks like some caches were lost.

**Comment by Nashatyrev** [comment]
Not caches. This optimization was lost: https://github.com/PegaSysEng/teku/pull/1109 and quadratic difficulty is back. 
@ajsutton you were right :)

**Comment by Nashatyrev** [comment]
Also interesting slowdown:
![изображение](https://user-images.githubusercontent.com/8173857/85009743-9eab5d80-b167-11ea-8a91-56295f2e36f4.png)

**Comment by Nashatyrev** [comment]
Done! We are on Onyx head. Synced 30K+ slots in 2+ hours :tada:
Heap consumption at the end of initial sync: 650M
After restart the storage initialization took ~1.5min

While we are able to sync at ~10 blocks/sec, we are effectively syncing at ~5 blocks/sec rate. This because we are spending just 50% of time in the transition code. My suspicion is that another part of time we are just waiting for blocks from the sync system.
