### ISSUE TITLE
Peer counts via API and metrics differ

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2177]
Currently, via API gives a peer count of 19:

```
$ curl http://localhost:5051/network/peer_count
19
```

Via metrics gives a peer count of 23:

```
$ curl http://localhost:8008/metrics 2>/dev/null | grep peers
# HELP libp2p_peers Tracks number of libp2p peers
# TYPE libp2p_peers gauge
libp2p_peers 23.0
# HELP network_peer_goodbye_total Total number of goodbye messages received from peers
```

It would probably be better to expose something like `beacon_peer_count` via the metrics interface (I'm compiling a list of other ways we can enhance the metrics). I don't know which of these is the more relevant.

**Comment by ajsutton** [comment]
The API only reports peers that have completed the status handshake and are ready to sync off.  The metrics reports how many connections (which matches what the eth2 metrics spec wants).  I suspect the API is wrong and should report the number of connections.

**Comment by rolfyone** [comment]
'bug' is probably a harsh term given they're different measurements.

All the same, i've added `beacon_peer_count` which tracks the same measurement so you can get the same values in grafana as the console and api.

I ended up listing the change under improvements in the changelog rather than under bug fixes.chang
