### ISSUE TITLE
Persist generated NodeID PrivKey when not supplied 

### ISSUE THREAD

**Issue by Nashatyrev** [Consensys-Incorporated/teku#2209]
### Description

When no `--p2p-private-key-file` option is supplied Teku generates a random KeyPair for NodeID every launch 
It would be more convenient if the private key generated on the first run is persisted and used on subsequent runs when `--p2p-private-key-file` is not set explicitly.

**Comment by protolambda** [comment]
Confirming this issue. I see the peer ID change and can't use my enr anymore after a restart. Will configure with `--p2p-private-key-file` for now.

**Comment by benjaminion** [comment]
This is a dup of #1961.

**Comment by benjaminion** [comment]
I closed #1961, but also see the comments there as they are relevant to implementing this properly (I.e. Seq number handling).

**Comment by protolambda** [comment]
If this is still open because of the complexity with secret key handling, maybe the implementation of seq-number persistence should be prioritized? That would avoid any bugs or unexpected behavior caused by the use of the same p2p private key after a restart (with that cli flag). Or is that already part of the discv5 library? Is the discv5 data persisted anywhere?
