### ISSUE TITLE
Limit number of connections per IP

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#2515]
### Description
I can open thousands of connections to Teku from a single IP using the following code:

```python
#!/usr/bin/python3
import os
import threading
import socket
import time

def main():
    threads = []
    for i in range(150):
        thread = threading.Thread(target=worker, args=(i,))
        threads.append(thread)
        thread.start()

def worker(worker_id):
    pid = os.getpid()
    while True:
      sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
      sock.connect(("192.168.1.212", 13001))
      print("Worker {} connected".format(worker_id))
      time.sleep(20)
      sock.close()

if name == "__main__":
    main()

```

I can spawn multiple instances of it and potentially overload Teku with open connections.  The following command shows my teku instance using 2300+ file descriptors

```
$ lsof | awk '{print $1}' | uniq -c | grep "java"
2330 java

```

**Comment by rolfyone** [comment]
to accomplish this, the plan seems to be 
 - update libp2p to have a handshake timeout, terminating connections that fail to conform within a given time
 - update libp2p to limit new incoming connections so there's only a certain pool size for incoming streams.

To prevent DOS, there should be still room for us to start outgoing connections without causing issues.

I've played around a bit with teku to try to get some of this happening, but by the time the PeerManager gets involved, all the handshaking is completed, so we can't really terminate non compliant incoming connections at that layer.

I've updated the script a little to print + NUM when connecting, and - NUM when it detects a disconnection, but the disconnection is not currently shown, because we don't terminate the connections. It might be helpful when actually making the change, so i've included here.

```
#!/usr/bin/python3
import os
import threading
import socket
import time

def main():
    threads = []
    for i in range(10):
        thread = threading.Thread(target=worker, args=(i,))
        threads.append(thread)
        thread.start()

def worker(worker_id):
    pid = os.getpid()
    while True:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.connect(("127.0.0.1", 9000))
        print("+ {}".format(worker_id))

        for counter in range(20):
            if is_socket_closed(sock):
                print("- {}".format(worker_id))
                break
            time.sleep(1)

        sock.close()

def is_socket_closed(sock: socket.socket) -> bool:
    try:
        # this will try to read bytes without blocking and also without removing them from buffer (peek only)
        data = sock.recv(16, socket.MSG_DONTWAIT | socket.MSG_PEEK)
        if len(data) == 0:
            return True
    except BlockingIOError:
        return False  # socket is open and reading from it would block
    except ConnectionResetError:
        print("  => connection reset")
        return True  # socket was closed for some other reason
    except Exception as e:
        print(e)
        print("  => unexpected exception when checking if a socket is closed")
        return False
    return False

if __name__ == "__main__":
    main()

```

**Comment by ajsutton** [comment]
Closing this one - there may be some value in limiting by IP but Anton has shown it's actually quite easy to just use a lot of different IPs and teku can handle the number of open connections fine given libp2p closes them out fairly quickly.  Java also ups the file descriptor limit as far as it's allowed when it first starts so users have to specifically set tight restrictions to have issues (and then leveldb and java's file handle usage are likely to cause them more problems than network connections).
