### ISSUE TITLE
Validator failed to produce block

### ISSUE THREAD

**Issue by uvizhe** [Consensys-Incorporated/teku#2566]
### Description
My teku validator has failed to produce block.
A console log shows this message:
```18:33:46.054 ERROR - Validator   *** Failed to produce block  Slot: 58368 tech.pegasys.teku.core.StateTransitionException: tech.pegasys.teku.core.exceptions.BlockProcessingException: java.lang.IllegalArgumentException: process_operations: Verify that outstanding deposits are processed up to the maximum number of deposits (See log file for full stack trace)```

Here is a corresponding fragment from teku.log: [gist](https://gist.githubusercontent.com/uvizhe/40dd3947b31c2c68e53349c4a8824b43/raw/f0ad7ada93be9a78a8edfc3c189228b4ad444149/teku.log)

### Versions (Add all that apply)
* Software version: `teku/v0.12.3-dev-fe0dc3ed/linux-x86_64/oracle-java-14`
* Java version: `java version "14.0.2" 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)`
* OS Name & Version: `Ubuntu 18.04.5 LTS`
* Kernel Version: `4.15.0-112-generic #113-Ubuntu SMP`
* Eth1 client: `Geth 1.6.5-stable-cf87713d`

**Comment by rolfyone** [comment]
thanks for raising this, we'll look at it as soon as possible!

**Comment by cemozerr** [comment]
Hi @uvizhe,

Any chance you have the logs around that time? Not only the error but some logs before and after? That could help us identify the state Teku was in when the issue happened.

**Comment by uvizhe** [comment]
Hi @cemozerr,
Unfortunately, I can't find necessary teku logs in `~/.local/share/teku/` anymore. Probably, I've deleted them to clean some space.

**Comment by mbaxter** [comment]
It looks like you could've failed to produce a block here if the eth1 node you were connected to failed to send 1 or more deposit events.  Added extra validation to make sure that the eth1 data we receive is complete.  Teku will now fail to start if any data is missing from our stored eth1 deposits, and we will print warnings if any ongoing requests for deposits return a response with missing data.

If your node fails to start up due to bad stored deposit data, at this point you'll have to resync your node.  If you do need to resync, be careful not to delete the `validators` folder inside of your data directory.
