### ISSUE TITLE
Remote Wallet

### ISSUE THREAD

**Issue by madhancr** [Consensys-Incorporated/teku#2675]
### Description
As an [Actor], I want [feature] so that [why]. 

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. [Step 1]
2. [Step 2]
3. [Step ...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: [`teku --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

### Additional Information

Hello, 
1) Does Teku work with remote wallet Dirk - https://github.com/attestantio/dirk
2) Can you unify the commands for remote wallet with other eth2 clients like Prysm? Right now, how we use remote wallet is different for these clients. Unifying them will make it easy for users and swithcing between clients as well.

**Comment by ajsutton** [comment]
Unfortunately Dirk uses a different remote signing API to Teku and eth2signer so it doesn't currently work with Teku.  We would definitely be open to supporting Dirk but it isn't currently something we're able to work on.  We'd definitely be happy to accept contributions and help anyone who was interested in developing that support though.

In terms of the commands use to configure external signers, these will necessarily differ between clients because each client takes a different approach to how they manage keys and do configuration.  That said, if ETH2 in general can standardise on an API for external signers then the differences in how to configure clients shouldn't be a significant barrier for users to switch clients.  Just at the moment each signer seems to expose a different API which makes it very hard for clients to support them all.

I've logged https://github.com/PegaSysEng/teku/issues/2681 to track the request to support Dirk. As I said, it's not something we'll be able to work on immediately but good to have a record that it's a desirable thing to have.

I'll close this ticket for now, if you have any follow up questions our Discord is probably the best place to ask: https://discord.gg/7hPv2T6
