### ISSUE TITLE
414 error from /eth/v1/validator/duties/attester

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2838]
Report from @mcdee via Discord
> I'm receiving a 414 error from /eth/v1/validator/duties/attester.  I'm throwing a lot of validators at it (~3,500, I think) but I'd hope that we can handle suitably large URLs.  Could you give me some background on what limits are in place, and why?

From @rolfyone 
> HTTP 414 is URL too long, we're not restricting it,  I can't find anything that's limiting it from the javalin side specifically (our web api). There's references to query length keeping within 2000 characters, which i recall vaguely as the reason why we were doing a post for the duties... but i've found nothing concrete as to an exact length. I'll do a little more digging, hopefully its something we can explicitly increase

**Comment by rolfyone** [comment]
https://stackoverflow.com/questions/27950281/dropwizard-how-to-fix-414-request-uri-too-long

to the best of my knowledge the current jetty default is 8k, not 2k, and there's some strong sentiment about whether its safe to increase it. Having said that, apache does run at a considerably higher limit...
I've asked on the javalin glitter if there's a way to increase the limit easily.

**Comment by rolfyone** [comment]
https://github.com/PegaSysEng/teku/pull/2840 would fix the problem, *but* we're probably not going to merge it...

Discussions on the standard api have basically pushed towards using a `POST` instead of a `GET` for attester duties, which will allow the indexes to be delivered in the body of the request, which is not bound by the header limits.
raised ticket https://github.com/ethereum/eth2.0-APIs/issues/92

**Comment by rolfyone** [comment]
the API spec has been updated to have attester duties as a POST, rather than a GET. I'll start on implementing that
