### ISSUE TITLE
signing spikes

### ISSUE THREAD

**Issue by tzapu** [Consensys-Incorporated/teku#2860]
# Description
Noticed there is a large spike of signings at the start of each epoch, I assume to find out which slot a validator needs to aggregate.

![image (3)](https://user-images.githubusercontent.com/2983312/94412829-f43dd000-0182-11eb-86f6-8e7377e0740f.png)

**Expected behavior:** [What you expect to happen]
It would be ideal if these signing requests could be spread over a lengthier amount of time, maybe only for nodes that know will be subscribed to all subnets. Not having spikes like that could potentially make or break the usage of hardware signers, which are not that great in the performance department (currently), on top of that, less network congestion at once (for remote signers) = less timeouts under heavier loads

**Frequency:** [What percentage of the time does it occur?]
every epoch

**Comment by ajsutton** [comment]
So my original idea to smooth out these spikes was to sign the slot number an epoch ahead of when we can calculate duties, but that doesn't actually work out because we don't yet know which slot each validator will be assigned from the epoch so instead of signing one slot number per validator we'd have to sign every slot number in the epoch with every validator (32x more signatures).  While we'd spread them out, 32x more work is probably not a good trade off.

So I can see two options that would work:
1. Assume we want to subscribe to the attestation subnet we'll aggregate 1 epoch ahead, which is the minimum we currently have.  Instead of performing all signatures to determine if we're aggregating as soon as duties are calculated (strart of epoch) we only sign the duties for the first slot, then each slot we do the signing to check the aggregators one epoch ahead. So slot 32 we check which validators aggregate slot 64, slot 33 we check which validators aggregate slot 65 etc.  This is the same number of signatures, smoothed out with peaks 32x lower, but still spiking each slot.

2. Batch the validators into groups based on the epoch's they attest similar to above, but instead of waiting for each slot to progress, check the first batch and once it's complete, immediately check the next etc. This doesn't smooth out the signing as much but still limits the rate at which signing occurs so there's only ever one slots worth of validators in-flight at a time.

With the current setup if you had `n` validators, at the start of each epoch you'd get a spike of `n` signing requests.
With option 1 at the start of each slot you'd get a spike of `n / 32`
With option 2 at the start of the epoch you'd get 32 spikes of `n / 32` signing requests one after the other.  But we could also have a cap on the number of signing requests put into each batch so reduce the size of the spike arbitrarily at the cost of delaying the determination of what we're aggregating slightly.

I think I'd actually lean towards option 2 as being the most scalable if we had a configurable limit on the maximum size of batches used. While its sustained load, it's a lot more configurable and I suspect makes for a much more self-contained change in Teku.

**Comment by tzapu** [comment]
i'm good with whatever option you see as a best fit that would limit the huge spike, don t have a preference for 1 or 2, the max number of requests in flight at one instant seems to be at most the same
