### ISSUE TITLE
Teku node not syncing

### ISSUE THREAD

**Issue by lufa23** [Consensys-Incorporated/teku#2890]
Hi, i started a Teku node with:

teku --network=medalla --metrics-enabled --rest-api-enabled --rest-api-docs-enabled

in order to gather some metrics.

Anyway, the node does not seem to be syncing
![Screenshot 2020-10-06 at 11 52 16](https://user-images.githubusercontent.com/67415638/95186561-68532600-07ca-11eb-98bc-d3b4dd70b831.png)

How can i solve this issue?
Thanks

**Comment by ajsutton** [comment]
Hi,
The node isn't syncing because it can't find any peers. It's hard to know why not from the small snippet of log. If you could include the full log content that would be very useful.

Also, what version of Teku are you running? Is it possible that something else is using port 9000 - often this is a Lighthouse instance on the same machine?

https://docs.google.com/document/d/1YWi4HqkGqs9PQA67agHON4PciPKO39mlZwH_3AKg68I/edit?usp=sharing includes some useful trouble shooting tips for common issues, including a link to a guide to open incoming ports which can help to find more peers.

**Comment by lufa23** [comment]
Here it is:

Teku version: `teku/v0.12.9-dev-4c2a25f7/osx-x86_64/oracle-java-13`
With `lsof -i :9000` i made sure there are no processes running on that port.
Here the whole log i got:
<img width="1668" alt="Screenshot 2020-10-13 at 16 07 35" src="https://user-images.githubusercontent.com/67415638/95872119-c05fce80-0d6e-11eb-86e3-25b109ff0587.png">

**Comment by rolfyone** [comment]
While teku is running, just for sanity, maybe check what's on 9000 and 5051...
```
sudo lsof -i :9000 -i :5051
```

5051 is the default rest port, should be accessible as localhost generally speaking:

```
curl -X GET "http://localhost:5051/eth/v1/node/version" -H "accept: application/json"
```

Is the `listening for connections on: /ip4/192.168.22.152/tcp/9000` the expected ip address? Potentially you could open up port 9000 from your firewall if you have access, then other peers should be able to connect to you. Having said that, you should be able to connect outwards, so i would have expected your peers to go beyond 0 even if you are just connecting to peers and they're not able to request a connection to you...

If none of that sheds any light, it might be worth clearing out log files, and just running a trace session for a short time (a couple of minutes would be plenty)...

```
rm -f ~/Library/teku/logs/teku.log
teku --network mandella --metrics-enabled --rest-api-enabled --rest-api-docs-enabled --logging trace
```

And if we could grab a copy of that trace file (`~/Library/teku/logs/teku.log`) as a gist, then we can dig further into the problem hopefully with a bit of an idea from the trace.

Sorry, these are mostly vague, because I'm just trying to get a better context of what might be going on...

**Comment by lufa23** [comment]
thanks, i have just run Teku connected to another WIFI network, and it is currently syncing with peers. So i guess it is a firewall/ IP problem. I will try your suggestions as soon as i have access to the other facility and see how to fix it

**Comment by rolfyone** [comment]
It's also possible for networks to block p2p traffic, which sounds like a plausible explanation if the same setup is working now, but it's only a 'possible' explanation. Just mentioning here as another possible thing to investigate if you have access to the sites firewall, or know the admin.

Some ISP's also block it, but i'm not 100% sure how you'd verify that it's an ISP unless it's on their site. Just another possibility if it works on the other network.
