### ISSUE TITLE
Add bounds check on UnsignedLongs

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#312]
### Description
I want to augment UnsignedLong's capabilities with extension methods, but Java doesn't support these natively.  Investigate the use of Manifold (or some other method) to give us the desired functionality.

http://manifold.systems/docs.html#extension-method-basics

I would like to have an easy way to do a bounds check on UnsignedLongs automatically when we do an UnsignedLong.plus() or UnsignedLong.minus().  

### Acceptance Criteria
Add the following extension methods to UnsignedLong:
* tryMinus()
* tryPlus()
* tryLongValue()
* tryIntValue()
* integrate into the rest of Artemis

> Note: tryMinus() and tryPlus() methods should throw an error if an underflow or overflow is detected

**Comment by atoulme** [comment]
Here is a proposal via Cava: https://github.com/ConsenSys/cava/pull/173

**Comment by jrhea** [comment]
Here is the issue where this will be debated:

https://github.com/ethereum/eth2.0-specs/issues/626

**Comment by jrhea** [comment]
I'm thinking that we might want to switch to Cava's uint64 type now that it is backed by long and has implemented some convenience methods for overflow detection

**Comment by akhila-raju** [comment]
@jrhea, has this been completed or is it still an open issue?

**Comment by jrhea** [comment]
@akhila-raju it is still an open issue.  I think we want to replace unsigned long with uint64 from cava. Antoine created an implementation that didn't rely on big integer

**Comment by akhila-raju** [comment]
For the sake of easier code readability and maintainability, we have decided to switch to long, since mathematical functions (addition, subtraction, multiplication, division, modulo, amongst others) are already supported by Java for longs. Every time we use an UnsignedLong to index an array, it has to be cast to an integer. Java already has long to int cast support. 

If we were to keep UnsignedLong, there would be many files we would have to maintain, including SSZ implementation for UnsignedLong, all supporting mathematical functions implemented for UnsignedLong, etc. It's unnecessary overhead since integer indexes are the major limiting factor of using UnsignedLong. 

Thus, to keep it simpler, we have decided, going forward, to use Java's native long rather than UnsignedLong.
