### ISSUE TITLE
TLS connection to external signer

### ISSUE THREAD

**Issue by jframe** [Consensys-Incorporated/teku#3121]
### Description
As a user, I want a TLS connection to the external signer so that signing data can be sent securely to the signer.

### Acceptance Criteria
* Allow TLS to be used for the external signer
* TLS client authentication of the external signer

**Comment by usmansaleem** [comment]
# Creating Self Signed PKCS12 keystores and trust stores for Teku and Web3Signer

Following examples use keytool utility which is available with JDK installation. OpenSSL can also be used to achieve similar results.

## KeyStores
### For Web3Signer (Server)
Web3Signer uses a PKCS12 keystore. Following command can be used to generate a self-signed private key/certificate pair.
~~~
keytool -genkeypair -keystore web3signer_keystore.p12 -storetype PKCS12 -storepass changeit -alias web3signer -keyalg RSA -keysize 2048 -validity 109500 -dname "CN=localhost, OU=PegaSys, O=ConsenSys, L=Brisbane, ST=QLD, C=AU" -ext san=dns:localhost,ip:127.0.0.1
~~~
The CN is usually the fully qualified hostname of Web3Signer. In addition, san extension can be used to change and/or add additional hostnames and/or IP address if required. For example:
`-ext san=dns:localhost,dns:serverHostName,ip:10.0.0.2,ip:127.0.0.1`
This will allow the same certificate to be used for more than one hostname/IP address specially if web3signer is running on a different machine than Teku with multiple hostnames.

### For Teku (Client)
Teku can use either PKCS12 or JKS keystore type. PKCS12 is recommended. This is the certificate that Teku will present to Web3Signer for TLS mutual authentication. If Web3Signer doesn’t recognize this certificate’s signature, it will reject the connection. Following command can be used to generate a self-signed private key/certificate pair.

~~~
keytool -genkeypair -keystore teku_client_keystore.p12 -storetype PKCS12 -storepass changeit -alias teku_client -keyalg RSA -keysize 2048 -validity 109500 -dname "CN=teku, OU=PegaSys, O=ConsenSys, L=Brisbane, ST=QLD, C=AU"
~~~

The CN doesn’t have to be the hostname for Teku as a client. However, it must be a lowercase value, such as “`CN=teku,`” as shown in above example.

## Trust Stores
Trust stores are required to trust the certificates of the other party for TLS mutual authentication.

### Create TrustStore For Teku (to trust Web3Signer certificate)
Teku can use a PKCS12 (or JKS) keystore to trust web3signer certificate. This keystore is referred to as a truststore since it only contains trusted certificate entry. It is a two step process to create it. 

* Export public certificate
First, export public certificate (to PEM format) from web3signer keystore:
`keytool -exportcert -keystore ./web3signer_keystore.p12 -alias web3signer -rfc -file web3signer.pem`

* Import into Truststore
Second, import the public certificate into a truststore that will be used by Teku
`keytool -importcert -storetype PKCS12 -keystore web3signer_truststore.p12 -alias web3signer -trustcacerts -storepass changeit -file ./web3signer.pem`

### Create Known Clients File for Web3Signer (to trust Teku certificate)
Web3Signer uses a known clients file to trust client certificates i.e. Teku. Use keytool to obtain common name and SHA signature:
~~~
keytool -list -v -keystore teku_client_keystore.p12
~~~
Take a note of:
~~~
CN=teku
SHA256: 67:89:C8:95:70:E0:38:10:2F:AB:7E:A3:75:4A:8C:29:C1:64:52:37:E5:E9:CD:EF:CD:27:C2:88:BF:84:3A:A1
~~~
Create a file called `knownClients.txt` with following contents (CN and signature, space separated on one line):
~~~
teku 67:89:C8:95:70:E0:38:10:2F:AB:7E:A3:75:4A:8C:29:C1:64:52:37:E5:E9:CD:EF:CD:27:C2:88:BF:84:3A:A1
~~~
