### ISSUE TITLE
Add endpoint for retrieving SSZ serialized states

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#3165]
### Description
Once #3063 is complete, users will be able to sync from a recent state.  To support this functionality, we should provide an endpoint to export states in a format the can be imported (SSZ).  This is a non-standard API, so we should add it to a "teku" namespace for now. 

Suggested parameters:
* A checkpoint argument (<BLOCK_ROOT>:<EPOCH_NUMBER>):  Return the state associated with the checkpoint's block root
* No argument:  Return the latest finalized state

**Comment by mcdee** [comment]
Note that there is an endpoint in the standard APIs that returns a state: https://ethereum.github.io/eth2.0-APIs/#/Debug/getState

The general idea to notify the server that SSZ is required would be through an Accept header.  We could use application/octet-stream, or define our own custom MIME type.

If this is something that all beacon nodes are going to need then it would be good to firm it up in the standard API.

**Comment by mbaxter** [comment]
Agreed @mcdee - if this functionality is useful, we'll want to move this into the standard API.

**Comment by ajsutton** [comment]
@mcdee My only concern with using Debug/getState is that I really don't like describing it as a debug API.  Given you're going to this API to get the canonical starting point for sync to resolve security risks with the weak subjectiivty period, having the API labelled debug is not particularly confidence inspiring.

But otherwise I do really like the ability to just set an `Accept` header to specify the output format - we've been planning to do that for anything that returned a block or state for quite a while but never quite gotten to it.

**Comment by mcdee** [comment]
Agree that if this is used for syncing it should be promoted to a non-debug location.  Is this something that will be across all clients before mainnet launch?  If so we could push to have it included before we freeze the API (although we do need to finalize the API ASAP, so may have some pushback for making it in to the spec at this late stage).

Regarding location, it would seem that an `/eth/v1/beacon/states/{state_id}` endpoint wouldn't be an unreasonable place to put it.
