### ISSUE TITLE
BLS tests are being flaky

### ISSUE THREAD

**Issue by cemozerr** [Consensys-Incorporated/teku#3175]
The tests below fail on circle CI sometimes: 
- succeedsWhenAggregateVerifyWithInfinitePairReturnsFalse() - tech.pegasys.teku.bls.BlstBlsTest
- batchVerify2InfinitePublicKeyAndSignature() - tech.pegasys.teku.bls.BlstBlsTest
- batchVerifyInvalidInfiniteSignature() - tech.pegasys.teku.bls.BlstBlsTest
- aggregateInfinitePublicKeyAndSignature() - tech.pegasys.teku.bls.BlstBlsTest
- batchVerifyInfinitePublicKeyAndSignature() - tech.pegasys.teku.bls.BlstBlsTest

Here is a link for a failed run along with its stack trace:
https://app.circleci.com/pipelines/github/ConsenSys/teku/8694/workflows/dae81c59-287a-4cf6-ad78-e1ea2b8a780f/jobs/54803

We've seen in the past that Constants that are set, but not reset, for a test that is run previous to another test can be an issue. So that could be a good starting point.

**Comment by Nashatyrev** [comment]
Yep, seen that once as well. Was surprised

**Comment by Nashatyrev** [comment]
Another case: https://app.circleci.com/pipelines/github/ConsenSys/teku/8846/workflows/24077d22-0097-440e-b664-91b7af7cfee1/jobs/55828

**Comment by Nashatyrev** [comment]
Most likely this is because of: 
- Tests are executed in parallel 
- BLS implementation is controlled via static `BLS.setBlsImplementation()` field 
- BLS tests both implementations (Mikuli and Blst) switching them with the static field above
- Apparently a signature is created when Mikuli implementation is 'active', then the parallel test switches implementation to Blst and Mikuli signature passed to the Blst implementation 

The right way to fix this would be to refactor the `BLS` class making it an interface, derive implementation classes from it and pass a `BLS` instance to tests. This is tightly related to enhancement #2716

The fast way to fix this would be to make bls entities interoperable in direction `Mikuli` -> `Blst`. The opposite interoperability already exists (was done just for the case): 
https://github.com/ConsenSys/teku/blob/52d464b174dcfac282eb878e98da4341624205b6/bls/src/main/java/tech/pegasys/teku/bls/impl/mikuli/MikuliSignature.java#L62-L68
https://github.com/ConsenSys/teku/blob/52d464b174dcfac282eb878e98da4341624205b6/bls/src/main/java/tech/pegasys/teku/bls/impl/mikuli/MikuliPublicKey.java#L52-L58

**Comment by Nashatyrev** [comment]
I'm worried that other tests could also be affected with BLS implementation switching in parallel

**Comment by Nashatyrev** [comment]
Also we anyway couldn't achieve full `Mikuli <-> Blst` interoperability because we can't convert `BatchSemiAggregate` from one implementation to another

**Comment by Nashatyrev** [comment]
Stacktrace sample to memorize here:
```
java.lang.ClassCastException: class tech.pegasys.teku.bls.impl.mikuli.MikuliSignature cannot be cast to class tech.pegasys.teku.bls.impl.blst.BlstSignature (tech.pegasys.teku.bls.impl.mikuli.MikuliSignature and tech.pegasys.teku.bls.impl.blst.BlstSignature are in unnamed module of loader 'app')
	at tech.pegasys.teku.bls.impl.blst.BlstBLS12381.lambda$aggregateSignatures$1(BlstBLS12381.java:145)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at tech.pegasys.teku.bls.impl.blst.BlstBLS12381.aggregateSignatures(BlstBLS12381.java:145)
	at tech.pegasys.teku.bls.impl.blst.BlstBLS12381.aggregateSignatures(BlstBLS12381.java:38)
	at tech.pegasys.teku.bls.BLS.aggregate(BLS.java:125)
	at tech.pegasys.teku.bls.BLSTest.succeedsWhenAggregateVerifyWithInfinitePairReturnsFalse(BLSTest.java:182)
```

**Comment by ajsutton** [comment]
I don't *think* tests run in parallel within the same JVM - could be wrong, but then we'd see a lot more issues with `Constants` not matching expectations. But what might be happening is that we're creating and storing a `BLSSignature` or some other object in a static variable, then it gets used after the BLS implementation has changed.  Might be worth double checking that anything that changes the BLS implementation switches it back in a `@After` block.

**Comment by Nashatyrev** [comment]
Hm, you are right. Just checked - several JVMs are spawn

**Comment by Nashatyrev** [comment]
Heh, I think I found the suspect:

https://github.com/ConsenSys/teku/blob/38b4313451d3099a5e1d45db27f4a8c68e498642/bls/src/test/java/tech/pegasys/teku/bls/BLSTest.java#L205-L219

`BLSTest` is abstract and overridden for both implementations. So probably those fields are initialized when first running Mikuli impl and then we are trying to use them in Blst 

Will check tomorrow. 

@ajsutton thanks for your doubts :)
