### ISSUE TITLE
Optimization: RocksDbHotDao.addVotes consumes ~30% of long sync performance

### ISSUE THREAD

**Issue by Nashatyrev** [Consensys-Incorporated/teku#3320]
### Description

![изображение](https://user-images.githubusercontent.com/8173857/100344347-b8dc4800-2ff1-11eb-8efb-a6e6921624fa.png)

Every individual vote is stored to DB which seems sub-optimal. Likely it would be more optimal to keep in-memory map and save/load it as a solid

**Comment by rolfyone** [comment]
PR #3427 takes a chunk out of the numbers, but its an incremental improvement - doesn't change the overall design just puts in a custom serializer so that none of the decision points in the generic serializer are required.

The improvement is fairly decent for both deserialize and serialize, added a benchmark test and outputs in the PR mentioned above. I won't close this ticket, but it's worth noting that there's been reasonable improvements.

Over long sync, I was previously seeing addVotes as roughly 54% of the 'doUpdate' time, and after the change it's down to about 39%.

**Comment by cemozerr** [comment]
I synced the latest master to mainnet for 10 minutes from the genesis block and used the Java Flight Recorder to generate the flame graph below and `addVotes` function was nowhere visible. 

This might not be an issue anymore, but the difference in our results are so stark that @rolfyone it might be a good idea for you to re-run the profiler 

![Screen Shot 2021-01-05 at 6.27.39 PM.png](https://images.zenhubusercontent.com/5e8a67e476d894cf9836956c/6f523099-4cdf-462c-9c1f-ea14e395dc75)

**Comment by rolfyone** [comment]
![Screen Shot 2021-01-12 at 11.55.53 am.png](https://images.zenhubusercontent.com/5e45dddb5e32e495879572b3/a3632583-b24d-42a9-8bb0-4d72db663eb3)

so it's reporting 36% of the update time now during a long sync of pyrmont...

**Comment by Nashatyrev** [comment]
During long sync on `Prater` `storeVotes` takes roughly 40% of overall sync process (excluding BLS verification in `ForkJoinPool`):
![изображение](https://user-images.githubusercontent.com/8173857/112291004-cdc7a000-8ca0-11eb-8d2d-d9b0668fe1ed.png)

**Comment by Nashatyrev** [comment]
Potential idea to optimize this: 
- keep the full `Map` in memory
- sequentially write updates in a single serialized `Map`. I bet it should be much faster than writing individual entries
- prune old updates 
- On start incrementally restore the memory map

Do you think this makes sense?

**Comment by Nashatyrev** [comment]
Also do we really need updating votes during long sync until some distance behind head slot?

**Comment by ajsutton** [comment]
Actually when syncing finalized blocks we could skip processing the attestations entirely for fork choice (no vote or protoarray updates).  The block processing would still process them to do the justify/finalize updates but we could skip all of fork choice.

The catch is that currently the block import process doesn't know it's importing what should be a finalized block because from it's point of view it isn't yet finalized.  We'd have to pass a hint down from the sync system.

**Comment by ajsutton** [comment]
Going to close this one out as we're not using RocksDB anymore and so much has changed in terms of performance profile that while changing the way we store votes may still be a worthwhile optimisation we should ensure we're guided by up to date profiling in deciding what to focus on first.
