### ISSUE TITLE
[Feature Request] Support for reading graffiti from file

### ISSUE THREAD

**Issue by Doppelbock42** [Consensys-Incorporated/teku#3373]
### Description
As a validator, I would like support for reading graffiti from a file so that I can preserve my privacy and draw Leslie the Rhino on the https://beaconcha.in/graffitiwall. 

**Expected behavior:** 
Something similar to what Prysm has, https://docs.prylabs.network/docs/prysm-usage/graffiti-file/. Prysm lists 3 options, Specific , Random, and Default. The Specific option where you can set graffiti based on validator ID is important so you can preserve privacy by not linking your validators. I'd also add another option called List, where it goes down a list of graffiti and repeats the list. List is similar to Random but in random some items might never get picked.

### Additional Information
This is mostly a fun feature but it does address a privacy concern where validators can be linked by using the same graffiti.

**Comment by rolfyone** [comment]
Thanks for raising this, we'll look into it.

**Comment by ajsutton** [comment]
For anyone looking to implement this, my suggestion would be to start from https://github.com/ConsenSys/teku/blob/513d969759df60e495822f7eda82ac593e32188d/validator/client/src/main/java/tech/pegasys/teku/validator/client/Validator.java#L27

The beacon chain can also provide a default graffiti at https://github.com/ConsenSys/teku/blob/848fd9c0282d17f3623741ed09d56c12141c09e3/validator/coordinator/src/main/java/tech/pegasys/teku/validator/coordinator/BlockFactory.java#L131

In both places it may make sense to introduce a `GraffitiLoader` class which is responsible for getting the graffiti rather than just passing in `Optional<Bytes32> graffiti`. `GraffitiLoader` could then handle loading the latest value from file or just supply the literal value as it does today and it makes it easy to reuse between the validator client and beacon chain.

It should also handle any failures to read the file and ensure the block creation doesn't fail (likely log an error and return the empty string if the file can't be loaded).

**Comment by ajsutton** [comment]
This was added with #3414.
