### ISSUE TITLE
PLEASE CHECK YOUR ETH1 NODE | Wrong Eth1 chain id (expected=1, actual=0)

### ISSUE THREAD

**Issue by rkandel** [Consensys-Incorporated/teku#3412]
Hi, 
I am trying to setup Teku Validator with Geth client and getting error message "07:28:59.256 ERROR - PLEASE CHECK YOUR ETH1 NODE | Wrong Eth1 chain id (expected=1, actual=0)" all the time.

I am using --network=mainnet and syncmode="full" and  console verbose  says "ChainID:1 ..." as shown below. Could somebody let me know what am I missing here.

config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, YOLO v2: <nil>, Engine: ethash}"

**Comment by ajsutton** [comment]
While Geth is syncing, it returns 0 as the chain ID because the concept of chain ID was only added after the dao fork.  Teku is trying to check that you're Eth1 node is connected to the right chain (ie MainNet and not Görli) so is asking for that chain ID and it doesn't match what we expect.

Once Geth has finished syncing the errors will stop.  Note that geth is still syncing as long as it's importing state entries, even if it reports that it has blocks up to near chain head.  Sadly it's not possible to know how much longer a fast sync will take because of the way the protocol works but 1-3 days is normal.

I'm going to close this issue just to keep things tidy.  We're around in the ConsenSys Discord #teku channel as well which is usually a faster way to get answers to questions: https://discord.gg/7hPv2T6

**Comment by cryptoguru2040** [comment]
Thank you for the explanation. I will wait until the full sync is complete.
