### ISSUE TITLE
Upgrade to Tuweni libs 1.4.0 when released 

### ISSUE THREAD

**Issue by Nashatyrev** [Consensys-Incorporated/teku#3419]
Tuweni `1.4.0` release is coming soon and there would be some fixes in `Bytes` library, so it makes sense to upgrade

https://github.com/apache/incubator-tuweni/releases

**Comment by Nashatyrev** [comment]
The following issues fixes are wanted: 
https://github.com/apache/incubator-tuweni/issues/186
https://github.com/apache/incubator-tuweni/issues/168

**Comment by rolfyone** [comment]
I upgraded to 2.0.0 and let CI run, but the performance is quite bad so putting back for now, we'll have to take a closer look some time.

**Comment by ajsutton** [comment]
So it turns out the performance degradation here is because tuweni-crypto's  `Hash` now has support for libSodium.  In theory, using libSodium will give us native hashing which should significantly improve performance. However, tuweni is checking if Sodium is available every single time it performs a hash operation.  For Teku that's a complete disaster.

And when sodium is installed, we appear to immediately get an `OutOfMemoryError` when sodium tries to allocate memory.  Sadly there's no good way to disable libsodium checks in Tuweni at the moment.  Have raised a PR to be able to disable it: https://github.com/apache/incubator-tuweni/pull/347

**Comment by Nashatyrev** [comment]
Fixed by #4912
