### ISSUE TITLE
--initial-state improvements

### ISSUE THREAD

**Issue by tzapu** [Consensys-Incorporated/teku#3488]
I used this amazing feature and it was simply magical to get a teku up to head in less than a minute. congrats.

there could be a couple of things that would make this even more magical
- cache the state in the data dir, once it's downloaded don't download another state
- if there is a an already synced chain, disregard the given intial state or something along those lines

it seems that if you give the state from an url, and the argument is still there after restarting the node, it sometimes (all the times?) crashes, probably because the initial state changes as it's given like `--initial-state=http://teku-beacon-archive:5051/teku/v1/beacon/states/finalized` 

the benefit of adding the initial state argument and leaving it is that you could have a statefulset of tekus that can scale up at a moment's notice

**Comment by ajsutton** [comment]
Thanks for reporting this.  Definitely worth looking into improving the usability here. There are some interactions with checking the weak subjectivity period which adds some security requirements around this (which is why Teku is currently always downloading the state again and exiting if it doesn't match) but I suspect they can be handled in a better way without losing security. Will just require a bit of thought.

**Comment by tzapu** [comment]
my thinking was that if there is an already downloaded state and it was synced from that, ignore it, then the weak subjectivity period wouldn't matter (i think, shot in the dark really) as it wouldn't actually redownload or sync from a new state again, it would continue it's normal sync. sorry if this is all missing the point though

**Comment by ajsutton** [comment]
Yeah you're thinking is pretty much correct - the risk is that if the node has been offline for long enough it's current state on disk may now be outside the weak subjectivity period and so it needs to either wipe the database and start from a recent snapshot or at least specify a weak subjectivity checkpoint so that it can confirm it followed the right chain once it does catch up again.  I think the current way its configured its trying to use the specified snapshot as the checkpoint whereas we need to find a better balance between the usability and weak subjectivity benefits of snapshot sync.

@mbaxter is the expert on this stuff though.

**Comment by mbaxter** [comment]
Currently, if the user sets an `--initial-state` that is ahead of the local chain, we'll exit with an error.  I think it may be a bit risky to assume that this should just be ignored - a user might be trying to fast-forward sync a node that has been offline for a while, for instance.  In that case better to inform the user that their node is misconfigured than to let the node continue to sync from its current chain.  

A few idea on how to improve this:
* We could add an explicit `--lazy-initial-state` param that is only used if the node has no chain data
* We could log a loud warning and interpret a future initial state as a weak subjectivity checkpoint.  So instead of trying to sync from the supplied state, we could just validate that we eventually reach it.  

I think I prefer the first option since it's more explicit and makes it harder to accidentally misconfigure the node.

**Comment by tzapu** [comment]
first option sounds like it would cover our needs well enough, but either would work just fine. sound great!

**Comment by ajsutton** [comment]
I'm really hesitant to have an additional CLI arg as I can see it being very confusing for users. We also want to avoid redownloading the state at every startup so can't even reliably detect it changed and use it as a ws checkpoint.  Which makes life a bit tricky...

Thinking it through, the risk we're trying to mitigate is if a node syncs, then is offline for longer than the weak subjectivity period, then starts up again. It needs to either discard its start and begin from a recent initial-state or have a ws checkpoint specified so it can sync from where it was up to and check it winds up on the right chain.  Being offline for that long is a fairly unusual case so it probably shouldn't be what we optimise for, but we do want to make sure it's secure.

What if we only use `--initial-state` if the database doesn't yet exist (ie first run) and ignore it afterwards.  But if we start up and find that the current state is too old, we treat that the same as starting a sync from genesis - currently that means printing a lot of warnings about being outside the weak subjectivity period and at some point in the future probably means refusing to start unless a ws checkpoint is provided. Possibly if an `initial-state` is being ignored and we're outside the weak subjectivity period we refuse to start now? (could be over complicating things).

`--initial-state` would then be exclusively focussed on shortcutting sync times (with the side benefit of weak subjectivity safety on initial sync) and `--ws-checkpoint` is how you mitigate weak subjectivity problems.

**Comment by tzapu** [comment]
the only thing i am worried about is that if the intial-state flag is set and the node restarts (usually after syncing completely) it fails to start. the rest of the potential issues seem like they would happen rarely and, in my head at least, sound like they should be handled manually.  From that point of view "What if we only use --initial-state if the database doesn't yet exist (ie first run) and ignore it afterwards."  sounds perfect to me
