### ISSUE TITLE
External validator client should retrieve network information from the beacon node config endpoint

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#3530]
### Description
Rather than having to be explicitly told the network to use, the external validator should retrieve the network config from the beacon chain config endpoint.  Shouldn't need to specify `--network` for the external validator client at all.

**Comment by ermyas** [comment]
Hi @ajsutton - I would like to take this issue up if I may. 

I've captured below my current understanding and added a couple of cursory questions.

_Current understanding:_
Currently, when running a remote validator client (typically using the `teku vc ...` subcommand),  a `--network` option needs to be specified. The value provided to this option can either be the name of one of a set of defined networks (_mainnet_, _prater_, etc.), or a path to a configuration file, in the case of a custom network. This information is used to load the relevant network presets and constants that a VC will need. However, because a beacon node already exposes some of this information through its config API (`/eth/v1/config/spec`), a VC can technically fetch these details directly, without requiring the cli option. 

_Details_
From what I gather, when a `--network` option is specified, roughly two things are performed in order to create an `Eth2NetworkConfiguration` instance that encapsulates the network details.  
1. [If a known/defined network is specified, a set of hardcoded default parameters are set](https://github.com/ConsenSys/teku/blob/master/ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java#L251) (e.g. discovery boot nodes, deposit contract deploy block, startup time out) - `Eth2NetworkConfiguration#applyNetworkDefaults`
2. [A spec yaml file corresponding to the name or path specified in `--network` is fetched and loaded](https://github.com/ConsenSys/teku/blob/master/ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java#L160). The spec file contains other relevant parameters not set in step 1

**Question 1:** 
For external validator clients, I assume step 1, would still be required if the remote beacon node is using one of the known networks? If so, there should be a reliable way of obtaining what defined network the beacon node spec is using.  From what I gather the `PRESET_BASE` doesn't quite serve that purpose and `CONFIG_NAME` seems to only be included for legacy reasons, and perhaps can't be relied upon? I feel I might be misunderstanding something here?

**Question 2:**
I assume we also remove the use of other network-related options from the VC subcommand (i.e. remove the `Eth2NetworkOptions` mixin in `ValidatorClientCommand`) such as `--eth1-deposit-contract-address` since they appear to be available through `config/spec`?

**Comment by ajsutton** [comment]
> Hi @ajsutton - I would like to take this issue up if I may.

That would be great. I'm not sure exactly how much refactoring or what trade offs will be involved so I'd encourage you to put up draft PRs early and get feedback. I'm happy to look over it even if it's not completed yet to check that it's heading in the right direction.

> _Current understanding:_
> Currently, when running a remote validator client (typically using the `teku vc ...` subcommand), a `--network` option needs to be specified. The value provided to this option can either be the name of one of a set of defined networks (_mainnet_, _prater_, etc.), or a path to a configuration file, in the case of a custom network. This information is used to load the relevant network presets and constants that a VC will need. However, because a beacon node already exposes some of this information through its config API (`/eth/v1/config/spec`), a VC can technically fetch these details directly, without requiring the cli option.

Yep, exactly.

> _Details_
> From what I gather, when a `--network` option is specified, roughly two things are performed in order to create an `Eth2NetworkConfiguration` instance that encapsulates the network details.
> 
> 1. [If a known/defined network is specified, a set of hardcoded default parameters are set](https://github.com/ConsenSys/teku/blob/master/ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java#L251) (e.g. discovery boot nodes, deposit contract deploy block, startup time out) - `Eth2NetworkConfiguration#applyNetworkDefaults`
> 2. [A spec yaml file corresponding to the name or path specified in `--network` is fetched and loaded](https://github.com/ConsenSys/teku/blob/master/ethereum/networks/src/main/java/tech/pegasys/teku/networks/Eth2NetworkConfiguration.java#L160). The spec file contains other relevant parameters not set in step 1

Yep.

> **Question 1:**
> For external validator clients, I assume step 1, would still be required if the remote beacon node is using one of the known networks? If so, there should be a reliable way of obtaining what defined network the beacon node spec is using. From what I gather the `PRESET_BASE` doesn't quite serve that purpose and `CONFIG_NAME` seems to only be included for legacy reasons, and perhaps can't be relied upon? I feel I might be misunderstanding something here?

All of the additional information from step 1 actually only applies to the beacon node. So when running a separate validator client we can just skip that and just load the content from the network config YAML file (as provided by the `/eth/v1/config/spec` endpoint).


> **Question 2:**
> I assume we also remove the use of other network-related options from the VC subcommand (i.e. remove the `Eth2NetworkOptions` mixin in `ValidatorClientCommand`) such as `--eth1-deposit-contract-address` since they appear to be available through `config/spec`?

We don't want to break backwards compatibility when initially rolling this out.  Longer term we probably will remove the `--network` option from the validator client but for now we'd want to make it optional.  If it's specified we'd use it the same way we do today.  If it's omitted we'd load the config from the beacon chain endpoint.

Additional options like `--eth1-deposit-contract-address` don't actually apply to the validator client itself and ideally wouldn't have been available there at all, but we've had a few options like that leak over unintentionally. So they'll also wind up being removed eventually (but be left there for now for backwards compatibility).

It's probably useful to know that we already load the network config from the beacon node for the `voluntary-exit` subcommand. The code to do that is https://github.com/ConsenSys/teku/blob/029f24890cdf0b6e90092372f78f3ab4b8de7638/teku/src/main/java/tech/pegasys/teku/cli/subcommand/VoluntaryExitCommand.java#L182 

We also need to be a bit careful in making this change because we only want it to apply when running the validator client in a separate process.  When it runs in the same process as the beacon node (the default node) it doesn't make sense for it to try and load the spec config via the REST API and should just use the same `Spec` instance as the beacon node component does.

**Comment by ermyas** [comment]
great, thanks @ajsutton. This confirms most of my thinking.

**Comment by ermyas** [comment]
> We don't want to break backwards compatibility when initially rolling this out. Longer term we probably will remove the --network option from the validator client but for now we'd want to make it optional. If it's specified we'd use it the same way we do today. If it's omitted we'd load the config from the beacon chain endpoint.

The issue here might be that the --network option is already optional, and defaults to  "mainnet", when not specified. This means that users already have an expectation of how this option behaves even when they are not using it explicitly. I don't imagine we want to break this expectation right away either, and deprecating the default behavior (or implicit usage) of something generally feels a bit trickier (i.e. eventually removing --network might not be something such users notice)

A couple of things to consider that might inform/constrain our options here:
- is our desired end-state that fetching the network spec from the beacon node is the only option (i.e. a user can't override this), or that we continue to support a way for the user to manually specify a network or custom spec file if they choose? 
  
- in the short term, fetching the network spec from the beacon node API will have to be something a user explicitly enables (since not specifying anything already uses "mainnet"). How should we do this? This is of course influenced by the question above. Some of the concerns are, of course, whatever we use (a new boolean flag, augmenting the --network option, etc.) will have to a) eventually transition to an option that is implicitly enabled by default b) potentially become deprecated, and require phasing out if it isn't something one can disable in the end-state (question above)

**Comment by ajsutton** [comment]
> The issue here might be that the --network option is already optional, and defaults to "mainnet", when not specified. This means that users already have an expectation of how this option behaves even when they are not using it explicitly. I don't imagine we want to break this expectation right away either, and deprecating the default behavior (or implicit usage) of something generally feels a bit trickier (i.e. eventually removing --network might not be something such users notice)

Good point.  I was thinking backward compatibility in terms of not failing to start if you have `--network` specified (because if it's removed it becomes an invalid option).  Changing behaviour unexpectedly is probably not ideal though.

The saving grace here is that if you have a beacon node on prater and a validator client on mainnet, it's not going to work anyway.  So while we probably want to provide some notice about the upcoming change, ultimately when we do switch over, the behaviour should either be unchanged or go from not working to working.


> * is our desired end-state that fetching the network spec from the beacon node is the only option (i.e. a user can't override this), or that we continue to support a way for the user to manually specify a network or custom spec file if they choose?

Yes, I think ultimately this is where we want to get to.

> * in the short term, fetching the network spec from the beacon node API will have to be something a user explicitly enables (since not specifying anything already uses "mainnet"). How should we do this? This is of course influenced by the question above. Some of the concerns are, of course, whatever we use (a new boolean flag, augmenting the --network option, etc.) will have to a) eventually transition to an option that is implicitly enabled by default b) potentially become deprecated, and require phasing out if it isn't something one can disable in the end-state (question above)

I'd suggest that we do this in three steps.

1. Support `--network auto` which means load the config from the beacon node.  Default would remain `--network mainnet`. This then acts as a really handy feature toggle so people can test out the new approach without it being the default and applying to everyone all at once
2. Switch the default to `--network auto`.  Probably at this point we'd also hide the `--network` option, update docs etc so new users just expect it to get the config automatically, but teku still starts for users who have the `--network` option. We'd add removal of `--network` to the list of upcoming breaking changes in the changelog.
3. Probably after a fair bit of time, we'd fully remove the `--network` option.

**Comment by ermyas** [comment]
Sorry for the delayed response @ajsutton. This sounds like a sensible approach. I've pushed a draft PR #4324, for feedback.
