### ISSUE TITLE
archive teku missing blocks

### ISSUE THREAD

**Issue by tzapu** [Consensys-Incorporated/teku#3605]
### Description
a teku synced with `--data-storage-mode=archive` from scratch is returning 404 for all slots between 498464 and 498527
teku seems to have restarted when it was syncing some blocks surrounding this interval, i was able to extract this from the logs

```
2/6/2021, 12:52:33.660 AM | 00:52:33.660 INFO - [37mSync Event *** Current slot: 572662, Head slot: 498528, Connected peers: 59[0m 
...
2/6/2021, 12:52:59.529 AM | 00:52:59.527 INFO - Teku version: teku/v20.12.1/linux-x86_64/oracle_openjdk-java-14 
```

### Versions (Add all that apply)
* Software version: 20.12.1
* Cloud VM, type, size: Azure AKS

**Comment by ajsutton** [comment]
I could imagine that https://github.com/ConsenSys/teku/pull/3507 which hasn't yet made it into a release may help.  Without that change we weren't actually waiting for the database to shutdown cleanly, but we still shouldn't lose blocks even if there's a non-clean shutdown.

The transaction to record finalized blocks is committed prior to even starting the transaction to prune them from the hot database so not sure how this would happen other than RocksDB losing the finalized transaction entirely but managing to keep the later hot db prune transaction.

**Comment by ajsutton** [comment]
The only thing I can see that could happen here is that the archive database lost a transaction which had been committed and the hot database managed to keep its transaction even though it occurred entirely after the first commit.  That's pretty unexpected but not impossible.

It does strongly suggest that with the move we're likely to do to leveldb we should use the combined database so archive and hot data is in a single database and this problem is avoided.  Unfortunately RocksDB's memory usage explodes when we try to use a combined db with it so a fix will be dependent on moving to leveldb.

Going to close this out as I don't believe there's anything more we can do on it and leveldb migration has its own stream of tickets.

**Comment by ajsutton** [comment]
Going to reopen this as I suspect #3791 is another instance of it.  I still think we need to move to leveldb to solve it properly unfortunately but worth making it easier to find if its more than a once off.

**Comment by ajsutton** [comment]
Closing this one again as new databases now use the combined leveldb2 format which avoids this issue.
