### ISSUE TITLE
validator metrics request

### ISSUE THREAD

**Issue by tzapu** [Consensys-Incorporated/teku#3610]
some of these might already exist and i missed them, so please point me in the right direction if so.
i could do with having:
current epoch as seen by the validator
attestations requested count for current epoch (total, not pending)
failed attestations for the current epoch or failed total attestations and i can overlay them
block proposals requested for the current epoch (total, not pending)
failed block proposals for the current epoch or total
failed signer requests, maybe broken down by timeout or errors
failed beacon node requests/disconnects

i ll keep adding what crosses my mind. 
thank you very very much :D

**Comment by jmcruz1983** [comment]
Any update in this front?
In the meantime, another option to pull some validator metrics?

**Comment by rolfyone** [comment]
Digging into the details currently.

`beacon_node_published_attestation_total` - total count of signed attestations submitted
`beacon_node_published_aggregate_total` - total count of signed aggregations submitted
`beacon_node_published_block_total` - total count of signed blocks submitted

My question is whether these are adequate to use instead of the per-epoch metrics which would go up and down all the time...

 - I've mostly added the current epoch counter, so that's relatively simple i think - basically the onSlot event calculates epoch based on the slot, and I can store the epoch at that point.

Create a labelled counter with 2 labels - dutyType (attestation, block, aggregate), and result(success, failure)

Create a counter to store the successes / failures / timeouts of external signer requests (total)

Create a counter on http request failures, and on eventStream disconnects

**Comment by jmcruz1983** [comment]
Thanks @rolfyone for your reply.

We aware and already use `beacon_node_published_attestation_total`, `beacon_node_published_aggregate_total` & `beacon_node_published_block_total` metrics. 

But in addition we would like to have an insight per validator in a given epoch.

**Comment by jmcruz1983** [comment]
Different question @rolfyone 

Is there a way to know activated keys in each validator? can we get it via metrics?

**Comment by rolfyone** [comment]
keys loaded by a validator are output to screen and log file at startup, with short hashes printed... is that what you're looking for?

**Comment by jmcruz1983** [comment]
> keys loaded by a validator are output to screen and log file at startup, with short hashes printed... is that what you're looking for?

No, at the startup shows the number of loaded keys, but I would like to know, if possible, which of these keys are actually activated/used.
Thanks @rolfyone

**Comment by rolfyone** [comment]
It's possible to add a count of specific statuses, at the moment less easy to do because of how gauges work, so still considering that.
Regarding the status of specific sets of validators, there's also an api: `/eth/v1/beacon/states/{state_id}/validators` which allows an array of validator indexes or keys... I think that's how most people tend to check the status of specific keys...
I'll keep adding the non 'labelled gauge' metrics initially, as they can be done without updating the library we're using, where as the labelled gauge concept is something that would require a bit of lower level work before they're going to be very practical.

**Comment by rolfyone** [comment]
raised #3795, #3796 to capture elements that we don't have easy facilities to create currently.
 - per-epoch production metrics
 - validator status gauges

the rest of the requested metrics should be in, and fairly helpful so I'll move this ticket to review.

**Comment by rolfyone** [comment]
the main 2 things to consider are the other raised tickets, putting this to backlog.

**Comment by benjaminion** [comment]
Closing as stale. Please open new issues for anything that remains important.

**Comment by tzapu** [comment]
hi @benjaminion 👋  a lot of stuff has been added since so makes sense to close this. 
this could do with an updating though https://github.com/ConsenSys/teku/blob/master/dashboard/teku-dashboard-grafana.json or removing and adding a link to a published grafana dash, 
i had a bit of a hard time finding a dash that was up to date and worked, i think i m using both yours and @ajsutton s ones that were published on grafana dahsboards but would love to know there is an official one that keeps getting updated and has all the stuff you add, without having to hunt for the new metrics myself (as you might remember, i am lazy)

thank you and the team for the amazing job you have done, teku works brilliantly 

/edit found this in the docs, looks updated, can t remember what didn t work last time i used it 
https://grafana.com/grafana/dashboards/13457-teku/

/edit2 for other stats scavangers, the other good dashboard is this https://grafana.com/grafana/dashboards/12522-teku-overview/

**Comment by ajsutton** [comment]
@tzapu I've published my "playground" dashboard which has a whole heap of different metrics - not all of them make sense, some likely require some hidden/unsupported options etc but should provide some good examples of useful metrics.

https://grafana.com/grafana/dashboards/16737-teku-detailed/

**Comment by tzapu** [comment]
amazing, thanks @ajsutton 🙇
