### ISSUE TITLE
Investigate attestation performance discrepancy

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#3726]
### Description
We have a user reporting an instance of the following attestation performance report:
```
"08:48:07.332 INFO - Attestation performance: expected 677, produced 691, included 691 (100%), distance 1 / 1.10 / 2, correct target 691 (100%), correct head 691 (100%)"
```

The expected attestation count (677) is less than the actual count of produced attestations (691).  Suspect that our [`ActiveValidatorTracker`](https://github.com/ConsenSys/teku/blob/0a73c860f8a28dbc7870538950235e76e36062ef/validator/coordinator/src/main/java/tech/pegasys/teku/validator/coordinator/performance/DefaultPerformanceTracker.java#L252) is getting skewed somehow ...

Teku Version: `21.2.0`

**Comment by ajsutton** [comment]
This was caused by the validator client getting signing timeouts while attempting to check if it was the aggregator.  As a result, it then didn't subscribe to committees for those validators and it's those subscriptions that tell the beacon chain how many validators it has running against it.  So the expected number of attestations was incorrect leading to the odd looking stats.
