### ISSUE TITLE
The voluntary exit command should check the pending exit queue to give more information

### ISSUE THREAD

**Issue by remyroy** [Consensys-Incorporated/teku#3951]
### Description
As an user of the `voluntary-exit` command, I want to get more information regarding my exit status so that I don't have to query any API or any website to get that information.

### Steps to Reproduce (Feature)
1. Execute the `voluntary-exit` command
2. Notice that you are not informed of when you are expected to actually exit or how long it will take

**Expected behavior:**
The `voluntary-exit` command should query the beacon node about the exit status of your validator(s) and give you more information regarding that exit. It should tell you how long you should expect to wait before your validator(s) are exited. It should tell you the exact exit epoch and withdrawable epoch.

**Actual behavior:**
It seems like the only information you get is the epoch at which the voluntary exit was published.

**Frequency:**
Everytime someone uses the `voluntary-exit` command

### Versions
* Software version: teku/v21.4.1/windows-x86_64/adoptopenjdk-java-11
* Java version: openjdk 11.0.11 2021-04-20 - OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) - OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
* OS Name & Version: Windows 10

**Comment by remyroy** [comment]
Here was my logs when I ran that command:
```
C:\Users\Hidden>c:\ethereum\bin\teku\bin\teku.bat voluntary-exit --beacon-node-api-endpoint=http://127.0.0.1:5051 --validator-keys=c:\ethereum\var\lib\eth2\keys;c:\ethereum\var\lib\eth2\keys
Loading configuration...
Exits are going to be generated for validators:
a27a2de
Epoch: 10168

These validators won't be able to be re-activated, and withdrawals aren't likely to be possible until Phase 2 of eth2 Mainnet.
Are you sure you wish to continue (yes/no)?
yes
Exit for validator a27a2de submitted.
```

**Comment by rolfyone** [comment]
Thanks for raising this, we'll add it to our backlog.

The information you've suggested will require that we wait for the exit to be included in a block, so there's some details that we will need to work though, but it does sound like a useful feature to implement.

You'll likely run this command then it'll sit and poll and wait for the exit to be registered so that it can display the pertinent information, and we'd potentially have some kind of flag to disable the polling if you just want the exit sent (for scripting use).
