### ISSUE TITLE
Build for tag 21.5.0 fails on clean checkout

### ISSUE THREAD

**Issue by tdiesler** [Consensys-Incorporated/teku#3988]
### Description

The build for the latest tag fails on RaspberryPi

```
> Task :teku:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
> Task :checkMavenCoordinateCollisions FAILED
FAILURE: Build failed with an exception.
* Where:
Build file '/home/pi/git/teku/build.gradle' line: 261
* What went wrong:
Execution failed for task ':checkMavenCoordinateCollisions'.
> Basedir /home/pi/git/teku/http does not exist
```

Is `teku/http` supposed to be there?

### Versions (Add all that apply)
* Software version: 21.5.0
* Java version: openjdk 11.0.11 2021-04-20
* OS Name & Version: Debian10

**Comment by ajsutton** [comment]
What was the exact command you ran? 

There shouldn't be a teku/http directory so I'm not exactly sure why its looking for it.

**Comment by tdiesler** [comment]
Same failure shows on MacOS

```
$ git log --oneline
7f8105062 (HEAD, tag: 21.5.0) Add cli option to override the altair fork block and enable it (#3961)
...

$ ./gradlew clean build
...
> Task :checkMavenCoordinateCollisions FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '.../teku/build.gradle' line: 261

* What went wrong:
Execution failed for task ':checkMavenCoordinateCollisions'.
> Basedir .../teku/http does not exist

```

**Comment by benjaminion** [comment]
I can reproduce this on Linux from a fresh clone:

```
tmp> git clone https://github.com/ConsenSys/teku.git
tmp> cd teku
teku> ./gradlew build
> Task :checkMavenCoordinateCollisions FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/teku/build.gradle' line: 261

* What went wrong:
Execution failed for task ':checkMavenCoordinateCollisions'.
> Basedir /tmp/teku/http does not exist
```

The following workaround, however, succeeds: manually creating the `http` directory before building.
```
tmp> git clone https://github.com/ConsenSys/teku.git
tmp> cd teku
teku> mkdir http
teku> ./gradlew build
...
BUILD SUCCESSFUL in 4m 45s
504 actionable tasks: 504 executed
```

I'll leave it to greater minds than mine to work out why.

Note that, after building, the `http` directory contains only a `build` directory (which has stuff in it), but this is ignored by git due to the `.gitignore` rules. Thus, git thinks `http` is empty and therefore does not include it in the archive. Old installations with a pre-existing `http` directory will work, and git doesn't know the difference.

```
teku> ls -l http
total 0
drwxrwxr-x 5 ben ben 100 May 15 11:21 build
teku> git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by tdiesler** [comment]
Merci, I can work with that

**Comment by ajsutton** [comment]
Ah that's a fun one.  So it turns out there was still a reference to a `http` module in the gradle config which didn't exist.  If you ran `spotlessCheck` or `spotlessApply` the directory would be created and everything works, but if the `checkMavenCoordinateCollisions` task ran before that directory got created it would fail. Both tasks run as part of the default build but the order isn't guaranteed.

So creating the directory is the right work around for 21.5.0 and #3991 will fix it for the next release.

Thanks for reporting this and sorry for the inconvenience.

**Comment by tdiesler** [comment]
UR welcome
