### ISSUE TITLE
Eth1 head at follow distance is a function of block height

### ISSUE THREAD

**Issue by mkalinin** [Consensys-Incorporated/teku#4005]
### Description

The spec states that candidate Eth1 blocks must be filtered this way:
```py
def is_candidate_block(block: Eth1Block, period_start: uint64) -> bool:
    return (
        block.timestamp + SECONDS_PER_ETH1_BLOCK * ETH1_FOLLOW_DISTANCE <= period_start
        and block.timestamp + SECONDS_PER_ETH1_BLOCK * ETH1_FOLLOW_DISTANCE * 2 >= period_start
    )
```

Effectively Teku processes candidate blocks in two steps:
- cache Eth1 blocks that satisfy following conditions `block.timestamp >= eth1_head_block.timestamp - cacheDuration` && `block.number <= eth1_head_block.number - ETH1_FOLLOW_DISTANCE`
- apply `is_candidate_block` filter to cached blocks

If seconds per block in Eth1 network is _greater_ than `SECONDS_PER_ETH1_BLOCK` Teku may effectively stem from `is_candidate_block` conditions stated by the spec to the following:
```py
def is_candidate_block(block: Eth1Block, period_start: uint64) -> bool:
    return (
        block.number + ETH1_FOLLOW_DISTANCE <= eth1_head_block.number
        and block.timestamp + SECONDS_PER_ETH1_BLOCK * ETH1_FOLLOW_DISTANCE * 2 >= period_start
    )
```

The source of this bug is in the logic of head tracker that notifies about new Eth1 block at follow distance using block height instead of timestamp:
https://github.com/ConsenSys/teku/blob/8df7ae14c1a9d4ebe633b3d835200576a00c9f91/pow/src/main/java/tech/pegasys/teku/pow/Eth1HeadTracker.java#L81

### Effect

Say real time per block is `15s` on average while `SECONDS_PER_ETH1_BLOCK = 14`. It would result in about `136` blocks not included in cache at the start of new voting period. Since, they are not in the cache they won't be considered as eth1 vote candidates.

The place this issue was originally discovered is [Nocturne](http://github.com/protolambda/nocturne) devnet, a testnet with deployed Merge code. Nocturne has empty slots which increase time between blocks and makes this issue occur. In other words, fixing this issue is important for the Merge.

**Comment by ajsutton** [comment]
You know I could have sworn the spec always followed 2048 blocks behind head, not just time based but have reviewed it and agree with your analysis. Won't be a quick fix unfortunately since you can't blocks by timestamp so we'll have to change our approach to tracking the head.

**Comment by mkalinin** [comment]
> You know I could have sworn the spec always followed 2048 blocks behind head, not just time based but have reviewed it and agree with your analysis. Won't be a quick fix unfortunately since you can't blocks by timestamp so we'll have to change our approach to tracking the head.

Spec used block height from the very beginning and then switched to timestamp based approach -- it might be a source of confusion.

I totally agree, there is no easy fix to that. Since there is no way to query blocks by timestamp a straightforward fix would require traversing blocks starting at `ETH1_FOLLOW_DISTANCE` and picking the last block that satisfies eth1 voting conditions. This is suboptimal and we might want to cache adjusted follow distance if block time has been increased in order to reduce traversal complexity; but when time between blocks starts sliding back towards `SECONDS_PER_ETH1_BLOCK` this cached follow distance should be re-adjusted.

**Comment by ajsutton** [comment]
Given we have to walk through every block in the cache period anyway to populate the cache, I think as long we don't entirely overshoot the period we need to cache we can wind up making the same number of requests without being too fancy.

Basically I'm thinking we request the block that's `ETH1_FOLLOW_DISTANCE` behind the current head.  My assumption is that that block will a) not be before the start of the period we need to cache (block time would have to be out by a factor of 2 I think) and b) we're not going to get any forks at that distance even if it turns out to be more recent than we need.

Then we just walk backwards from there to the start of the period we need to cache as we currently do, and also walk forward until we get the first block that's more recent than `ETH1_FOLLOW_DISTANCE * SECONDS_PER_ETH1_BLOCK`. When time progresses enough that the last block is now within the period we should cache, we request the next block after it, ensuring that we always wind up holding one block that's more recent than the period we need.  That actually lets us stop polling the head block as well so should wind up significantly reducing the number of requests we need to make to the eth1 node.

**Comment by ajsutton** [comment]
I'm thinking with that approach even if `ETH1_FOLLOW_DISTANCE` winds up being more recent than we actually want, we just wind up caching more than we need initially and will gradually prune the cache down over time since we won't request any new blocks until the most recent one we have is within the cache period.
