### ISSUE TITLE
Incorrect BLS key validation

### ISSUE THREAD

**Issue by dnkolegov** [Consensys-Incorporated/teku#4025]
### Description
Public key validation must check group membership and that the key is not the point at infinity.
At the same time:
- BLST-backed implementation [checks](https://github.com/ConsenSys/teku/blob/master/bls/src/main/java/tech/pegasys/teku/bls/impl/blst/BlstPublicKey.java#L84) group membership only
- MIKULI-backed implementation [doesn't validate](https://github.com/ConsenSys/teku/blob/master/bls/src/main/java/tech/pegasys/teku/bls/impl/mikuli/MikuliPublicKey.java#L106) the key at all

### Acceptance Criteria
* All algorithms that operate on public keys require first validating those keys
* It should include group membership and infinity checks, as per https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-04#section-2.5.

**Comment by benjaminion** [comment]
Thank you for raising this.

The Mikuli implementation performs the [group membership](https://github.com/ConsenSys/teku/blob/master/bls/src/main/java/tech/pegasys/teku/bls/impl/mikuli/G1Point.java#L88) and [infinity](https://github.com/ConsenSys/teku/blob/master/bls/src/main/java/tech/pegasys/teku/bls/impl/mikuli/G1Point.java#L84) checks on deserialisation of the public key. This is fine within the context of the Teku client, as all potentially hostile public keys are received in serialised form. The Mikuli approach differs from the current Blst implementation, which used to rely on checking group membership at deserialisation but no longer does, due to a change in the Blst library.

We have been looking at modifying this to make the group membership checks consistent across implementations and cache the results, which would make this more obvious.

**Comment by dnkolegov** [comment]
Thanks for the response.

What about this BLST [check](https://github.com/ConsenSys/teku/blob/master/bls/src/main/java/tech/pegasys/teku/bls/impl/blst/BlstPublicKey.java#L84)?
You didn't mention that.

**Comment by benjaminion** [comment]
To summarise everything:

### Mikuli

Group membership and infinity test are always performed during deserialisation, so we can't have an invalid key in the system. These tests are _not_ repeated when the public keys are used (aggregation or verification). The same is true for G2 signature points.

### Blst

Group membership tests are _not_ performed during deserialisation (with an exception for the special case  [0, +/-2]) during normal control flow. These checks are performed in the Blst library when the public keys are used (aggregation or verification). The same is true for signatures.

The `BlstPublicKey.forceValidation()` method you highlight is not actually used in most cases. It allows for group membership to be checked during deserialisation when desired, outside the normal control flow (e.g. while reading validator key files locally or dealing with slashing protection files). It's a no-op for Mikuli since group membership is always checked during deserialisation.

### Future

At some point soon we plan to make these two approaches consistent, and cache group membership so that we can be sure that the test is only ever done once per public key, and only for public keys that actually get used.

**Comment by dnkolegov** [comment]
Thank you.

It should be noted that BLST developers suggest that "The expectation is the application will deserialize/uncompress an object and call KeyValidate if that object is a previously unvalidated public key. The deserialize interface is agnostic to the
higher level object type." Source: [link](https://research.nccgroup.com/wp-content/uploads/2021/01/NCC_Group_EthereumFoundation_ETHF002_Report_2021-01-20_v1.0.pdf), page 37.

**Comment by benjaminion** [comment]
Noted. However the `KeyValidate` method is not available in the Java (or C) bindings of _blst_.

Instead, the Java bindings apply the group check explicitly at the points where public keys are used. For example [here](https://github.com/supranational/blst/blob/master/bindings/blst.hpp#L163).

Blst's handling of the point at infinity has changed over time, so we test for it explicitly in the application for consistency. For example [here](https://github.com/ConsenSys/teku/blob/master/bls/src/main/java/tech/pegasys/teku/bls/impl/blst/BlstSignature.java#L123).

As mentioned, we are planning to make things more consistent across the two implementations at some point.

**Comment by benjaminion** [comment]
Closing for now as I believe that Teku is correctly checking for the point at infinity and for group membership, even if not in the most obvious or optimal way.
