### ISSUE TITLE
Consider using stronger randomness in BLS batch verification

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#4136]
I don't believe we genuinely need high quality randomness for performing batch verification. Any potential attacker is severely constrained in what they can attempt here, even if they can gain some knowledge of the RNG output. Nonetheless, a couple of people have raised this recently, and for the sake of a quiet life it may be worth improving the randomness.

We should validate whether the comment about `SecureRandom` still applies. If the performance impact is negligible, we should move over to using `SecureRandom`.

https://github.com/ConsenSys/teku/blob/d0bd4d06848fe62fc1ae5088e37b4dd62d949e33/bls/src/main/java/tech/pegasys/teku/bls/impl/blst/BlstBLS12381.java#L40-L48

**Comment by ajsutton** [comment]
`SecureRandom` can definitely block on lack of entropy even on the most recent JDKs but that is because it reads from `/dev/random` when creating its initial seed.  But as long as we are reusing a single instance of `SecureRandom` it shouldn't block and fortunately `SecureRandom` is thread safe, unlike the plain `Random`.
