### ISSUE TITLE
Look at using Blst's SHA256 implementation [1D]

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#4190]
Blst has a [SHA256 implementation](https://github.com/supranational/blst/blob/master/src/sha256.h) that is likely faster than whatever we are currently using. We should at least benchmark this.

Challenge is that the interface seems to be not exposed, neither through the _blst.h_ and _blst_aux.h_ header files, nor via the Java bindings, so we might need to patch these.

Another advantage of doing this is that, if the [optimisations here](https://hackmd.io/@potuz/rJX9iD30u) were to get ported into Blst, then we would benefit automatically.

**Comment by ajsutton** [comment]
A simpler alternative to getting a native sha256 implementation may be Amazon Corretto Crypto Provider: https://github.com/corretto/amazon-corretto-crypto-provider
It only provides Linux/amd bindings currently (Linux/aarch is experimental currently) but that's a lot of bang for our buck and can easily fall back to BouncyCastle.  Since it uses the JCA/JCE system it automatically gets picked up by everything doing hashing so we don't need to make code changes.

**Comment by benjaminion** [comment]
The main rationale for looking at our SHA256 is that Eth2 uses it for the most part in a very specific way that is amenable to a significant optimisation. No generic SHA256 is likely to implement that optimisation. _If_ Blst were to add it (in view of its ties to Eth2) then it would be well worth having. I haven't heard of any plans for this, though.

Otherwise, I don't actually know that Bouncy Castle's SHA256 is any worse than other implementations. Given our rather narrow use, general benchmarks are unlikely to be helpful.

But Coretto looks nice!

**Comment by jtraglia** [comment]
@benjaminion So I decided to look into this today.

### TDLR:

The BLST SHA256 implementation:

* is 3 times **slower** than built-in with 32-byte data sizes
* is 192 times **faster** than built-in with 1,048,576 (1MB) data sizes
* if data size <= 128, it's slower; if data size >= 256, it's faster

#### Benchmark results

```
Benchmark                                    (dataSize)   Mode  Cnt        Score        Error  Units
SingleValueHashBenchmark.measureSha256               32  thrpt    3  3033237.252 ±  26004.369  ops/s
SingleValueHashBenchmark.measureSha256               64  thrpt    3  1789691.474 ±  45666.534  ops/s
SingleValueHashBenchmark.measureSha256              128  thrpt    3  1241169.080 ±  63174.973  ops/s
SingleValueHashBenchmark.measureSha256              256  thrpt    3   785981.271 ±  10837.448  ops/s
SingleValueHashBenchmark.measureSha256             1024  thrpt    3   240934.276 ±    937.748  ops/s
SingleValueHashBenchmark.measureSha256            32768  thrpt    3     8106.790 ±    157.852  ops/s
SingleValueHashBenchmark.measureSha256           262144  thrpt    3     1013.562 ±     16.523  ops/s
SingleValueHashBenchmark.measureSha256          1048576  thrpt    3      253.545 ±      3.804  ops/s
SingleValueHashBenchmark.measureSha256blst           32  thrpt    3   973814.472 ±  32509.016  ops/s
SingleValueHashBenchmark.measureSha256blst           64  thrpt    3   977989.666 ±  52005.340  ops/s
SingleValueHashBenchmark.measureSha256blst          128  thrpt    3   978521.077 ±  37397.219  ops/s
SingleValueHashBenchmark.measureSha256blst          256  thrpt    3   977670.441 ±  57773.634  ops/s
SingleValueHashBenchmark.measureSha256blst         1024  thrpt    3   945049.183 ±  65419.716  ops/s
SingleValueHashBenchmark.measureSha256blst        32768  thrpt    3   566455.052 ± 117182.064  ops/s
SingleValueHashBenchmark.measureSha256blst       262144  thrpt    3   180337.905 ±  31888.006  ops/s
SingleValueHashBenchmark.measureSha256blst      1048576  thrpt    3    48753.614 ±  81030.990  ops/s
SingleValueHashBenchmark.measureSha256guava          32  thrpt    3  3382911.798 ±  86285.734  ops/s
SingleValueHashBenchmark.measureSha256guava          64  thrpt    3  1838135.256 ±  33819.813  ops/s
SingleValueHashBenchmark.measureSha256guava         128  thrpt    3  1262388.745 ±  49430.821  ops/s
SingleValueHashBenchmark.measureSha256guava         256  thrpt    3   780528.164 ±  14990.448  ops/s
SingleValueHashBenchmark.measureSha256guava        1024  thrpt    3   238564.751 ±   5135.214  ops/s
SingleValueHashBenchmark.measureSha256guava       32768  thrpt    3     8106.865 ±     92.811  ops/s
SingleValueHashBenchmark.measureSha256guava      262144  thrpt    3     1015.304 ±      1.139  ops/s
SingleValueHashBenchmark.measureSha256guava     1048576  thrpt    3      253.451 ±      1.075  ops/s
```

### Conclusion

The BLST SHA256 implementation is definitely faster, but the JNI overhead (and/or the quirks of my implementation) prevents this from being suitable replacement for smaller blobs of data (32-byte) like we really want. This could still be useful in other ways, for example if we can batch queries into one JNI call, I believe this could provide a big performance boost. Another idea, we could split the `Hash.sha256` method into multiple functions based on usage; for small data use built-in implementation, for larger data use the BLST implementation. This would give us the best of both worlds.

I also decided to throw [Google's Guava Hashing](https://guava.dev/releases/23.0/api/docs/com/google/common/hash/Hashing.html) into the mix since, for me, it's faster than the built-in SUN security provider. In my experience, with 32-byte data it's 11.5% faster than the current provider. I think we should consider using it.

### Technical details

#### System

This was tested on my ARM64 (aarch64) Mac running macOS. I used the optimized BLST library.

#### Changes to blst

https://github.com/supranational/blst/compare/master...jtraglia:expose-sha256

To test this out, I needed to expose the SHA256 methods. For the record, I ran into an issue with the `finalize` method, regarding having bytes as the digest type. I ended up making it an array of ints and converting that to an array of bytes afterwards; the overhead is pretty minimal but things could be slightly more efficient.

#### Changes to teku

https://github.com/ConsenSys/teku/compare/master...jtraglia:hashing

For teku, I needed to build a development version of [jblst](https://github.com/ConsenSys/jblst) with the new hash class included. Then I added some new benchmarking functions to test it out.

**Comment by jtraglia** [comment]
@benjaminion So I decided to look into this today.

Edit: I've since learned that Linux is much faster than macOS at SHA256 hashing. See new comments below for details. Knowing what I know now, I don't think that BLST (nor ACCP) are worth the trouble. We should investigate why things are so slow on macOS though. Not many people run Teku on macOS, so low priority. I like it as development environment.

This was tested on my ARM64 (AArch64) Mac running macOS. Using JDK 11 and the optimized BLST library.

```
Benchmark                                    (dataSize)   Mode  Cnt        Score        Error  Units
SingleValueHashBenchmark.measureSha256               32  thrpt    3  3072185.439 ± 125575.302  ops/s
SingleValueHashBenchmark.measureSha256               64  thrpt    3  1762289.977 ±  13357.958  ops/s
SingleValueHashBenchmark.measureSha256              128  thrpt    3  1243538.785 ±  27733.394  ops/s
SingleValueHashBenchmark.measureSha256              256  thrpt    3   758764.379 ±  12528.512  ops/s
SingleValueHashBenchmark.measureSha256             1024  thrpt    3   237290.577 ±   9508.714  ops/s
SingleValueHashBenchmark.measureSha256            32768  thrpt    3     8095.997 ±    285.517  ops/s
SingleValueHashBenchmark.measureSha256           262144  thrpt    3     1001.875 ±     79.229  ops/s
SingleValueHashBenchmark.measureSha256          1048576  thrpt    3      248.876 ±     10.270  ops/s
SingleValueHashBenchmark.measureSha256blst           32  thrpt    3   947792.883 ±  72989.974  ops/s
SingleValueHashBenchmark.measureSha256blst           64  thrpt    3   940477.996 ±  43586.516  ops/s
SingleValueHashBenchmark.measureSha256blst          128  thrpt    3   921503.175 ± 199069.958  ops/s
SingleValueHashBenchmark.measureSha256blst          256  thrpt    3   883873.655 ±  12551.889  ops/s
SingleValueHashBenchmark.measureSha256blst         1024  thrpt    3   679195.083 ±  96800.345  ops/s
SingleValueHashBenchmark.measureSha256blst        32768  thrpt    3    67524.886 ±   4307.435  ops/s
SingleValueHashBenchmark.measureSha256blst       262144  thrpt    3     8925.803 ±    139.249  ops/s
SingleValueHashBenchmark.measureSha256blst      1048576  thrpt    3     2247.055 ±     19.613  ops/s
SingleValueHashBenchmark.measureSha256guava          32  thrpt    3  3331828.262 ± 104019.496  ops/s
SingleValueHashBenchmark.measureSha256guava          64  thrpt    3  1820458.815 ±  26575.189  ops/s
SingleValueHashBenchmark.measureSha256guava         128  thrpt    3  1260498.710 ±  34991.967  ops/s
SingleValueHashBenchmark.measureSha256guava         256  thrpt    3   775529.063 ±  18170.187  ops/s
SingleValueHashBenchmark.measureSha256guava        1024  thrpt    3   236643.173 ±  12102.662  ops/s
SingleValueHashBenchmark.measureSha256guava       32768  thrpt    3     8031.858 ±    444.905  ops/s
SingleValueHashBenchmark.measureSha256guava      262144  thrpt    3     1005.928 ±     52.178  ops/s
SingleValueHashBenchmark.measureSha256guava     1048576  thrpt    3      252.111 ±     18.567  ops/s
```

My takeaways from this:

* BLST is 3 times slower than the SUN provider with 32-byte data sizes.
* BLST is 9 times faster than SUN with 1,048,576 (1MB) data sizes.
* If data size <= 128, BLST is slower than SUN.
* If data size >= 256, BLST is faster than SUN.
* Hashing 32 bytes, Guava is about 10% faster than SUN.

The BLST SHA256 implementation is definitely faster, but the JNI overhead (and/or the quirks of my implementation) prevents this from being suitable replacement for smaller blobs of data (32-byte) like we really want. This could still be useful in other ways, for example if we can batch queries into one JNI call, I believe this could provide a big performance boost. Another idea, we could split the `Hash.sha256` method into multiple functions based on usage; for small data use built-in implementation, for larger data use the BLST implementation. This would give us the best of both worlds.

I also decided to throw [Google's Guava Hashing](https://guava.dev/releases/23.0/api/docs/com/google/common/hash/Hashing.html) into the mix since, for me, it's faster than the built-in SUN security provider. In my experience, with 32-byte data it's 8-12% faster than the current provider. I think we should consider using it. I will look into Amazon Corretto another day. ARM64 support is still experimental which makes things more difficult for me to test.

Changes to BLST: https://github.com/supranational/blst/compare/master...jtraglia:expose-sha256

To test this out, I needed to expose the SHA256 methods. For the record, I ran into an issue with the `finalize` method, regarding having bytes as the digest type. I ended up making it an array of ints and converting that to an array of bytes afterwards; the overhead is pretty minimal but things could be slightly more efficient.

Changes to Teku: https://github.com/ConsenSys/teku/compare/master...jtraglia:hashing

For teku, I needed to build a development version of [jblst](https://github.com/ConsenSys/jblst) with the new hash class included. Then I added some new benchmarking functions to test it out.

**Comment by jtraglia** [comment]
Tested Amazon Corretto Crypto Provider (ACCP) too. It would have been really easy to setup if they had ARM64 builds. I ran into building issues on my desktop running macOS, so I did my testing on my M1 MacBook Air with Asahi Linux. To my surprise, hashing is a lot faster on it than my desktop running macOS. I've heard about instances like this (docker) but this is the first time I've encountered such a glaring difference. Using JDK 17.0.3 here.

```
Benchmark                                    (dataSize)   Mode  Cnt         Score        Error  Units
SingleValueHashBenchmark.measureSha256               32  thrpt    3  13569533.711 ± 130327.096  ops/s
SingleValueHashBenchmark.measureSha256               64  thrpt    3  10314317.878 ±  27860.687  ops/s
SingleValueHashBenchmark.measureSha256              128  thrpt    3   8073006.144 ±  99810.506  ops/s
SingleValueHashBenchmark.measureSha256              256  thrpt    3   5571927.726 ±  75620.128  ops/s
SingleValueHashBenchmark.measureSha256             1024  thrpt    3   1952367.462 ±   5085.932  ops/s
SingleValueHashBenchmark.measureSha256            32768  thrpt    3     69932.785 ±    204.163  ops/s
SingleValueHashBenchmark.measureSha256           262144  thrpt    3      8777.819 ±      6.978  ops/s
SingleValueHashBenchmark.measureSha256          1048576  thrpt    3      2195.486 ±      0.884  ops/s
SingleValueHashBenchmark.measureSha256blst           32  thrpt    3   1987371.415 ± 118981.794  ops/s
SingleValueHashBenchmark.measureSha256blst           64  thrpt    3   1497922.137 ± 637721.192  ops/s
SingleValueHashBenchmark.measureSha256blst          128  thrpt    3   1179675.993 ± 111154.559  ops/s
SingleValueHashBenchmark.measureSha256blst          256  thrpt    3    850988.774 ± 259867.992  ops/s
SingleValueHashBenchmark.measureSha256blst         1024  thrpt    3    301289.549 ±   9931.898  ops/s
SingleValueHashBenchmark.measureSha256blst        32768  thrpt    3     11298.083 ±     76.443  ops/s
SingleValueHashBenchmark.measureSha256blst       262144  thrpt    3      1414.986 ±      8.910  ops/s
SingleValueHashBenchmark.measureSha256blst      1048576  thrpt    3       353.982 ±      0.292  ops/s
SingleValueHashBenchmark.measureSha256guava          32  thrpt    3  11404590.606 ± 934566.634  ops/s
SingleValueHashBenchmark.measureSha256guava          64  thrpt    3   9115808.500 ± 152685.274  ops/s
SingleValueHashBenchmark.measureSha256guava         128  thrpt    3   7312232.479 ±  66112.513  ops/s
SingleValueHashBenchmark.measureSha256guava         256  thrpt    3   5277752.959 ±  43494.925  ops/s
SingleValueHashBenchmark.measureSha256guava        1024  thrpt    3   1900855.781 ±  12948.674  ops/s
SingleValueHashBenchmark.measureSha256guava       32768  thrpt    3     69643.374 ±     85.433  ops/s
SingleValueHashBenchmark.measureSha256guava      262144  thrpt    3      8776.927 ±     10.479  ops/s
SingleValueHashBenchmark.measureSha256guava     1048576  thrpt    3      2195.471 ±      5.413  ops/s
```

```
Benchmark                                   (dataSize)   Mode  Cnt        Score        Error  Units
SingleValueHashBenchmark.measureSha256accp          32  thrpt    3  7576601.406 ± 326291.729  ops/s
SingleValueHashBenchmark.measureSha256accp          64  thrpt    3  6333668.858 ± 142790.283  ops/s
SingleValueHashBenchmark.measureSha256accp         128  thrpt    3  5242661.718 ± 584941.779  ops/s
SingleValueHashBenchmark.measureSha256accp         256  thrpt    3  3917592.812 ± 688553.419  ops/s
SingleValueHashBenchmark.measureSha256accp        1024  thrpt    3  1589406.114 ±  73611.332  ops/s
SingleValueHashBenchmark.measureSha256accp       32768  thrpt    3    69014.760 ±   2480.834  ops/s
SingleValueHashBenchmark.measureSha256accp      262144  thrpt    3     8758.515 ±     12.786  ops/s
SingleValueHashBenchmark.measureSha256accp     1048576  thrpt    3     2192.861 ±     31.811  ops/s
```

My takeaways from this:
* Holy crap, hashing 32 bytes is 4.5x **faster** on Linux than on macOS!
* Guava is not faster than the SUN provider here.
  * Guava is about 10% faster than SUN in JDK 11 though.
  * With ACCP enabled, Guava is a lot slower; it must use ACCP somehow.
* BLST is a lot slower on Linux. Not sure why.
* Hashing 32 bytes, ACCP is about 2 times **slower** than the SUN provider.
* Except for BLST, all of the implementations have almost the exact same speed with 1MB data.

**Comment by jtraglia** [comment]
One more thing, I believe ~2200 ops/s is the maximum hashing speed for 1MB data on this CPU core. My desktop and laptop have the same CPU core, just my desktop has more cores and they are slightly higher frequency. Hashing 1MB on macOS with BLST ran at 2247 ops/s and hashing 1MB on Linux had a maximum of 2195 ops/s. I believe that SUN and Guava are essentially running native SHA256 implementations on Linux. Not sure how that works. And BLST isn't necessarily faster, macOS is just slow.

**Comment by jtraglia** [comment]
And some results for an x86_64 system:

```

**Comment by jtraglia** [comment]
Results for a Linux/x86_64 system. Using the [AMD EPYC 7763](https://www.amd.com/en/products/cpu/amd-epyc-7763), a high-performance server processor. This uses JDK 17.0.3 and the optimized BLST library. Tested on a headless server with:

```
./gradlew :infrastructure:crypto:jmh --args "SingleValueHashBenchmark"
```

It seems that there is no single "best" SHA256 implementation here. For Linux systems, BLST is not faster than the current implementation. For macOS, SUN and Guava are really slow and BLST is only faster for big data. ACCP performs better than BLST, but it's still slower than SUN and Guava, and it doesn't support macOS. Guava performs better than SUN on macOS/ARM64 systems but worse than SUN on Linux/x86_64 systems.

```
Benchmark                                    (dataSize)   Mode  Cnt         Score         Error  Units
SingleValueHashBenchmark.measureSha256               32  thrpt    3  11168106.414 ± 1693312.076  ops/s
SingleValueHashBenchmark.measureSha256               64  thrpt    3   8426580.543 ± 1080714.507  ops/s
SingleValueHashBenchmark.measureSha256              128  thrpt    3   6434143.259 ± 1213711.771  ops/s
SingleValueHashBenchmark.measureSha256              256  thrpt    3   4318392.835 ±  238493.899  ops/s
SingleValueHashBenchmark.measureSha256             1024  thrpt    3   1467833.927 ±   39928.503  ops/s
SingleValueHashBenchmark.measureSha256            32768  thrpt    3     52639.993 ±     287.069  ops/s
SingleValueHashBenchmark.measureSha256           262144  thrpt    3      6633.187 ±      32.165  ops/s
SingleValueHashBenchmark.measureSha256          1048576  thrpt    3      1658.756 ±      11.942  ops/s
SingleValueHashBenchmark.measureSha256blst           32  thrpt    3   2101046.337 ±  251820.181  ops/s
SingleValueHashBenchmark.measureSha256blst           64  thrpt    3   1597434.107 ±  264535.700  ops/s
SingleValueHashBenchmark.measureSha256blst          128  thrpt    3   1336445.888 ±  175639.015  ops/s
SingleValueHashBenchmark.measureSha256blst          256  thrpt    3    985325.606 ±  102673.307  ops/s
SingleValueHashBenchmark.measureSha256blst         1024  thrpt    3    378604.832 ±    6015.798  ops/s
SingleValueHashBenchmark.measureSha256blst        32768  thrpt    3     14666.045 ±     291.193  ops/s
SingleValueHashBenchmark.measureSha256blst       262144  thrpt    3      1845.417 ±       5.489  ops/s
SingleValueHashBenchmark.measureSha256blst      1048576  thrpt    3       459.266 ±       2.308  ops/s
SingleValueHashBenchmark.measureSha256guava          32  thrpt    3   9724702.156 ±  423845.133  ops/s
SingleValueHashBenchmark.measureSha256guava          64  thrpt    3   7265297.653 ± 1059145.297  ops/s
SingleValueHashBenchmark.measureSha256guava         128  thrpt    3   5672332.036 ±  196066.373  ops/s
SingleValueHashBenchmark.measureSha256guava         256  thrpt    3   4027923.064 ±  627469.845  ops/s
SingleValueHashBenchmark.measureSha256guava        1024  thrpt    3   1434461.048 ±  206594.205  ops/s
SingleValueHashBenchmark.measureSha256guava       32768  thrpt    3     52524.113 ±     597.426  ops/s
SingleValueHashBenchmark.measureSha256guava      262144  thrpt    3      6628.502 ±     119.768  ops/s
SingleValueHashBenchmark.measureSha256guava     1048576  thrpt    3      1658.771 ±       8.452  ops/s
```

```
Benchmark                                    (dataSize)   Mode  Cnt         Score         Error  Units
SingleValueHashBenchmark.measureSha256accp           32  thrpt    3   5453940.010 ±  569751.370  ops/s
SingleValueHashBenchmark.measureSha256accp           64  thrpt    3   4175459.185 ±  504897.258  ops/s
SingleValueHashBenchmark.measureSha256accp          128  thrpt    3   3430860.128 ±  580098.775  ops/s
SingleValueHashBenchmark.measureSha256accp          256  thrpt    3   2656700.427 ±  548776.099  ops/s
SingleValueHashBenchmark.measureSha256accp         1024  thrpt    3   1091475.835 ±  111394.886  ops/s
SingleValueHashBenchmark.measureSha256accp        32768  thrpt    3     51952.495 ±     188.260  ops/s
SingleValueHashBenchmark.measureSha256accp       262144  thrpt    3      6612.083 ±     211.722  ops/s
SingleValueHashBenchmark.measureSha256accp      1048576  thrpt    3      1657.045 ±       8.147  ops/s
```

My takeaways from this:

* BLST is much slower than the other implementations.
  * 5x slower with 32-byte data, 3x slower with 1MB data.
* Guava is slower than SUN (13% slower) with 32-byte data.
* ACCP is about 3 times faster than BLST with all data sizes.

**Comment by lucassaldanha** [comment]
@jtraglia do you have any more thoughts on this or are you happy to close this as BLST does not seem to be an improvement?

**Comment by jtraglia** [comment]
> @jtraglia do you have any more thoughts on this or are you happy to close this as BLST does not seem to be an improvement?

Yes, I think we should close this. It doesn't appear to be much of an improvement.

As a small update, I've learned a lot about blst since making those comments. When hashing large data, I suspect blst was so much slower on Linux targets because I didn't enable to proper features; `__ARM_FEATURE_CRYPTO` on the ARM system and `__SHA__` on the AMD system. But still, JNI overhead will kill performance when hashing small data; the benchmarks on macOS/arm64 show this. The other implementations (guava, accp, sun) are quite fast already.

**Comment by lucassaldanha** [comment]
Thanks for the help @jtraglia 👍
