### ISSUE TITLE
Run security scan on docker images automatically

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4227]
Add an automated check to run `docker image scan` on the Teku docker images and report on any new vulnerabilities.

Should run nightly and not as part of PR approvals as new vulnerabilities can be discovered at any time separate to when code changes.

**Comment by rolfyone** [comment]
I've setup synk to email me with a report on any high/critical issues with the develop jdk 16 image daily, and I'll forward tomorrow once it's been generated, and take it from there.

**Comment by rolfyone** [comment]
There's a new circleci job called 'nightly', which runs a trivy scan, and has the following output:

```
consensys/teku:develop-jdk14 (ubuntu 20.04)
===========================================
Total: 0 (HIGH: 0, CRITICAL: 0)


consensys/teku:develop-jdk15 (ubuntu 20.04)
===========================================
Total: 0 (HIGH: 0, CRITICAL: 0)


consensys/teku:develop-jdk16 (ubuntu 20.04)
===========================================
Total: 0 (HIGH: 0, CRITICAL: 0)

CircleCI received exit code 0
```

I tested with 'Medium' in the list to alert, so that I could see the job fail, and now it's back to just failing on high/critical. I think this is pretty much what we want, and previously failures of this job emailed the team, so I think we should be good to call this 'done'.
