### ISSUE TITLE
Switch state regeneration metrics to use labelled counter

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4465]
### Description
Switch the `storage_memory_states_tasks_requested`, `storage_memory_states_tasks_active`, `storage_memory_states_tasks_queued`, `storage_memory_checkpoint_states_tasks_requested`, `storage_memory_checkpoint_states_tasks_active` and `storage_memory_checkpoint_states_tasks_queued` metrics to use a single labelled counter.

**Comment by arhamj** [comment]
A couple of questions. 
1. What about the `tasks_total` and the `cache_size` metrics, do we leave them as is?
2. Could I use a labelled double gauge instead of a labelled counter, to address decrementing of the counter value?
3. Would the nomenclature (`_tasks` => metric name), (`status` => label name) work?

If not picked already I could pick this issue

**Comment by regio** [comment]
@arhamj yes, you can pick this.

**Comment by ajsutton** [comment]
1. Yes the `tasks_total` and `cache_size` metrics should remain separate.
2. Yes sorry, the title should have said labelled gauge not counter.
3. and yes I think that nomenclature works.  So we'd wind up with things like storage_memory_states_tasks{status=requested}

**Comment by arhamj** [comment]
@ajsutton can you help review the PR?
