### ISSUE TITLE
Update ansi-regex:5.0.0 to version 6.0.1 to avoid vulnerability

### ISSUE THREAD

**Issue by cesarsotovalero** [Consensys-Incorporated/teku#4550]
### Description

I ran the [OWASP Dependency-Check](https://owasp.org/www-project-dependency-check/) tool on the Teku codebase. It founds that dependency `ansi-regex:5.0.0`, declared [here](https://github.com/ConsenSys/teku/blob/master/.openapidoc/package-lock.json#L221-L229), is vulnerable to Inefficient Regular Expression Complexity, see [CVE-2021-3807](https://github.com/advisories/GHSA-93q8-gq69-wqmw).

### Action

I suggest updating this dependency to the latest patched version [6.0.1](https://www.npmjs.com/package/ansi-regex), which is not affected by this vulnerability.

**Comment by ajsutton** [comment]
Thanks for raising this.  It is worth noting that `ansi-regex` is not actually a part of Teku or anything we publish, it's part of the build script to export the OpenAPI documentation during the build.  Since we control all the regex it can execute I don't believe the CVE applies here but updating is a good idea anyway.

**Comment by rolfyone** [comment]
NPM suggested that 5.0.1 would be sufficient to get past the listed vulnerability, which is likely to be more compliant with whatever the tool is used for now, so I've taken that recommendation into the PR.
