### ISSUE TITLE
Some merge related flags have weird flag dependencies

### ISSUE THREAD

**Issue by skylenet** [Consensys-Incorporated/teku#4762]
### Description
I was trying to join the merge devnet3 and added the following flags to my Teku node : 

```
--Xdata-storage-non-canonical-blocks-enabled=true
--Xnetwork-merge-total-terminal-difficulty=5000000000
...
```

Then I noticed that I got the following message when the node started:

`Unknown options: '--Xdata-storage-non-canonical-blocks-enabled=true', '--Xnetwork-merge-total-terminal-difficulty=5000000000'`

I found it weird, because I had @parithosh already using these flags on a running node using the same version. 
I ended up figuring out that if I don't define the `--metrics-host-allowlist` ... then this won't work. 

### Steps to Reproduce (Bug)

Run without the metrics-host-allowlist flag:
```sh
$ docker run --rm -it parithoshj/teku:merge-b6d8129 \ 
   --Xdata-storage-non-canonical-blocks-enabled=true --Xnetwork-merge-total-terminal-difficulty=5000000000
# Output:
Unknown options: '--Xdata-storage-non-canonical-blocks-enabled=true', '--Xnetwork-merge-total-terminal-difficulty=5000000000'
```

Then run with the metrics-host-allowlist flag and notice that the node will start:
```sh
$ docker run --rm -it parithoshj/teku:merge-b6d8129 \ 
   --metrics-host-allowlist="localhost" \
   --Xdata-storage-non-canonical-blocks-enabled=true --Xnetwork-merge-total-terminal-difficulty=5000000000
   
```

**Expected behavior:** [What you expect to happen]

Don't require to set --metrics-host-allowlist for the other flags to work. 

### Versions (Add all that apply)

```
$ docker run --rm -it parithoshj/teku:merge-b6d8129 --version                                                                       
teku/vUNKNOWN+gb6d8129/linux-x86_64/-eclipsefoundation-openjdk64bitservervm-java-16
```

**Comment by parithosh** [comment]
I'd additionally like to add that the behaviour is also seen using teku's official docker image `consensys/teku:develop`. The bug and behaviour with `--metrics-host-allowlist="localhost"` is exactly the same.

**Comment by ajsutton** [comment]
This is occurring because both of those options are invalid.  The valid options are `--data-storage-non-canonical-blocks-enabled` and `--Xnetwork-merge-total-terminal-difficulty-override`.

They aren't rejected when put after `--metrics-host-allowlist` because `--metrics-host-allowlist` can accept multiple values so any unknown options that follow it are treated as allowed domains.  

I've seen this confusion come up a few times recently so have opened https://github.com/ConsenSys/teku/issues/4765 to try to ensure we consistently report invalid options and will close this one.

For the record, you can see all the `--X` options teku supports by running `docker run --rm -it parithoshj/teku:merge-b6d8129 -X` (or `teku -X`).
