### ISSUE TITLE
Duplicate public key group membership checks somewhere in sync committee handling

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#4776]
The group membership test for public keys is necessary but expensive. We try to do this exactly once for each key by performing the check lazily and caching the result in the `PublicKey` object.

I dumped out the public keys tested for group membership during a short sync.

```
> wc -l keys.txt 
270068 keys.txt
> cat keys.txt | sort | uniq | wc -l
266806
```

This indicates that we have a small number of unnecessary duplicate checks going on (3262 of them, about 1.2%).
```
> cat keys.txt | sort | uniq -c | sort -rn | less
      8 >>> b9c49d06dc9b10ac4227a9f5f2cbb1127b29f519332c5c8d0cd63bd36d6683b6c264b320ea7fb03ab5bb9236b7338bb6
      8 >>> b9a4a6991f7651ee2e28ac580a184d4ee64de522217721d67120e9703cd0413092a94d8fcc06ad3ce7d77f5a5d5e21b2
      8 >>> b97cdcc4a27193c865037f78a2763b80f689a0c9a5f9b7273e9e7eea00016359998c9f7bf1b0597748867a28853f4d7c
      8 >>> b925d532d130d45c240bcf69b7f9a65117086746e1789147ae258a952aad7e72d36f6665f0c858b059c3adfa529c6bb8
      8 >>> b91767217e91527ac0dba104f68bbb511b298facca7478bd02f348dc13ea9546a196b54b63db18831261523315a340ed
      8 >>> b9022ccf8e347aa711d9847e893371ab3171732bf3852750925467058691ec0757c3372e232d1be407bb11bd275b2a33
      8 >>> b8ec52bdc31d2c9db8c3fe319c561f7ad5048c6849d5ad7c4466f9c077fe50253aa2ae9febe99d52cfc6ca1cd69e38e7
      8 >>> b8b24e0bd208100f8dd0958613dc79b984bfd225095580683017ebfe482d7fa1143d6164509bbf9d55d05407deed8fa8
...
```

So a bunch of public keys were group-checked 8 times.

On a hunch, I checked the first few keys, and they are all current members of the sync committee.

### Conclusion
Somewhere in the sync committee code we are creating new PublicKey objects rather than re-using the ones we have, leading to unnecessary group membersip checks.

**Comment by benjaminion** [comment]
This is probably due to a `BLSPublicKey.fromBytesCompressed()` somewhere, which may be unavoidable, but if we have (or can look up) the validator index we should prefer `Spec.getValidatorPubKey()`. See the comment [here](https://github.com/ConsenSys/teku/blob/master/ethereum/spec/src/main/java/tech/pegasys/teku/spec/datastructures/state/Validator.java#L123).

**Comment by benjaminion** [comment]
[This  gist](https://gist.github.com/benjaminion/92709920e12dbf9244d084a078276c2c) shows stack traces for the occasions when the `BlstPublicKey fromBytes()` method is called for public key: `b9c49d06dc9b10ac...`. This method ought ideally to be called only once per key. Might give some clue as to where the new PublicKey objects are being created, but it's not immediately clear to me - because our deserialisation is also lazy these traces show when the key is used rather than when it was created. Gah.

**Comment by benjaminion** [comment]
Some further stack traces suggest that the issue is [here in SszPublicKey.java](https://github.com/ConsenSys/teku/blob/9aeda7b8e270b04ed6f9720c9cb1c980dd81d21d/ethereum/spec/src/main/java/tech/pegasys/teku/spec/datastructures/type/SszPublicKey.java#L47). This looks like it is re-making the public key rather than re-using it, but I freely confess to being out of my depth at this point.

It's called from [here](https://github.com/ConsenSys/teku/blob/df595d98cd264789fa58f8cba156337e354b9ce4/ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/synccommittee/SignedContributionAndProofValidator.java#L271), and [here](https://github.com/ConsenSys/teku/blob/9aeda7b8e270b04ed6f9720c9cb1c980dd81d21d/ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/altair/block/BlockProcessorAltair.java#L185), and [here](https://github.com/ConsenSys/teku/blob/master/ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/common/util/SyncCommitteeUtil.java#L121), all involved in sync committee stuff,  and appears to recreate a fresh public key each time.

**Comment by ajsutton** [comment]
Good spot.  Avoiding this can be quite challenging because sync committees are defined by their public keys so we have to go out of our way to convert from public key to index and back to the cached public key. I suspect we can't avoid remaking the public key when getting it from SSZ data but need to make sure we do this switch properly.

I think one place we're getting this wrong is `BlockProcessorAltair.processSyncAggregate` which is using the pub keys directly instead of swapping for the cached version. But there's also things like `Validator.getPublicKey` and places in the API which are potentially using public keys that they should get from cache - not sure if those instances are triggering group membership checks or not.

Ideally we'd redefine `SszPublicKey.getBLSPublicKey` to something that takes a public key cache and automatically returns the cached version.  This isn't as simple as it sounds though as the public key cache is actually in `StateTransitionCaches` and currently done from validator index -> public key (it also has public key -> validator index cache). May need to do some profiling to get the right data structures here.  It will be important to ensure that the cache always holds all validator public keys - if it has a strict limit on the number of keys cached the validator set may outgrow that limit and we'll suddenly have huge performance problems.

**Comment by ajsutton** [comment]
We are also getting this wrong in `SignedContributionAndProofValidator.getParticipantPublicKey` which winds up using the public key from the sync committee directly instead of the cached version.
