### ISSUE TITLE
[Optimisation] Avoid reprocessing of locally produced blocks

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#4792]
### Description
We could avoid reprocessing blocks that has been locally generated\proposed.

![image](https://user-images.githubusercontent.com/15999009/146158926-f2a9a362-64fc-4532-b744-b5beb49d9b6e.png)

**Comment by ajsutton** [comment]
The EL will already optimise this so I wouldn't try to special case it. If we were going to special case it, we'd be better off skipping the processing of the whole block - we'd have to check the block signature since that's created by the validator but could just keep a short term cache of the `BeaconBlock` and resulting `BeaconState` to import without reprocessing.

**Comment by lucassaldanha** [comment]
Closed as not planned.
