### ISSUE TITLE
Send periodic keep alive

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4840]
### Description
Once we have Javalin updated to a version that can send event source comments, periodically send an empty comment to all event source connections so they don't time out.

It's likely sufficient to just send the blank comment every 15 seconds regardless of whether other messages are sent as the bandwidth overhead is very low.

**Comment by ajsutton** [comment]
The two key classes here are `EventSubscriptionManager` and `EventSubscriber`.  Probably the best approach is to have `EventSubscriber` handle sending the keep alive comments itself.  It already has an `AsyncRunner` instance it can use to schedule regularly repeating events, it would need to ensure that the repeating events are stopped when the `SseClient` instance is closed (it's already using `sseClient.onClose` to register a close listener in the constructor so could add to that).

**Comment by rolfyone** [comment]
For manually seeing what's going on, can use 
```
curl -X GET "http://localhost:5051/eth/v1/events?topics=voluntary_exit" -H "accept: text/event-stream"
```
any event really, use 'head' if you want to see a lot of events, or something like voluntary exit above if you want to see just the comments...

```
sseClient.sendComment(" ");
```
will send a comment on the stream to a client, that's the new feature I added in javalin 4.2.0 to use for this ticket. We don't need to send anything really in a comment, could test if empty string works rather than space, otherwise just a space will suffice.

https://github.com/ConsenSys/teku/pull/4844

There was a commit here that implemented the keepalive poorly, but I've left in the test suite functionality to count comments.
