### ISSUE TITLE
`getParameterAsIntegerList` parses values as unsigned integers

### ISSUE THREAD

**Issue by jtraglia** [Consensys-Incorporated/teku#4947]
### Description

The `getParameterAsIntegerList` method parses values as unsigned integers instead of signed integers. 

https://github.com/ConsenSys/teku/blob/9c0086ca5af0f90eddc26ca437475adfa7afc914/data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/ListQueryParameterUtils.java#L50 

On the other hand, `getParameterValueAsInt` uses the `Integer.parseInt` method as one might expect.

https://github.com/ConsenSys/teku/blob/9c0086ca5af0f90eddc26ca437475adfa7afc914/data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/SingleQueryParameterUtils.java#L62

I would expect `getParameterAsIntegerList` to parse values as signed integers like `getParameterValueAsInt` does, or for `getParameterValueAsInt` to parse values as unsigned integers.

This is a super minor issue, as `getParameterAsIntegerList` is not even used yet.

**Comment by jtraglia** [comment]
It looks like the `getParameterAsIntegerList` function was used in `GetAttesterDuties` (now `PostAttesterDuties`) but they have since changed the call to (correctly) parse the indices as an `UInt64` array.

https://github.com/ConsenSys/teku/blob/5a4db7401894d8ce369b322762195ae507730f66/data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/v1/validator/PostAttesterDuties.java#L117

**Comment by jtraglia** [comment]
I've noticed another discrepancy that I think is worth asking about. `PostSyncDuties` is supposed to take the same inputs as `PostAttesterDuties` but it parses the index values as an `Integer` array instead of `UInt64` array.

https://github.com/ConsenSys/teku/blob/5a4db7401894d8ce369b322762195ae507730f66/data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/v1/validator/PostSyncDuties.java#L104

I think there would be a problem if an index larger than 2^32 is provided. The doc string even says uint64 types.

https://github.com/ConsenSys/teku/blob/5a4db7401894d8ce369b322762195ae507730f66/data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/v1/validator/PostSyncDuties.java#L85-L86

References:
* https://ethereum.github.io/beacon-APIs/#/Validator/getAttesterDuties
* https://ethereum.github.io/beacon-APIs/#/Validator/getSyncCommitteeDuties

**Comment by jtraglia** [comment]
Sorry to keep commenting. So it will not crash if given a 64-bit index. It will throw an exception and return a bad request message. But I think that `getAttesterDuties` and `getSyncDuties` should take `List<UInt64>` indices instead of `List<Integer>` like they currently do. According to the spec, `ValidatorIndex` and `CommitteeIndex` are `uint64` types.

References:

* https://github.com/ethereum/consensus-specs/blob/02b32100ed26c3c7a4a44f41b932437859487fd2/specs/phase0/beacon-chain.md#custom-types

**Comment by ajsutton** [comment]
Thanks for raising these. It's on our list to review.

**Comment by rolfyone** [comment]
`getParameterAsIntegerList` - this function was only used in test code, so I've removed the function and associated tests.

Regarding use if integers to represent validator id's, largely discussed on discord with @ajsutton.

The cliff notes for future reflection:
 - Internally validator arrays etc. are actual java arrays, and these have a limitation of using integer offset because of the primitives.  We can read in as `UInt64`, but ultimately, we're referencing into an array and this needs to use integer type for position.
 - If we ever have more than `MAX_INT` validators, then we'll need a lot of very significant changes to the system, and the api representation would be just a very small adjunct to that change, for now we are accepting that the internal representation is much smaller than the theoretical maximum.

If I've missed anything significant in the discord discussion, please feel free to add. For now I'll go ahead and put up a PR that removes the unused code.

**Comment by jtraglia** [comment]
@rolfyone Thank you making this change. This is fine with me.
