### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot create attestation for future slot.

### ISSUE THREAD

**Issue by theRealYoshi** [Consensys-Incorporated/teku#5131]
### Description
[Detailed description of the problem and the impact it has]

### Steps to Reproduce (Bug)
[Please be as specific as possible]
Randomly get this error when the client runs:

ERROR - Validator   *** Failed to produce attestation  
java.lang.IllegalArgumentException: Cannot create attestation for future slot.
Requested 3327683 but current slot is 3327680

**Expected behavior:** [What you expect to happen]
It should be running smoothy

**Actual behavior:** [What actually happens]
Looks like it attest a slot in the future that does not exist yet

**Frequency:** [How regularly does it occur?]
Every 8-9 hours ish. 

### Versions (Add all that apply)
* Software version: [`teku --version` or look for log lines starting with `Teku version:`]
* teku-22.3.0
* Java version: [`java -version`]
* 
* OS Name & Version: [`cat /etc/*release`]
* 
* Docker Version: [`docker version`]
* Docker version 20.10.12,
* Cloud VM, type, size: [Amazon Web Services I3-large]
* AWS us-east-2 r5.8xlarge

**Comment by ajsutton** [comment]
As discussed on discord: This message indicates that the beacon node is struggling to keep up - in this case from memory because the java heap size was too small.

That said we do plan to do some work to avoid this particular symptom of the node struggling in the future but likely it still wouldn't perform well. The beacon node should be load shedding to catch up much sooner rather than having its view of the current slot fall behind by so much.

**Comment by benjaminion** [comment]
Closing as no modifications to Teku required.
