### ISSUE TITLE
Optimisation idea: batch verify deposit signatures in a block

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#5254]
Currently we check deposit signatures [one-by-one](https://github.com/ConsenSys/teku/blob/70e2d323748f668af288c89d9c5813bab28b8df1/ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/common/block/AbstractBlockProcessor.java#L654) when processing new deposits. Since there are up to 16 deposits per block we could likely save some time by batch verifying them together. We don't need to know which one fails (if any) as the whole block is invalid if any signature is invalid.

**Comment by ajsutton** [comment]
Deposits can be included in blocks even if they have invalid signatures and the processing of those deposits changes depending on whether the signature is valid or not (deposits with invalid signatures that add new validators are ignored).

But given that most deposits do have valid signatures it probably does make sense to do a single batch validation of them and then if that's invalid fall back to individually validating them.  It would cost at least 1ETH for every time you made us do that so not much of a DOS risk.  There's a few details around that since we don't currently check signatures for deposits to existing validators but since most deposits are for new validators it may still be a net win to just check them all up front.

**Comment by benjaminion** [comment]
> Deposits can be included in blocks even if they have invalid signatures

Ah, yes - this is the exception to the rule that everything in a block must be valid, since deposits must be handled consecutively. Just testing 😉

**Comment by ajsutton** [comment]
Don't worry I've been round that loop a few times and went to implement this optimisation again the other day.  There's a comment in the `isSignatureValidMethod` to remind me why it won't work now.
