### ISSUE TITLE
sync committee gossip should not be processed while in sync mode

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#5300]
when in sync mode, its possible to get 
```
teku 2022-04-05 23:09:36.734 WARN  - Ignoring sync committee gossip because the chain head is too old. Chain head slot 3519574 is more than an epoch before the required slot 3522560
```

if sync committee gossip isn't unsubscribed, and it's quite noisy in logs.  I suspect the answer is we should unsubscribe to sync committee channels while we're in sync mode, and coming out of sync mode any subscriptions should be re-issued.

I'm not sure if it's worth just not even attempting to process the messages while syncing, but that may be another option, we just ignore them... will need to clarify preference with @ajsutton

**Comment by ajsutton** [comment]
We normally unsubscribe from all gossip channels when we're far enough behind the chain head and sync committee gossip would be included in that.  Maybe that cut off is too far back but I suspect this is a symptom of bigger problems on the box at the time.  This log message is saying we're ignoring the message because the head is too far back.

**Comment by ajsutton** [comment]
Going to close this - I haven't seen it since so I think that particular box in a bad state and hadn't unsubscribed from gossip for some reason despite being so far behind.
