### ISSUE TITLE
Builder API Compatability with Distributed Validators - Validator Registration

### ISSUE THREAD

**Issue by ciaranmcveigh5** [Consensys-Incorporated/teku#5898]
### Distributed Validators Require Signed Contents To Be The Same - ValidatorRegistrationV1

The current implementation of the validator registration isn't compatible with a distributed validator

For distributed validators it's important that the signed contents are the same across all "co-validators"  

Teku currently uses timeProvider.getTimeInSeconds() for the Timestamp in ValidatorRegistrationV1, time.now in milliseconds are likely to never match

- The simplest solution would be an --X param that effectively hardcodes the timestamp, this could be done via an actual timestamp, a slot number or an epoch number, in this situation it's up to the co-validators to co-ordinate to ensure they all have the same config set for "timestamp"
- Since Teku uses the first signature (with the hardcoded timestamp) for any subsequent re-registrations the distributed validator will simply need to update their registration config which would include timestamp to register with new information on a relay

see here for discussion in discord https://discord.com/channels/697535391594446898/697539289042649190/994236320799002705

cc @tbenr

**Comment by corverroos** [comment]
A hardcoded flag with a "random" timestamp might be the easiest solution to implement, but it moves the complexity of co-ordinating and configuring to operators of the distributed validator.

Since periodic registrations are done at the start of every epoch, the epoch start time could also be used. This reduces operation and coordination overhead at the cost of increased implementation complexity and one additional signature per validator per epoch.
