### ISSUE TITLE
Subnet subscriptions configuration for entry nodes

### ISSUE THREAD

**Issue by lucassaldanha** [Consensys-Incorporated/teku#6112]
To reduce the bandwidth and CPU requirements for beacon nodes in a large staking service, we should be able to delegate which beacon node to use for specific attestation subnets. Subscription requests, creating aggregates and publishing attestations should be directed to the beacon node assigned to that attestation/aggregate’s subnet.

This is a continuation of the [Sentry Beacon Nodes](https://docs.teku.consensys.io/how-to/use-sentry-nodes#configure-sentry-nodes)

The BN subnet subscriptions could be spread across different BNs based on the sentry node configuration file. 
Example:
```
{
    "beacon_nodes": [
        {
            "attestation_subnets": {
                "start": 0,
                "count": 32,
                "endpoints": ["http://nodeA:9051"]
            },
            "attestation_subnets": {
                "start": 33,
                "count": 31,
                "endpoints": ["http://nodeB:9051"]
            },
            "sync_committee_subnets": {
                "start": 0,
                "count": 32
                "endpoints": ["http://nodeA:9051"]
            }
            "sync_committee_subnets": {
                "start": 33,
                "count": 31
                "endpoints": ["http://nodeB:9051"]
            }
        }
    ]
}
```

**Comment by mehdi-aouadi** [comment]
Turned out this issue is broader than expected. To start I converted it to an Epic and here is why:
- [The subnets subscription revamp](https://github.com/Consensys/teku/pull/7341) solves a small part of what is suggested only. The BN subscribes to 2 persistent subnets only now and to others according to the VC assigned attestation aggregation duties (running more than 64 validators could end u making the BN connecting to all subnets though). The proposed solution is to make the user able to assign specific subnet ranges to specific BNs (when many are used) in order to balance the load.
- What is suggested doesn't concern the attestations subnets handling only but also how the VC requests are handled by the BNs in general (the attestations subnets being what triggered this reflection imu). The proposed solution is to make it possible, using a configuration file, to assign tasks to specific BNs (`calculate_duties`, `create_blocks`, `publish_blocks`, `create_attestations`, `publish_attestations`, `create_aggregates`...). More details can be found in [this note](https://hackmd.io/0jhD6wEzQLWnE3huXLkjgg#Minimize-Subnet-Subscriptions)
- The suggested changes will probably affect how the BNs failover mechanism is currently implemented
- The feature requires new configurations files in order to orchestrate the VC requests across different BNs

**Comment by mehdi-aouadi** [comment]
IMO since the subnet [subscription revamp](https://github.com/Consensys/teku/issues/7296) has been merged, this issue could be closed.
- The motivation behind it was to reduce cpu requirements for BNs because they were subscribing to all subnets but they are now subscribing to 2 persistent subnets only ans we already measured a nice cpu usage drop since the change has been merged
- This adds  a lot complexity to the sentry nodes configuration and make it error prone and hard to stay consistent
- We didn't get clear feedback about the sentry nodes feature and not sure if building such feature on top of it could be useful from an end user point of view
