### ISSUE TITLE
Teku validator client does not load all the keys from external signer

### ISSUE THREAD

**Issue by ghost** [Consensys-Incorporated/teku#6129]
### Description
- Teku validator client does not load all the keys from external signer, it fails silently or without a detailed error message, which causes many of our validators to miss attestations

### Steps to Reproduce (Bug)
[Please be as specific as possible]

Teku validator clients: We run these each configured to manage ~240 keys.  They connect to a kubernetes svc beacon node load balancer w/ .25 cpu,  0.5Gi ram with the following parameters:
```
teku validator-client --network=auto --log-include-validator-duties-enabled=true --log-include-events-enabled=true --metrics-enabled=true --metrics-host-allowlist=* --metrics-port=8081 --metrics-interface=0.0.0.0 --data-path=/data --validators-external-signer-public-keys="http://$POD_IP:5050/api/v1/eth2/publicKeys" --beacon-node-api-endpoint="http://cl-teku-beacon.eth.svc.cluster.local:5051/" --validators-external-signer-url="http://$POD_IP:5050" --validators-external-signer-timeout=2500 --log-color-enabled=false --log-file=/tmp/ethereum2.log
```

Message in teku logs when this happens
```
[eth-validator-teku-eth-wallet-0176-0] 21:37:54.706 ERROR - External signer is currently not reachable at http://10.46.153.75:5050/
[eth-validator-teku-eth-wallet-0176-0] 21:38:44.307 ERROR - Validator   *** Failed to produce attestation  Slot: 4546091 Validator: b4f882e tech.pegasys.teku.validator.client.signer.ExternalSignerException: External signer (http://10.46.153.75:5050/) failed to sign due to java.net.http.HttpTimeoutException: request timed out (See log file for full stack trace)
```

**Expected behavior:** [What you expect to happen]
- Better retry from validator client to external signer to get all load keys and/or be more explicit when it cannot load all keys
- Same behavior as prysm

**Actual behavior:** [What actually happens]
- Fail silently

**Frequency:** [How regularly does it occur?]
- When multiple validator clients are restarted together

### Versions (Add all that apply)
* Software version: [`teku --version` or look for log lines starting with `Teku version:`] 22.8.1
* Java version: [`java -version`] eclipse-temurin:17.0.3_7-jdk-focal
* OS Name & Version: [`cat /etc/*release`] ubuntu:20.04 docker base image
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by ajsutton** [comment]
Thanks for the info.  The logs indicate that Teku made five attempts to start.  The first four attempts to exited immediately with the error message:
```
Failed to load public keys from URL http://10.46.159.194:5050/api/v1/eth2/publicKeys
```

This is because the external signer did not respond with the list of keys Teku should run. I’m assuming that Kubernetes automatically restarted teku  which caused it to retry loading the keys and again failed.  The logs also show that Teku has been configured to log to `/tmp/ethereum2.log` and additional detail on why the request to the signer failed will be in that log file. When the validators are unable to be loaded, teku has no way possible way to operate. The only two options are to exit with an explanation as it does, or continue running without performing any duties and repeatedly retry loading. We’ve chosen to have Teku exit in this case for a few reasons:

1. Having the process exit tends to trigger monitoring alerts much more quickly and clearly than just having error messages in the log
2. Given this instance of Teku has never seen the supplied URL work, it may be that there’s been a misconfiguration and the URL will never work, in which case retrying wouldn’t help
3. In most setups there should be a system designed to automatically restart the process anyway which causes it to retry the request. It appears Kubernetes is doing that in this case

On the fifth attempt, Teku successfully loaded 246 validator keys and began loading and performing duties for them. The `External signer (http://10.46.153.75:5050/) failed to sign due to java.net.http.HttpTimeoutException` message indicates that when Teku requested the external signer sign an attestation as part of performing one of those scheduled duties, the signer did not respond in a timely fashion and the request failed because of that timeout. 

So firstly in terms of logging, it looks like Teku is configured to split logging between the console and log file, but only the console output seems to be getting captured. For a Kubernetes setup, setting `--log-destination console` is generally recommended so that all log output is sent to the console.  That said, in this case the console log is already clearly reporting each failure with the indication that the signer is not responding.

As to why the signer is timing out after a restart, when the validator client restarts, it needs to recalculate all the duties that each validator is required to perform. As part of that, each validator needs to create a signature, via the external signer, to determine if it is the aggregator for the slot it is scheduled in. Duties can be calculated for both the current and next epoch so each validator would need to create two signatures as part of calculating those duties. So when the validator client is restarted, there is an increase in the number of signing requests sent to the external signer.  The signer doesn’t appear to be able to handle this increased load, leading to a timeout on some requests, while other requests are succeeding as seen by the log messages from Teku about successfully publishing attestations.

When signing an attestation times out, Teku doesn’t retry because the attestation is already late and unlikely to be included and issuing another signing request to an already overloaded external signer would just overload it further likely leading to missing other attestations as well.

Ultimately resolving this issue will require identifying why the external signer is unable to respond in a timely manner. I’d also recommend looking at its response times even outside periods where validator clients have restarted as if it’s close to its resource limit there may be delays that don’t reach the timeout threshold but still slow down production of attestations and potentially reduce the rewards earned.

Teku does have a couple of options to help tune its behaviour when the external signer is struggling to respond. Firstly the timeout can be adjusted with `--validators-external-signer-timeout` currently you’ve’ reduced this to 2500ms which gives the signer less time and makes timeouts more likely. Leaving this at the default of 5s would make timeouts less likely.

The rate of signing requests sent to the external signer as part of calculating duties can also be restricted with the `--Xvalidators-external-signer-concurrent-limit` option. The default is to limit to 32 concurrent requests and this could be reduced. A lower value will send fewer requests to the signer at a time, making it less likely to become overloaded, but will also mean it takes longer for Teku to calculate the duties for all validators which may introduce delays in beginning to perform those duties if the limit is set too low and the signer is still slow to respond.

**Comment by ghost** [comment]
Thanks, @ajsutton, we'll roll out the `--validators-external-signer-timeout=5000``` and report if we're still having issues.

**Comment by ajsutton** [comment]
Going to close this one, but feel free to reopen or reach out if it's still happening with the increased timeout.
