### ISSUE TITLE
Teku validator client requires fee recipient before Bellatrix upgrade

### ISSUE THREAD

**Issue by ghost** [Consensys-Incorporated/teku#6130]
### Description
- Teku validator client requires fee recipient before Bellatrix upgrade, prysm validator client does not.  This miss in config caused many of our validators to miss attestations

### Steps to Reproduce (Bug)
[Please be as specific as possible]
- teku beacon upgraded to 22.8.1 and configured with default fee recipient
- teku validator client running at 22.6.1 (not upgraded as we did not want to restart yet)

**Expected behavior:** [What you expect to happen]
- Consistent behavior as prysm
- Backwards compatibility between beacon and validator client
- Make it clear in release notes at what point exactly the config is needed

**Actual behavior:** [What actually happens]
- Failed with:

```
[eth-validator-teku-eth-wallet-0222-0] Invalid configuration. --validators-proposer-default-fee-recipient or --validators-proposer-config must be specified when Bellatrix milestone is active
```

**Frequency:** [How regularly does it occur?]

### Versions (Add all that apply)
* Software version: [`teku --version` or look for log lines starting with `Teku version:`] teku beacon: 22.8.1; teku validator client: 22.6.1
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by rolfyone** [comment]
Thanks for raising this, can you confirm your validator-client was either not specifying `--network` or was using `--network=auto`?

This setting would fetch network settings from the beacon-node when it connects, and that would result in the VC getting informed of the pending bellatrix network upgrade, and it would behave as you are describing...

A workaround would be to specify `--validators-proposer-default-fee-recipient`, and you'll be able to continue to use the old VC with the new network configuration, and be compliant with the minimal requirements for the merge. If we were to default the setting, it'd be to 0x00, and that'd cause the flow on effect of burning any earnt eth silently if you don't give an appropriate value.

**Comment by ghost** [comment]
yes, validator client was using `--network=auto`, and we fixed it by specifying `--validators-proposer-config` and upgrading validator client to 22.8.1.  But we had to do it more as a firedrill, rather than the intended planned rollout to beacons first and then validator clients.  

Not sure, there is much to fix here, other than docs and consistent workflow as prysm for next time.

**Comment by ajsutton** [comment]
Ok, going to close this one. We expect that fee recipient is required for any network where bellatrix is scheduled. I can see why this is a bit surprising given the VC didn't update, but it was still a configuration change applied to the validator client which caused it. This is a one off transition where we had to make a choice between refusing to startup when required config is missing or running with the invalid config and then failing when the merge actually happened (or burning the fees).  We went with refusing to start because it's much more visible, ensuring the configuration problem gets fixed rather than missing block proposals (which is also then bad for overall network health).
