### ISSUE TITLE
Allow users to set a fee cutoff to use a block supplied by the builder API

### ISSUE THREAD

**Issue by allboxes** [Consensys-Incorporated/teku#6140]
### Description
User's are required to make a binary choice between using a centralized block builder or forgoing MEV.

**Expected behavior:** [What you expect to happen]
Allow user's to set a fixed fee cutoff under which they will use a locally produced block.  

In this way validators can gain exposure to large MEV opportunities while still contributing to decentralized block building when MEV is small/non existent.

Additionally, as the CL does not currently have a view into the value of a locally produced block, this provides some protection to user's from relay's producing very low value blocks.

In the future this can be enhanced by comparing the value of the locally built block vs. the remote builder's submission and using a fee delta instead of a fixed fee..

**Comment by ajsutton** [comment]
This is a good idea.  It _could_ be done in the beacon node, but this kind of feature would ideally live in the MEV sidecar (eg mev-boost) which is already responsible for comparing the bids from different relays and selecting which one to use. It would make a lot of sense for it to have an option to return no bid if a minimum value isn't reached and the beacon node would then automatically fallback to using the local EL.

There are two advantages to this, firstly it avoids adding more complexity from MeV into the beacon node and secondly, it would make the feature available to all beacon node implementations at once rather than each having to independently implement it.

**Comment by allboxes** [comment]
That's a good point. I submitted it to MEV-Boost.

**Comment by allboxes** [comment]
It looks like Lighthouse/Prysm are implementing this and I'm not getting much traction on the MEV-Boost relay for the issue/PR so thought I'd put it back on your radar in case you have the bandwidth to include it here.

**Comment by metachris** [comment]
If there's wider interest in this feature as part of mev-boost, please signal your interest with a 👍 on https://github.com/flashbots/mev-boost/issues/273

**Comment by allboxes** [comment]
Implemented in MEV-Boost
