### ISSUE TITLE
Expose current sync committee and next sync committee per pubkey in the validator prometheus metrics

### ISSUE THREAD

**Issue by ghost** [Consensys-Incorporated/teku#6270]
# 🚀 Feature Request

### Description

Mainly need to know two things (from sync committee perspective):
- which pubkey is in a sync committee currently
- which pubkey will be in a sync committee next

If we're really concerned about data, then as a baseline, even just knowing that the validator has one of the keys in sync committee currently and/or next would be useful to expose via prometheus, so we can plan maintenance at the validator level (which is managing for us ~200-300 pubkeys) accordingly.  

### Describe the solution you'd like

Expose prometheus metric per pubkey in the validator metrics

### Describe alternatives you've considered

I've looked at https://www.coincashew.com/coins/overview-eth/guide-or-how-to-setup-a-validator-on-eth2-mainnet/part-ii-maintenance/checking-my-eth-validators-sync-committee-duties already, but would like to have this via prometheus

### Links:
- [ethstaker teku-helpdesk discord conversation](https://discord.com/channels/694822223575384095/782670046736285697/1025413246217375814)
- similar to https://github.com/prysmaticlabs/prysm/issues/11522
- [Prysmatic Labs code-review channel discord conversation with potuz and prestonvanloon](https://discord.com/channels/476244492043812875/483017808658169866/1025450792112631848)

**Comment by rolfyone** [comment]
Thanks for raising, we had some discussions around this...

I think the key concern with labelled gauges with labels containing pubkeys is that it's a lot of extra metrics being tracked. probably not so bad when its only 200-300, but when you're getting into the thousands it would be quite a thing...

One suggestion was to have a count of the validators (on the current vc) in the current sync committee, and a count of the validators in the next sync committee - would that be suitable for your needs?

**Comment by ghost** [comment]
I think a count meets the minimum requirements for an operator like us to know when not to do maintenance on a VC and that's suitable for now, but obviously, knowing the pubkey would give the best visibility thru prometheus.


Also, I brought up standardization for metrics like these across the consensus clients: https://github.com/prysmaticlabs/prysm/pull/11523#issuecomment-1265598591, consistency and standardization would help greatly to increase the client diversity, thanks!

**Comment by rolfyone** [comment]
There's a level of standard around the metrics, but definitely a minimal set of standard across all clients would be good. There's been varying degrees of attempts to do it, and a lot of things have been moved, but I wouldn't say there's currently a 'standard'.

Partially metrics are to measure specific things, and these things change, but I do agree that certain things are consistent to all clients and could be consistently named.

Implementation note for future reference, we might be able to use a metrics category for adding the detailed entries of each validator pubkey and current / next committee, so that you'd enable that category if you want that level of detail.. Potentially off by default so that larger validator sets don't get too much volume from this change.  A count would be potentially present as a default metric (validators in the current sync committee, validators in the next sync committee).

Thanks for the feedback @ybstaked - this should be in a good state to action once we get to it now.

**Comment by ghost** [comment]
@rolfyone any update on this?

**Comment by rolfyone** [comment]
Nothing new at this stage - it's on the list of things to consider, but there's also a pressing need to catch up with spec changes...

**Comment by ghost** [comment]
@ajsutton @rolfyone any updates on this?  which release is this in?

**Comment by ghost** [comment]
This does not even have to be per pubkey, just need to know per VC process whether or not (binary) it has any validator keys that are currently in sync committee, so we can know whether or not to do any maintenance on the VC process (upgrades, etc.)

**Comment by rolfyone** [comment]
Sorry for the delay this got stuck behind spec changes, will look now at an initial count type solution for you.

**Comment by ghost** [comment]
Thanks @rolfyone for following up!  Prysm already implemented something in line with what you're thinking first pass here: https://github.com/prysmaticlabs/prysm/pull/11860

**Comment by rolfyone** [comment]
I called it a different thing :/ sorry

In line with the other metrics for the pending duties, i called it `validator_scheduled_sync_committee_duties_current`
It's actually the count of validators with duties technically, but i wanted to keep it consistent naming wise...

Also added a `validator_current_sync_committee_last_epoch` so that its easy to see the last epoch of the current committee, though it's a fairly simple thing to compute...
