### ISSUE TITLE
investigate 'no peers found on gossip topic'

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#6527]
```
Failed to publish attestations(s) for slot NNN because no peers were available on the required gossip topic
```

**Comment by rolfyone** [comment]
From Ben:
One hypothesis is that it is due to more nodes on the post-Merge network that are not running validators, making it harder to find the ones you want. Is increasing the number of peers likely to help (gut feel, yes)? If so, should we increase our default maxPeers?

**Comment by tbenr** [comment]
from a user in discord:
he is experiencing some peering issues during sync committee duties. I asked him enable TRACE on `SyncCommitteeMessageGossipManager` and here it is:

```
2022-12-06 09:55:51.001 INFO  - Slot Event  *** Slot: 5291377, Block: b9ced3d8073485d1b190027e46feebc4600c1f5e5e481cdb91f7bcb520b5f015, Justified: 165354, Finalized: 165353, Peers: 100
2022-12-06 09:56:00.236 INFO  - Validator   *** Published sync_signature     Count: 1, Slot: 5291378, Root: e09755625ddaf5ba409134d0129ca612feaf7e0402eca82d5a736ccc38a65101
2022-12-06 09:56:00.236 TRACE - Failed to publish sync committee message for slot 5291378
java.util.concurrent.CompletionException: io.libp2p.pubsub.NoPeersForOutboundMessageException: No peers for message topics [/eth2/4a26c58b/sync_committee_3/ssz_snappy] found
at java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.completeRelay(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: io.libp2p.pubsub.NoPeersForOutboundMessageException: No peers for message topics [/eth2/4a26c58b/sync_committee_3/ssz_snappy] found
at io.libp2p.pubsub.gossip.GossipRouter.broadcastOutbound(GossipRouter.kt:404) ~[jvm-libp2p-minimal-0.10.0-RELEASE.jar:?]
at io.libp2p.pubsub.AbstractRouter$publish$1.invoke(AbstractRouter.kt:72) ~[jvm-libp2p-minimal-0.10.0-RELEASE.jar:?]
at io.libp2p.pubsub.AbstractRouter$publish$1.invoke(AbstractRouter.kt:66) ~[jvm-libp2p-minimal-0.10.0-RELEASE.jar:?]
at io.libp2p.etc.types.AsyncExtKt.submitAsync$lambda-1(AsyncExt.kt:53) ~[jvm-libp2p-minimal-0.10.0-RELEASE.jar:?]
... 7 more
```

So the node struggle to find (or suddenly loses) sync committee peers

**Comment by tbenr** [comment]
Seems like during the entire sync committee period user had missed the majority of all messages but not all. So wasn't able to maintain good peers.
<img width="941" alt="image" src="https://user-images.githubusercontent.com/15999009/205902308-e2f222a0-eea9-4f12-83eb-de2fc3285aa4.png">

Attestations have been OK and steady peers to 100 (86 inbound, 14 outbound)

**Comment by stefa2k** [comment]
Some more metrics of the case @tbenr mentioned:
![image](https://user-images.githubusercontent.com/54934211/206426572-1824d73d-617e-4b01-b158-e777c0d8ecea.png)
![image](https://user-images.githubusercontent.com/54934211/206426630-9e42527c-1830-4035-b72e-59550bc03303.png)

**Comment by stefa2k** [comment]
As @tbenr requested:

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/54934211/206663559-b81e2463-56a8-4179-be06-f32aefe7bbcb.png">

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/54934211/206663771-f6bd36a7-2cdd-4204-b518-e746f911d57a.png">

**Comment by lucassaldanha** [comment]
Thanks, @stefa2k we are looking into this and will report back as soon as we can.

**Comment by ajsutton** [comment]
One possibly relevant detail with sync committees specifically, is that you only subscribe to those topics if you're scheduled to be in a sync committee (including in the next sync committee) or if you've set `--p2p-subscribe-all-subnets`. Whereas with attestation subnets, you subscribe to one subnet per validator you run.  So if you're running 64 or more validators you'll always be subscribed to all attestation subnets, but likely won't be subscribed to sync committee subnets.  In that case it would be worth enabling `--p2p-subscribe-all-subnets`.  Normally doing so would increase CPU and bandwidth significantly but with 64+ validators you're already paying that cost, so may as well stay subscribed to the sync committee subnets as well - then other peers will be seeking out your node to connect all the time and it _may_ help ensure you have peers on the subnet.  That said, when you are scheduled to be part of a sync committee, you'd subscribe to those topics and other sync committee members would start seeking you out then anyway so it's definitely not a guarantee that it would help.

The other possibility is that because post-merge there are a larger number of nodes not running validators and thus not subscribed to any subnets, it's gotten harder to ensure Teku has peers on all the different subnets. It may be that Teku's scoring system is flipping between prioritising different attestation and sync committee subnets trying to cover them all, but unable to within the peer limit. If that's the case, and there's sufficient bandwidth available, increasing the peer count may help. Worst case if every peer is only subscribed to one subnet then we'd need `(64 + 4) * 2 = 136` peers to have two peers on each subnet which is the default target.   I'd be tempted to try setting `--p2p-peer-upper-bound=150` to give a bit of wiggle room, but it's important to watch bandwidth availability - if the extra peers exceed the available bandwidth it would likely make the problem worse.

Fundamentally, I don't think there are any quick fixes here. We will likely wind up needing to adjust either Teku's defaults or it's peer selection strategy to adjust to the changes in the network post-merge, but we'll need to gather a fair bit of data on what effects that actually has before we can be confident if it actually helps or not.

**Comment by ajsutton** [comment]
ok, I'm not particularly convinced by the theory that it's harder to find peers on the required subnets.  Wrote a script to simulate a validator being in a sync committee and telling the beacon node to subscribe and Teku very quickly found 15-20 peers on each sync committee subnet, along with 20+ peers on each attestation subnet just with default options and a brand new node (with open ports).

What is weird though, when the `until_epoch` was reached and the beacon node was no longer being told it needed to be subscribed to the sync committee subnets, the number of peers on those subnets dropped to zero straight away. The node was at its upper peer bound at the time.  Send a subscription request again and within a slot it had 5 peers back on those subnets.

That does mean that if there's ever a point where the VC's call to `/eth/v1/validator/sync_committee_subscriptions` is lost either because it expires before the VC refreshes it successfully or the beacon node restarts after it was called, the number of peers on sync committee subnets would drop to zero very quickly and cause issues. I think that's because sync committees are no longer valuable and so those peers are replaced by ones subscribed to more attestation subnets quickly which isn't a bad thing.
The Teku VC will subscribe to subnets until the end of the sync committee period so if the beacon node doesn't restart, getting that call once should be enough for the entire sync committee period. However, it only makes the call once per sync committee period unless the VC is restarted. That's not frequent enough and makes it pretty easy for the beacon node to wind up restarting and have the subscription be lost.
Also if the subscription request failed, it would log an error to the log file, but not to the console which could easily be missed.

**Comment by ajsutton** [comment]
Except none of that applies to attestations - only sync committees, so it doesn't explain why we sometimes see no peers on attestation subnets.  Possibly there's multiple issues here.

**Comment by alepacheco** [comment]
I was having this issue with 500 peers and subscribing to all topics

**Comment by ajsutton** [comment]
> I was having this issue with 500 peers and subscribing to all topics

You will have almost certainly overloaded your node's ability to service all those peers quickly enough and hit the limits of your network causing peers to downscore and unsubscribe from you which then causes this problem.  I'd suggest reducing the peer limit to at most 150 and not subscribing to all topics as a starting point. There could well be other factors involved but being unable to keep up with the traffic will pretty much guarantee you get this failure.

**Comment by lucassaldanha** [comment]
@stefa2k have you had a chance to update your config to use `--p2p-subscribe-all-subnets`? We might need to wait until your validators are chosen for a sync committee but it would be worth a try.

**Comment by stefa2k** [comment]
> @stefa2k have you had a chance to update your config to use `--p2p-subscribe-all-subnets`? We might need to wait until your validators are chosen for a sync committee but it would be worth a try.

No change to Teku's behaviour with @ajsutton 's suggestions.

**Comment by tbenr** [comment]
User reported the issue has been fixed by not using the following CLI parameters anymore:
--p2p-port
--p2p-advertised-ip
--p2p-advertised-port

So letting teku be on its default ports and autodetect its external ip and port.

closing the issue.
