### ISSUE TITLE
Implement getAttestationRewards API method

### ISSUE THREAD

**Issue by lucassaldanha** [Consensys-Incorporated/teku#6703]
**Description**

This method eetrieves attestation reward info for validators specified by array of public keys or validator index. If no array is provided, return reward info for every validator.

Reference: [Beacon API spec](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Rewards/getAttestationsRewards)

**Tasks**
- Implement API interface based on spec (returning some mock data)
- Implement real logic of fetching/calculating sync committee rewards
- Changelog update

**Comment by rolfyone** [comment]
I *think* this might be complicated...
As far as I understand this is computed on epoch transition. the reason thats going to be important is because in several modes we don't actually have a facility to get old states (prune), so we'd only be able to compute this for non finalized epochs, or similar...
epoch transition is also changed a bit, so make sure you check all the forks to make sure things don't change...

**Comment by duktig666** [comment]
Whether it contains punishment information？

Based on this, alarm and monitoring can be performed.
