### ISSUE TITLE
Top-up blocks voluntary exit?

### ISSUE THREAD

**Issue by heeckhau** [Consensys-Incorporated/teku#6803]
### Description and steps to Reproduce (Bug)
I have set up a few validators on zhejiang and the voluntary exit does not work for validators where I did a "top up"

Note that the voluntary exit did work for a regular zhejiang validator I also started: https://zhejiang.beaconcha.in/validator/0x87093e5995aa89184ce9fd151ebc1a787804c54ecd62d22ec8879af7c54c02e95af1550351633a127d18146c203e8239

For the other validator, I did some extra topups with https://zhejiang.launchpad.ethereum.org/en/top-up
This validator I can not exit. Whatever I try, the exit epoch remains on 18446744073709551615
https://zhejiang.beaconcha.in/validator/0xa743b1bcc41fa493a44a3c362a1f9a8699ffb35a2d6333bc04427b559cf44b2649d9df79bcec49e746f9345085999a07#deposits
```
Loading configuration...
Exits are going to be generated for validators:
98e2bf9
Epoch: 1381

These validators won't be able to be re-activated once this operation is complete.
Are you sure you wish to continue (yes/no)?
yes
Exit for validator 98e2bf9 submitted.
```

I tried the same with another validator that was topped-up. Same result.

<img width="979" alt="image" src="https://user-images.githubusercontent.com/735288/218102739-d96a5c9b-838a-4c8f-9f57-3a196e8427ff.png">

⚠️ **Update** ⚠️ : when I tried again a day later, it just worked. Does a top-up reset a timer?

https://zhejiang.beaconcha.in/validator/0x98e2bf94fe3db418b3d7aa47930a672e1ad35d971928c198d997b31276d654867fd91f1aa66a71ce0ee3ff2d39175a6a
<img width="905" alt="image" src="https://user-images.githubusercontent.com/735288/218102643-66074035-043d-4b9d-be27-596f418ea2f0.png">

-------

**Expected behavior:**

A voluntary exit should work or an error message should be shown.

**Actual behavior:** 

The exit command is accepted, but the exit epoch is not changed

### Versions (Add all that apply)
* Software version: teku/v23.1.0+10-gac10368/osx-aarch_64/-eclipseadoptium-openjdk64bitservervm-java-17
* Java version: OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode)
* OS Name & Version: macOS Ventura 13.1

**Comment by benjaminion** [comment]
I am reasonably certain that this is unrelated to the top-up. There is no logic in the spec or in Teku to reset any timer on a top-up - the top-up amount just gets added to the beacon chain balance.

I suspect something like this:
  - Initial deposit of 32 ETH processed at epoch 434
  - Validator becomes active at epoch 996
  - Top-up deposit of 1 ETH processed at epoch 1128
  - You try to exit the validator soonish after this, but you are not allowed to initiate a voluntary exit until [activation + 256 epochs](https://eth2book.info/bellatrix/part3/transition/block/#voluntary-exits) (I.e. 27 hours after activation).
  - After epoch 1252 you are able to exit

Is that a possibility?

**Comment by heeckhau** [comment]
@benjaminion I had 2 validators (61486 and 61487) that were deposited in the same epoch (434). One with with a top-up (61486) and one without (61487). So both had the same activation epoch too (561).

That is why I suspect that the top-up changes something. If this is not in the protocol rules, my hypothesis is that Teku uses the last deposit epoch instead of the activation epoch.

In any case Teku gives no error, and does not change the exit epoch.

This was the output from Teku API, when I tried to figure out what was going wrong:
```
{
  "execution_optimistic": false,
  "finalized": false,
  "data": {
    "index": "61486",
    "balance": "32000038051",
    "status": "active_ongoing",
    "validator": {
      "pubkey": "0x98e2bf94fe3db418b3d7aa47930a672e1ad35d971928c198d997b31276d654867fd91f1aa66a71ce0ee3ff2d39175a6a",
      "withdrawal_credentials": "0x0100000000000000000000009b18e9e9aa3dd35100b385b7035c0b1e44afca14",
      "effective_balance": "32000000000",
      "slashed": false,
      "activation_eligibility_epoch": "435",
      "activation_epoch": "561",
      "exit_epoch": "18446744073709551615",
      "withdrawable_epoch": "18446744073709551615"
    }
  }
}
```
When I ran the voluntary exit a second time, I got:
```
Loading configuration...
Exits are going to be generated for validators:
98e2bf9
Epoch: 1582

These validators won't be able to be re-activated once this operation is complete.
Are you sure you wish to continue (yes/no)?
yes
Exit is not the first one for validator 61486.
```
So Teku was aware that an exit was triggered, without actually exiting.

I hope this isn't too confusing, just trying to help and experimenting with corner cases.

**Comment by benjaminion** [comment]
Noted, and I'll let one of my colleagues take a look. But I still think that the top-up is unrelated, there is no mechanism for it to affect voluntary exits at all.

All that Teku does when you talk to its API is forward your voluntary exit to the network. After that it's up to all the clients on the network to keep it in their message pools and eventually to include the voluntary exit in a block. Submitting the VE to Teku does not in itself action the exit - once it's sent to the network it's out of Teku's hands (unless you happen to publish a block shortly afterwards). There can be arbitrary delays and losses in this process - since voluntary exits are not consensus critical (and are uncompensated) clients tend not to prioritise them.

**Comment by heeckhau** [comment]
FYI: I just tried  to exit again, this time with Lighthouse, and that worked.
Let me know if you need more information.

**Comment by rolfyone** [comment]
Ok so basically submitting an exit goes into a pool, and that is published to the network so that any potential block builder should be able to pick up and run with the exit.
It's not guaranteed and there's no incentive to include it so it's a bit less reliable than some of the other messages.

At that point it's submitted.
If a subsequent message is posted to the same BN, you get the `Exit is not the first one for validator xxx` message, this basically is saying it's already in the pool...

If the exit is already in the pool, we can probably improve the logic a little, as unless you're a block builder your pool isn't consumed, so it's a little difficult to reason about the logic.
Given the first one went through, it's likely we're publishing correctly, or you built the block that included it. The second one is similar to a corner case with BLS withdrawals I've been thinking about, where it's actually been submitted to the network, but it needs to hit a block builder or the message won't be processed, and it's hard to resubmit.

There's a number of improvements we could potentially make to improve the story in cases like this, I think now that we're getting to withdrawals being active, people are more likely to submit voluntary exits more often, so it's probably worth some improvements in this area.

I guess the todo list is:
 - quick confirmation that we actually do broadcast voluntary exits for sanity, it's likely already included in acceptance tests.
 - contemplate allowing a re-broadcast at the very least for exits that are already in the queue after a period - this could be automated (preferably) or manual after sufficient time has passed that it won't be considered a duplicate message. This would apply to locally submitted exits, and be broadly applicable to bls change messages.

Hopefully this isn't in the 'way too much information' bucket, but at the very least it'll be useful for myself or the team when we can look at it more closely.

@heeckhau if you're able to see if your BN created the block from the first exit that may be contextually relevant but I think we're equally able to move forward and progress this issue without that information, so I wouldn't spend too long on it if you can't find it straight away...

**Comment by heeckhau** [comment]
@rolfyone Thanks for looking into this. So it was a coincidence that it did not work for one of the validators, and is unrelated to the top-ups.

Can you be a bit more specific on what you'd like me to look into? My BN did not propose any blocks.

**Comment by rolfyone** [comment]
The fact that you didn't propose any blocks actually answers my question perfectly :)

**Comment by heeckhau** [comment]
@rolfyone Awesome. Thanks for you great work 👍

**Comment by rolfyone** [comment]
Welcome. I think it's not incorrect to reject as it had, but now that we can determine local versus remote, we do have a facility to automatically re-broadcast while we're aware of that local submission so this should ensure your request is at least on the network!

Hopefully it's a good middle ground, I believe it's basically what's needed in the case above, where things might get lost and stuck in local cache forever effectively...

The only other gap in real terms is we'd lose that local submission on restart, but I think that's probably ok for now, as you can submit a new request and add it to the local cache again... Perhaps one day it's worth persisting these local entries...
