### ISSUE TITLE
Insane amount of data written during synchronisation

### ISSUE THREAD

**Issue by RogerHKW** [Consensys-Incorporated/teku#7238]
Basically, when launching a new node from scratch, Teku wears out 1 TB of SSD for 6 GB of effective data stored. Maybe is there something to optimize in the software when it rewrites 166× everything ?

After the synchronisation, the problem stops.

I noticed this problem with `smartctl` on my Samsung Evo 970 Plus last week (31 TB written for 1 TB of data stored after synchronisation with Mainnet) but I was not sure whether it was a bug of smartctl or Besu or the controller of the SSD. Since then, I separated Teku and Besu on two different SSDs. I'm synchronizing with Görli since yesterday and today I notice that the new SSD devoted to Teku (Samsung PM961) stores 6GB more data but the _Data units written_ field of `smartctl` gained almost 1 TB. `iostat` confirms that 1TB has been written since yesterday on this disk used exclusively by Teku.

No swap. Teku runs with _-Xmx22G_. There is always between 10 and 17 GB of RAM free (so used by Linux to cache files).

**Comment by yorickdowne** [comment]
Is this a checkpoint sync?

**Comment by RogerHKW** [comment]
I tried both and it seems to write less with a checkpoint : about ×20 instead of ×166.

**Comment by yorickdowne** [comment]
Given that checkpoint sync is the preferred, safer, recommended way, I’m not sure this is a thing that needs to be fixed.

**Comment by RogerHKW** [comment]
There is malfunction in the code which rewrites every byte at least 20 times within two days and that's fine? Is it how serious the developers of a software managing tens of billions dollars are?

You are kidding right? If not, it might also explain why Teku (and Besu) use way more RAM than specified with `-Xmx`. What's next? 99% of the CPU consistently and it's fine as long it's not 100?

**Comment by lucassaldanha** [comment]
@RogerHKW I appreciate the feedback and the details from your investigation and reporting this to the team. We will take a look into it.

As a separate note, please keep in mind that we have a [code of conduct](https://github.com/ConsenSys/teku/blob/master/CODE-OF-CONDUCT.md) for our projects and it applies to any of the developers that contribute to the project and people participating in the community (Discord, GH Issues, etc.). We do ask you to be mindful of your tone and the way you talk to our developers and members of the community. We won't tolerate abusive behaviour.

**Comment by yorickdowne** [comment]
Chillax @RogerHKW . I am not a Teku dev btw. I am expressing how it impacts me as a user. Optimization is a rabbit hole without a bottom, and squeezing the last half TB of writes out of a process may not be a good use of dev time.

Couple data points @lucassaldanha . Two servers running since mid-2021, one Lighthouse and one Teku. Total TB written for both.

Lighthouse/Erigon: 291 TB
Teku/Besu: 319 TB

That's within "margin of error", particularly given that these figures include the EL and there have been a few resyncs here and there. 

I doubt there's actually a "there", here. Teku is likely as optimized as it can be, or as it is reasonable to be. Ethereum as a whole writes almost nothing. I've been up for two years on those and haven't meaningfully scratched the durability of the drives.
