### ISSUE TITLE
Full task queue p2p-async-scheduler-0

### ISSUE THREAD

**Issue by Archethect** [Consensys-Incorporated/teku#7306]
I am getting the following error on Teku v23.5.0.

```shell
Unexpected rejected execution due to full task queue in p2p-async-scheduler-0
``` 

Just before this error I get lots of this warnings

```shell 
 WARN  - Discarding gossip message for topic /eth2/824be431/beacon_aggregate_and_proof/ssz_snappy because the signature verification queue is full
```

This results in Teku falling out of sync and not attesting anymore. 
I am running this setup on Dappnode if it might be of any help.

**Comment by tbenr** [comment]
Hello @Archethect,
Most probably your node started struggling due to low resources (probably memory) which caused gossip queues to fill up and after a while your node fell out of sync and stopped attesting.

Can you share how much ram you are giving to teku? (the -Xmx parameter), teku now prints some of these info in the logs at startup.
Which type of CPU do you have? How many dapps are you running in dappnode?

Latest 23.6.0 is more resilient when under pressure.

**Comment by tbenr** [comment]
@julien-marchand 
Your issue might be related to low memory configuration. Latest dappnode teku package has been updated to allow memory configuration: https://github.com/dappnode/DAppNodePackage-teku/pull/68
It will now configured to run with 6gb by default (previous config was 4g).

I recommend you to update.

In the meantime I'm going to close the issue. Feel free to reopen it if you still have more details to report.
