### ISSUE TITLE
Teku VC asks Web3Signer to sign for inactive validators

### ISSUE THREAD

**Issue by gg718** [Consensys-Incorporated/teku#7382]
### Description
Teku VC asks Web3Signer to sign for inactive validators. Let's say I load 10 keys into Teku; 5 that have received 32 ETH and become active, and another 5 that have yet to receive 32 ETH, I see errors in the logs for Web3Signer like:

> `2023-07-24 09:42:15.029+00:00 | vert.x-eventloop-thread-0 | ERROR | LogErrorHandler | Failed request: http://web3signer:9000/api/v1/eth2/sign/0xa60345b3482359171a7aae637b93fcd9245126a07bc58717cbc55502a197bf838e10adb6825f52420994c9f29c913b7d`

Other validator clients correctly recognize the validator is not active and do not ask Web3Signer to sign.

### Steps to Reproduce (Bug)

**Expected behavior:**

Teku should not ask Web3Signer to sign for inactive keys.

**Actual behavior:**

Teku asks Web3Signer to sign for inactive keys.

**Frequency:**

Every epoch.

### Versions (Add all that apply)

* Teku v23.6.2
* Web3Signer v23.6.0

**Comment by rolfyone** [comment]
Thanks for raising.
When you say 'constantly', is it asking every slot? Once an epoch?
It sounds very much like attempting to determine if an attester is an aggregator...

I'll put the 'bug' flag on this one, but this extra information would be useful if it's easy to get at, otherwise we'll be trying it anyway so we'll find out soon enough...

**Comment by gg718** [comment]
Apologies, opened this issue a little too hastily.

It's every epoch – description updated.

**Comment by rolfyone** [comment]
Ok great, I suspect it's likely trying to decide which validators are aggregators for the epoch.
The VC likely isn't fully aware of each validators status, but I think we can probably do something to alleviate this.
Thanks for the extra context, it's helpful :)

**Comment by ghost** [comment]
We are also noticing this and same behavior for exited validators and it causes in our case to miss a lot of attestations where there are inactive or exited keys.

**Comment by rolfyone** [comment]
> We are also noticing this and same behavior for exited validators and it causes in our case to miss a lot of attestations where there are inactive or exited keys.

Signing a message causes missed attestations?
Are you talking about signing contention? Or reporting in the summary line? I'd be interested to know a little more on this if possible...

**Comment by ghost** [comment]
@rolfyone unfortunately no errors in either Teku BN or Teku VC logs, but the performance of our Teku validator has been considerably worse and I think it's due to this issue.

- https://beaconcha.in/validator/292955#attestations

**Comment by ghost** [comment]
Just fyi, we are planning to prune out all inactive and exited keys from our keymanager and see if that improves Teku performance, otherwise, we'll fall back to Prysm VC + Prysm BN 😞

**Comment by zilm13** [comment]
@ybstaked we are looking into this, I'm trying to reproduce the bug. Please, get back to us with the results of the pruning.
If pruning helps, handling of exited and inactive validators is clearly the issue, otherwise we should look into more details as the reason of bad validator performance is somewhere else for your nodes. We'd be happy to help find out it.

**Comment by ghost** [comment]
@zilm13 thanks, we just pruned all inactive keys from one VC process  (still has keys with `withdrawal_done` status).  Now, monitoring the remaining 1 active key in the wallet: https://beaconcha.in/validator/17998#attestations, along with another key in another wallet that's also impacted by it: https://beaconcha.in/validator/292955#attestations

**Comment by ghost** [comment]
Again, no errors in Teku VC or Teku BN and performance doesn't seem to have improved in the last 2 hours, will wait overnight and if still no improvement, will switch back to Prysm.

**Comment by rolfyone** [comment]
Are there large numbers of `regeneration of state` messages on the BN? This can cause issues close to epoch transition and is something we've refactored in the release that's being made currently - basically it was regenerating epoch states, and i've changed caching to remove that specific cause of slow down... a symptom is those messages.
While I was testing this seemed to be a problem that could occur even with huge heap space, just due to how the old state caching was functioning, and was fairly regular (every epoch or so), and because of where it occurred it could potentially cause slowdown outside of how keys are managed...

**Comment by ghost** [comment]
This validator's performance looks better: https://beaconcha.in/validator/17998#attestations

Before: 99 total keys: 1 active, 32 exited, 66 inactive
After: 33 total keys: 1 active, 32 exited.

**Comment by ghost** [comment]
> Are there large numbers of `regeneration of state` messages on the BN? This can cause issues close to epoch transition and is something we've refactored in the release that's being made currently - basically it was regenerating epoch states, and i've changed caching to remove that specific cause of slow down... a symptom is those messages. While I was testing this seemed to be a problem that could occur even with huge heap space, just due to how the old state caching was functioning, and was fairly regular (every epoch or so), and because of where it occurred it could potentially cause slowdown outside of how keys are managed...

There is no "regeneration" or "error" logs in either Teku BNs or Teku VCs.  Only "warning" logs is:  
```
[cl-teku-mainnet-2-0] 12:00:27.403 WARN  - Late Block Import *** Block: ad8c030ee77d5c06517987ac83d51b7428dbba0dc624b08542649302b60fd68e (7020000) proposer 760069 arrival 4158ms, pre-state_retrieved +5ms, processed +191ms, execution_payload_result_received +38ms, begin_importing +0ms, transaction_prepared +0ms, transaction_committed +0ms, completed +11ms
```

**Comment by rolfyone** [comment]
> This validator's performance looks better: https://beaconcha.in/validator/17998#attestations
> 
> Before: 99 total keys: 1 active, 32 exited, 66 inactive After: 33 total keys: 1 active, 32 exited.

ok that's really good to know, thanks! We've got someone looking at this problem, so this is useful context.

**Comment by ghost** [comment]
Actually part of the fix seems like us switching to another beacon node, but not sure why the "broken Teku BN" was having issues, there's no useful error logs.
