### ISSUE TITLE
Change the default storage mode to minimal

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#7392]
This will be easiest in a couple of stages.

For this release we'll create a file in the database folder that stores the mode that the database was opened in. This will allow us to refer to that in future as 'current' mode the database is in.

Future release will change from 'prune' data-storage-mode as default, probably to be null.

Then we'll need logic to reconcile if this is not set, use the one stored to file etc.

Once we've got that logic in place, we'll be able to change the 'default' to be minimal, and existing databases with prune as default will continue to load that from disk and retain there data.

First PR for persisting the current storage mode is #7391.

**Comment by benjaminion** [comment]
The efficacy of this approach depends on people not skipping the first upgrade. It would be more robust do to a single-stage change if possible.

Basically:

  - If the node has an existing database, default to `prune` and then look at their configuration to see if there is an override. I.e. no change in behaviour for existing DBs.
  - If the node does not have an existing DB, default to `minimal` unless overridden by the node's configuration.

Then keep a record of the decision so that in the second case it doesn't flip back to `prune` at the next restart.

The goal is not to delete anyone's data without their express consent. Imo deleting data when it's wanted is worse behaviour than keeping data when it's not wanted, but I'm open to persuasion on this.
