### ISSUE TITLE
Cannot create attestation for future slot

### ISSUE THREAD

**Issue by nolanv-be** [Consensys-Incorporated/teku#7402]
### Description
My consensus node stop working for about one hour due to "Cannot create attestation for future slot" then start syncing again.
![Screenshot from 2023-07-31 09-31-57](https://github.com/Consensys/teku/assets/109871781/eecb50da-36a0-47ec-9a5c-dbf53a7247d5)
![Screenshot from 2023-07-31 10-01-22](https://github.com/Consensys/teku/assets/109871781/878fc10e-0943-4c4b-b92e-1bd48643f200)
![Screenshot from 2023-07-31 10-03-53](https://github.com/Consensys/teku/assets/109871781/70bc327c-6454-4b7d-8251-9ac36e5aac3c)

### Steps to Reproduce (Bug)
Run Teku consensus node with Besu.

**Expected behavior:** Run without any issue

**Actual behavior:** Stop posting attestation and restart syncing 

**Frequency:** Only one time

### Versions 
* Software version: Teku 23.6.2 with Besu 23.4.4
* Java version: 17.0.7
* OS Name & Version: Ubuntu 22.04
* Docker Version: Barebone

**Comment by rolfyone** [comment]
Thanks for raising.
This is typically a sign of struggle - what `-Xmx` setting do you have with teku? This is the heap space used, typically we're seeing people on less than 5g (would look like `-Xmx5g`) struggle on mainnet currently...

**Comment by rolfyone** [comment]
I had a closer look at your screenshots and it does look like you were on 5g heap at the time, and your peer count dropped to 0 (or close to) for a period during full Garbage collection...
This looks very similar to a historical sync issue we had during non finality a couple of releases back ,but shouldn't be present in the current (23.6.2)
Can I confirm which teku image you're using? It really does look very similar to something fixed in 23.5.0, but its definitely possible that some other scenario looks similar on the dash...

Would it be possible to see the beacon node logs prior to the spike in garbage collection just after 8pm on the metrics board? Specifically warnings / errors / exceptions are of interest, probably in the period from 8pm to maybe 5 past...

Related to this, though not strictly, we've started a release that would address some memory consumption etc which might alleviate things, though it'd be interesting to pursue and see if there's something else involved here.

**Comment by nolanv-be** [comment]
Indead I use the Xmx5g flag but I confirm that I use the version 23.6.2.
![image](https://github.com/Consensys/teku/assets/109871781/47163770-15cf-48ed-83de-62a6fee56d1b)

Log files => https://gist.github.com/d-banana/33492faf6370d81017a658c93643b177

**Comment by rolfyone** [comment]
Particularly during the heavy garbage collection during the outage period we lost a lot of states and kept having to regenerate.
This problem should be resolved in 23.8.0 using the epoch-states cache, which is on by default.

It greatly reduces the states in memory, and if you're accessing a lot of non final states it might be worth increasing that cache, which is noted in release notes, but by default it should be good for most users. 

Are you happy to update to 23.8.0?

**Comment by rolfyone** [comment]
Hey there, did 23.8.0 fix your reported problem?

**Comment by nolanv-be** [comment]
No more issues since the update and the addition of extra ram memory.
