### ISSUE TITLE
validator_duties_performed{result="failed"} metric does not report a failure when it actually fails onchain

### ISSUE THREAD

**Issue by ghost** [Consensys-Incorporated/teku#7410]
Possibly related to #7382, maybe it doesn't report when signing fails due to inactive/exit keys.

**Comment by rolfyone** [comment]
Thanks for raising.

I think that metric is specifically relating to when the process of creating a specific duty failed...

Are you looking for something like the Attestation performance data to be available via metrics, where you'd be able to see included count etc?

#7382 should be somewhat unrelated to that 'failed', but I haven't looked closely. It sounds very much like the process we go through to determine if a validator is due to aggregate, which we need to sign a message to be able to determine due to how the process was designed...
The gap in that ticket (heavy assumption) is likely that we're signing for all keys we've loaded, rather than just actual active keys, because we're less aware than we could be about the state of the key we've been given...

**Comment by ghost** [comment]
What we are looking for is a way to measure and alert on failed attestations, i.e.: if no successful attestations after 20 minutes.

**Comment by StefanBratanov** [comment]
Hi @ybstaked possibly following metrics can help. They are BN ones and are per epoch. Basically how they work is based on your subscribed attestation subnets, it determines how many attestations were expected from your validators, and then it determines how many were produced by your validators and included on the chain.


```
$ curl localhost:8008/metrics | grep -E validator_performance.*attestations

# HELP validator_performance_produced_attestations Number of produced attestations
# TYPE validator_performance_produced_attestations gauge
validator_performance_produced_attestations 2.0
# HELP validator_performance_expected_attestations Number of expected attestations
# TYPE validator_performance_expected_attestations gauge
validator_performance_expected_attestations 2.0
# HELP validator_performance_included_attestations Number of included attestations
# TYPE validator_performance_included_attestations gauge
validator_performance_included_attestations 2.0
```

We use it in our Teku detailed dashboard:

![image](https://github.com/Consensys/teku/assets/14827647/301bb3b2-8dac-4aa3-a478-8611a27c3f35)

**Comment by rolfyone** [comment]
Hey @ybstaked - any thoughts on Stefans suggestion? It does offer basically what you're looking for...

**Comment by tbenr** [comment]
@ybstaked we are going to close this. Feel free to reopen it if you have more info to share.
