### ISSUE TITLE
Option for specify network in voluntary-exit sub-command

### ISSUE THREAD

**Issue by heejin-github** [Consensys-Incorporated/teku#7489]
### Description
With Lighthouse BN, Teku VC cannot execute voluntary-exit with following error.
Lighthouse BN didn't provide `MAX_REQUEST_BLOCKS`. but, it seems similar with #7397 .
so, trying to find specify network name but, voluntary-exit sub-command didn't have it.

### Steps to Reproduce (Bug)
- Teku validator client connected with Lighthouse BN.
- activate validator 
- try voluntary-exit with below docker command.
```sh
#!/bin/bash

docker run -it --name teku_validator_exit \
	--network host \
	-v <PATH_FOR_VALIDATOR_KEYS>:/root/vc/teku/validator_keys \
	consensys/teku:23.9.0 \
        voluntary-exit \
        --beacon-node-api-endpoint=<LIGHTHOUSE_BEACON_API_ENDPOINT> \
        --confirmation-enabled=false \
        --validator-keys="/root/vc/teku/validator_keys/<EXIT_VALIDATOR_KEYSTORE>:/root/vc/teku/validator_keys/<KEYSTORE_PASSWORD>" 
```
- run log
```sh
Loading configuration...
Failed to retrieve network spec from beacon node endpoint '<LIGHTHOUSE_BEACON_API_ENDPOINT>'.
Details: Missing value for spec constant 'MAX_REQUEST_BLOCKS'
```

Lighthouse BN didn't provide `MAX_REQUEST_BLOCKS`. so, trying to specify network. (refer to the #7397 )
but, there's no options for `network` in `voluntary-exit` sub-command.
```
Unknown options: '--network', 'goerli'

To display full help:
teku [COMMAND] --help
```

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [How regularly does it occur?]

### Versions (Add all that apply)
* Software version: [`23.9.0`]
* Java version: [`java -version`]
* OS Name & Version: [`Ubuntu 22.04.3 LTS`]
* Docker Version: [`24.0.5, build ced0996`]
* Cloud VM, type, size: [Baremetal]

**Comment by rolfyone** [comment]
Thanks for raising.
We will have a look at the lighthouse interop with some of the constant values moving around in the spec recently, which will be the reason that teku couldn't read the spec from the BN.

In regards to the command to execute the exit, it's definitely possible, and very similar to where you got.
Because of the library we use for command processing, its a bit confusing, but `--network` is an option on the teku command, so the voluntary-exit ends up looking like:
```
teku --network goerli voluntary-exit \
--beacon-node-api-endpoint=<LIGHTHOUSE_BEACON_API_ENDPOINT> \
        --confirmation-enabled=false \
        --validator-keys="/root/vc/teku/validator_keys/<EXIT_VALIDATOR_KEYSTORE>:/root/vc/teku/validator_keys/<KEYSTORE_PASSWORD>" 
```

This will then read the network configuration from the built-in package. 

Hopefully this gets you going! We'll look at the constants that made this required, it's much less clunky when it can be read from the BN.

**Comment by heejin-github** [comment]
@rolfyone Thanks for your kind!
Unfortunately, I tried with `--network` option on the teku command. but, it seems still trying to read from the BN.
even if I added `--network goerli` option, still failed to retrieve network spec from BN as below log.


```sh
$ cat exit-validator.sh
#!/bin/bash

docker run -it --name teku_validator_exit \
	--network host \
	-v <PATH_FOR_VALIDATOR_KEYS>:/root/vc/teku/validator_keys \
	consensys/teku:23.9.0 \
        --network goerli \
        voluntary-exit \
        --beacon-node-api-endpoint=<LIGHTHOUSE_BEACON_API_ENDPOINT> \
        --confirmation-enabled=false \
        --validator-keys="/root/vc/teku/validator_keys/<EXIT_VALIDATOR_KEYSTORE>:/root/vc/teku/validator_keys/<KEYSTORE_PASSWORD>" 
```

- log
```
$ bash exit-validator.sh
Loading configuration...
Failed to retrieve network spec from beacon node endpoint 'http://localhost:3600/'.
Details: Missing value for spec constant 'MAX_REQUEST_BLOCKS'

```

**Comment by rolfyone** [comment]
Oh that's annoying! I'll have to get that fixed, we shouldn't be reading from the spec again if we already have it available!
I'll raise a separate ticket for the interop, and this ticket we can resolve the network issue at least... If we treat them separately it'll be easier to move through the process :)

**Comment by rolfyone** [comment]
We've implemented an option to generate an exit in the validator-api, but it's a bit of setup involved...

https://docs.teku.consensys.net/reference/rest#enable-the-validator-client-api

Because it's authenticated etc, its a lot less simple to use, and that api only generates the exit, it won't publish it to the BN...
https://ethereum.github.io/keymanager-APIs/?urls.primaryName=dev#/Voluntary%20Exit/signVoluntaryExit
If you went that way, you'd then take the generated exit and submit it on a beacon-api...

If it's not super urgent to generate your exit, it might be easier to hold off, or use another tool like ethdo
https://github.com/wealdtech/ethdo/blob/master/docs/usage.md#exit-comands

Hopefully this gives a couple of options, apologies that the workaround didn't work!

**Comment by rolfyone** [comment]
a couple of random notes.
I'm changing to add --network option to the voluntary-exit command, so that you can manually specify --network when using voluntary exit, rather than using the beacon-endpoint.

behaviours:
 - if --config-file is specified on the parent command, and that has network set, this would flow down into the voluntary-exit command - and so would the keys, so if you do use this option, be careful as it would attempt to exit all the keys found in the configuration file. ` teku --config-file teku.yml voluntary-exit .......`
 - if you need to specify network, it will work as part of the voluntary-exit command, not outside the voluntary-exit command. This is because outside of voluntary exit we actually default this field to 'mainnet' so its unique behaviour to not default this field. `teku voluntary-exit --network mainnet .......`
 - without config-file or network explicitly set, we will continue to attempt to load from the beacon-api, which continues to default to http://localhost:5051, and obviously if that fails as described in ticket, we can't continue without intervention.

Ideally most of the time the remote config loads, because this is the same config you're going to attempt to submit the exit against, so ideally we can leverage that to reduce scope for errors.

I believe there's still more cleanup to do on this command, but i've at least extended it to allow network to be set. The complexity would come in if for some reason the local configuration wasn't in line with the BN configuration, but this should be unusual unless you're a dev.
