### ISSUE TITLE
web3signer remote registration, unable to delete keys

### ISSUE THREAD

**Issue by yorickdowne** [Consensys-Incorporated/teku#7503]
### Description

I am starting Teku with `--validators-external-signer-url http://web3signer:9000 --validators-external-signer-public-keys external-signer` so that keys loaded into web3signer come in on startup, and users do not need to manually register these keys if they switched consensus layer clients.

I also register the keys with Teku when loading them into web3signer, so that they are immediately live.

This creates an issue when trying to delete the remote registration.

- Load keys into web3signer and register as remote key with Teku, via keymanager API
- Restart Teku, it loads keys from the web3signer URL
- Attempt to delete keys and delete remote registration, this fails. Likely because the remote registration was created upon startup from the web3signer URL:

```
Remote registration for validator 0x8fe5b2c0ce05093e3c6bbe1db0363b542709dfb4b8433e13ce23f1e7a7d840cc09a2ad97c5fd03980988df48bbe840f2 was found but an error was encountered trying to delete it:
Cannot remove read-only validator
```

- Restart Teku again. It would now not get a key list from web3signer, but it still sees the remote registration that was created on key import:

```
No keys loaded into web3signer
Remote keys registered with consensus
0x9642bbe4853617cb603863e4c90398304724ad192c4d6337fded814a6ab0c04ede5dafd9d9148ae4c0d1a51354a17687 http://web3signer:9000
0x8fe5b2c0ce05093e3c6bbe1db0363b542709dfb4b8433e13ce23f1e7a7d840cc09a2ad97c5fd03980988df48bbe840f2 http://web3signer:9000
```

This is worrisome for users: They deleted keys but still see the registration. One user came to me with slashing fears.

**Expected behavior:**

I'd like to be able to remove registrations that I created, or that were created from web3signer when Teku starts, so key deletion also removes the remote registration from Teku.

I'd like to keep the behavior where keys are immediately live on import, which is why they are imported into web3signer and then registered with Teku, both via keymanager API.

**Frequency:**

Reproducible

### Versions (Add all that apply)
* Software version: `teku/v23.9.0/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17`

**Comment by rolfyone** [comment]
any Key that is added outside of keymanager is 'read only', because each startup it's going to load from the configuration and we have no control to remove it.
It can be very confusing attempting to load keys via config AND via keymanager, so my initial suggestion would be avoiding attempting to do that.

Using `--validators-external-signer-public-keys external-signer` basically tells teku to load the key via configuration, and I'd expect that any loaded via keymanager after that should actually fail to import given that they're present in the signer list already, are you saying you can add via config AND keymanager?

I'll play around, but my initial assumption is avoid specifying `--validators-external-signer-public-keys external-signer`, as this loads via configuration (meaning they're read only), and you're wanting to manage keys with key-manager by the sounds.

**Comment by yorickdowne** [comment]
I’m trying to have my cake and eat it, too.

When users load new keys into web3signer I’d like those to be live right away, so hence the use of keymanager. Is there another way, like sending a signal?

When users switch clients, I’d like Teku to pick up web3signer keys without the need to use keymanager, hence the use of the command line parameter to load public keys.

**Comment by tbenr** [comment]
@yorickdowne you can try https://docs.teku.consensys.net/how-to/load-validators-without-restarting
I don't know if it is add-only

**Comment by rolfyone** [comment]
I had a play today and was able to use `kill -s HUP <TEKU_PID>` to load more validators owned by a web3signer.

Is this what we were looking to understand from this ticket ultimately?

Basically my process:

 - loaded a set of keys to web3signer (about 130) - used my interop-keys.sh script

 - start teku as minimal, with 
 ```
validators-external-signer-url: http://localhost:19000
validators-external-signer-public-keys: external-signer
```
saw 130 keys loaded...

 - load more keys into web3signer, send hup, get notified `Loading 126 validator keys...`
 - normal prompts about slashing protection data etc, 
 - issue another HUP, get `loading 0 validator keys`, because there were no new keys to load.
 
I'm not sure removing would be so easy, as this process does seem additive, just putting it out there, in case that's a problem..

**Comment by rolfyone** [comment]
We actually have a test explicitly showing that we don't remove keys from an external signer, so if key a is there on load, and only b is there on reload, you'd be attempting duties for (a,b)

I don't think this would be super hard to modify if it's helpful to remove the keys on HUP... probably a day or 2 of playing...

**Comment by rolfyone** [comment]
This is actually less simple than I was hoping, I might have to re-evaluate.

My use case:
 - start a network with 256 external validators
 - after a few epochs, remove them from the external signer
 - send HUP to teku (reloads) - still trying to perform duties (not great)
 - send keys to signer again  - successfully perform duties on teku with no hup (so the keys didnt get removed correctly)
 
I'm going to close that PR un-merged, as this won't be the change you're looking for giving that odd behaviour, we'll have to have a closer look at it all.

**Comment by yorickdowne** [comment]
@tbenr Thanks! I changed my code to not register web3signer keys via keymanager and instead use SIGHUP. Works well for adding keys!

@rolfyone Appreciate the effort! That's a doozy for sure.

**Comment by tbenr** [comment]
Going to close this. We will re-evaluate if there is actual need.
