### ISSUE TITLE
Custom network configs break unless GOSSIP_MAX_SIZE and others are defined

### ISSUE THREAD

**Issue by siladu** [Consensys-Incorporated/teku#7555]
Following https://github.com/Consensys/teku/issues/7179 (spec change: https://github.com/ethereum/consensus-specs/pull/3375) it is expected that networking config values are not inherited via the preset-base in the network config?

For example, when I use a custom network config, I am now required to define GOSSIP_MAX_SIZE despite `PRESET_BASE: 'minimal'`, see https://github.com/siladu/beku-timestamp/commit/de1f285e6ec80db614c874f8979c3954401a3f61

This also impacts web3signer due to the inherited dependency on the teku network config such that any custom networks in devnets or test infrastructure now requires the networking config.

**Comment by rolfyone** [comment]
I think this got broken by trying to cope with some remote values missing from constants that moved...

I'll work up a solution, the problem is specifically the ordering in remote config loader from #7510, it looks like we fixed it in the incorrect way...

**Comment by rolfyone** [comment]
Actually, I may have slightly assessed this incorrectly... but I think the fix will be the same.

Basically in consensus-specs, a bunch of 'constants' got moved to 'config'. `GOSSIP_MAX_SIZE` is one, and it pretty much does mean that all custom configs need to now define those values, because they're no longer constants (3375 you mentioned above).

There's a 'similar' problem with remote config where we now load some defaults in a bad order, but that's different to the root cause of this issue, which is just not having those moved values set in config thats loaded from a local resource.

I think your initial assessment of it was correct in that its a flow on effect of the consensus-specs change, but this has also caused issues loading remote configs where 3375 hadn't been done on external BNs we're loading configuration from.

**Comment by rolfyone** [comment]
One potential issue of note is the `MIN_EPOCHS_FOR_BLOCK_REQUESTS` which defaults differently on minimal compared to mainnet, so if that value is of interest you should definitely set it to the value you require.

**Comment by tbenr** [comment]
My position on this is that it isn't a Teku issue, it is a spec issue.

`GOSSIP_MAX_SIZE` is only defined in configs now, and is not present in any preset. This determine that this parameter (together with the other `Networking` params) is now mandatory to be set in every config. A config without it is effectively an invalid config.

Maybe the solution to this is to move this parameters on preset (but I don't have the reasoning why it was chosen to move them in config). Happy to continue the discussion on a spec issue!
