### ISSUE TITLE
Teku rest api timeouts when requesting validator state

### ISSUE THREAD

**Issue by mortimr** [Consensys-Incorporated/teku#7673]
### Description
Currently calling the `/eth/v1/beacon/states/${SLOT}/validators` endpoint on the rest api, getting either a closed connection or a 404 for some slots that are just a few epochs in the past.

Performed when head slot was `6904629`

```
curl http://localhost:5051/eth/v1/beacon/states/6904550/validators

curl: (56) Recv failure: Connection reset by peer
```

```
curl http://localhost:5051/eth/v1/beacon/states/6904500/validators

curl: (56) Recv failure: Connection reset by peer
```

even `head` will sometimes fail.

Is there a configuration (apart from archive) that I might be missing ?

**Comment by rolfyone** [comment]
Hey thanks for raising this. A couple of initial comments and questions...

I'm assuming you're not in archive mode, given the 404 reference. Basically if you're not in archive mode, anything before the finalized state will be a 404, because we don't have those state to build validator data from.

So if finalized is slot 3200, and you select 3199 for example, then you're going to receive a 404.

Regarding timeout, you'll probably find a subsequent query with the same parameters will work, becuase by then it'll have rebuilt state so it can get down to business.  If you're doing this kind of query often, you could consider increasing the state cache (which will require more memory), using `--Xstore-state-cache-size` which has defaulted to 8 since about June.  If you increase this to around 96, you'll basically have all states in memory and never need to rebuild states for these queries.

The other thing that can definitely help is requesting only the validators which you need information on, as the list is very large now.

In terms of questions
 - what teku version are you using?
 - how much heap are you running with (-Xmx)
 - are you seeing 'Completed regeneration of state' messages while you're running these validator queries?
 - Am I correct in my assertion that you're not using archive mode? If you are using archive mode, are you querying states from earlier than when your database is storing? (before you initialised, its possible to rebuild states from earlier but its not default behavior)
 - what network are you running on? is it a validating node? (more because I won't ask you to test things on a validating node unless we really need to)

Hopefully this is a start...

**Comment by rolfyone** [comment]
@mortimr did this help at all?

**Comment by rolfyone** [comment]
Without further information, assuming that the information above has helped, feel free to re-open if there's more.
