### ISSUE TITLE
Burn address cannot be set via Key Manager API

### ISSUE THREAD

**Issue by dappnodedev** [Consensys-Incorporated/teku#7742]
### Description
Performing an HTTP(S) POST to the Key Manager API of the Teku validator service for setting the fee recipient to the burn address for a specific validator pubkey results in a 400 Bad Request error: `{"code":400,"message":"Cannot set fee recipient to 0x00 address."}`. What is the rationale for this? Is it possible to allow setting the burn address as fee recipient?

### Steps to Reproduce

curl -k --cert-type P12 --cert <cert_file>:"<cert_pass>"  -X POST "https:/<validator_container>:<validator_port>/eth/v1/validator/<pubkey>/feerecipient" -H  "accept: */*" -H  "Content-Type: application/json" -d "{\"ethaddress\":\"0x0000000000000000000000000000000000000000\"}" -H "Authorization: Bearer <token>"

**Expected behavior:** [What you expect to happen]
The fee recipient should be set even if it is the burn address

**Actual behavior:** [What actually happens]
The 0x00 address cannot be set as fee recipient for a validator

### Versions (Add all that apply)
`teku/v23.10.0/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17`

Running in Docker

**Comment by rolfyone** [comment]
We can allow the burn address, originally it was decided that its basically throwing eth away so we preferred an actual address...

What use-case do you see as setting the burn address?

@benjaminion thoughts?

**Comment by benjaminion** [comment]
I am fairly firmly against allowing the zero address to be specified.

Couple of reasons:

1. It's easy to work around. There are plenty of burn addresses in Ethereum if someone really wants to burn their rewards. More than 1,460,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000 of them. Preventing one of them is not a significant limitation. People often use [`0x0000....dead`](https://etherscan.io/address/0x000000000000000000000000000000000000dead) for example.

2. People sometimes use `0x0000...0000` as a placeholder. Or in automated pipelines, zero can sometimes end up inadvertantly as the value. For example, after the DAO fork, people lost Ether because the UI for the [ReplaySafeSplit](https://etherscan.io/address/0xaa1a6e3e6ef20068f7f8d8c835d2d22fd5116444#code) contract inserted the zero address if the user forgot to specifiy a To address. This is catastrophic UX.

If there is a genuine use case for allowing the `0x00` address, I'd be happy to reconsider, but I find it very hard to imagine one.

**Comment by dappnodedev** [comment]
I agree with the 2 reasons @benjaminion pointed out. Thanks so much for the detailed explanation. I'll close the issue :)
