### ISSUE TITLE
Update VC to use JsonTypeDef instead of annotated schemas

### ISSUE THREAD

**Issue by lucassaldanha** [Consensys-Incorporated/teku#7762]
Related to "Finish off removing the old beacon-api schemas" and "Consistent VC API Calls" TIP.

**Comment by courtneyeh** [comment]
Requires converting all the API requests in `OkHttpValidatorRestApiClient` to use `JsonTypeDef` as seen in `OkHttpValidatorTypeDefClient`.

**Comment by courtneyeh** [comment]
GET requests involve:
- Moving static type definitions into `DeserializableTypeDefinition`'s, and moving them to the `ethereum.json.types` package along with the wrapper objects.
- Creating the request extending `AbstractTypeDefRequest`, and using this instead for calls made in the `RemoteValidatorApiHandler` class.

GET requests left: GetSpec, GetBlockHeader, GetValidators, ~~GetAttestationDuties~~, ~~GetSyncCommitteeDuties~~

GetSpec is expected to be harder because the data held in `GetSpecResponse` is less simple to turn into a `DeserializableTypeDefinition` from the looks of it.

**Comment by courtneyeh** [comment]
**Update:** The `getAttestationDuties` method in `OkHttpValidatorRestApiClient` Is related to the `PostAttesterDuties` endpoint. Therefore, it is a POST not a GET.

Same with the `getSyncCommitteeDuties` method. It relates to `PostSyncDuties`.

**Comment by rolfyone** [comment]
partially addressed in #8452
