### ISSUE TITLE
Implement header parameter into APIs

### ISSUE THREAD

**Issue by courtneyeh** [Consensys-Incorporated/teku#7868]
make sure Eth-consensus-version is specified on open api definitions where appropriate in all endpoints.

**Comment by rolfyone** [comment]
bigger thing i'd like here is to be able to say 'the response object has a header' for eth-consensus-version for GET.

**Comment by mehdi-aouadi** [comment]
@gfukushima  After checking I see we're compliant with the beacon API specs (the `Eth-Consensus-Version` is used correctly whenever specified) which is a good start.
I think the idea behind this issue is to add the header in the open api definition when it's present in the response.
Example: The `GetAggregateAttestationV2` [has a header in the response](https://github.com/ethereum/beacon-APIs/blob/master/apis/beacon/pool/attestations.v2.yaml#L22) but there is no mention of that in our open api definition in `_eth_v2_beacon_pool_attestations.json`. So ideally I think we might want it to be present there too so we can detect when a header is missing for some reason and to be more compliant with the spec.
In the swagger UI we should have those headers listed: https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getBlockAttestationsV2
<img width="1701" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2R4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e079c78db39e90ed9006bbe6d6f9e9a8c63ff1fa/Screenshot%202024-08-20%20at%2021.10.17.png" alt="Screenshot 2024-08-20 at 21.10.17.png" />


With our current implementation we don't have that:
<img width="927" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1Z4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f4fa7f826a825a8c70c6ec270582b565aca49c5/Screenshot%202024-08-20%20at%2021.09.05.png" alt="Screenshot 2024-08-20 at 21.09.05.png" />

That's my understanding
