### ISSUE TITLE
Unable to create gossip_messages directory to save gossip messages. Disabling saving debug data to file. 

### ISSUE THREAD

**Issue by Neurone** [Consensys-Incorporated/teku#8256]
### Description
During startup, Teku tries to create the following folders in the current directory instead of using the configured `data-base-path`.

```
./gossip_messages
./gossip_messages/decoding_error
./gossip_messages/rejected
./invalid_blocks
```

This is probably due to the recent introduction of the [DebugDataDumper ](https://github.com/Consensys/teku/blob/730358fc0ca258b3d16fd9790e5eaf60adb05471/ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/util/DebugDataDumper.java#L51).

### Steps to Reproduce (Bug)
1. [download](https://artifacts.consensys.net/public/teku/raw/names/teku.zip/versions/24.4.0/teku-24.4.0.zip) and unzip teku 24.4.0
2. navigate to any folder you have read only access (i.e., `/home`)
3. launch teku via absolute or relative path
4. wait a few seconds
5. stop teku (CTRL+C)
6. check the log for the error message `ERROR | DebugDataDumper | Unable to create gossip_messages directory to save gossip messages. Disabling saving debug data to file.`
7. navigate to a temp folder you have write permissions
8. launch teku via absolute or relative path
9. wait a few seconds
10. stop teku (CTRL+C)
11. verify debug folders are created inside the current folder

**Expected behavior:**

Teku complies with the `data-base-path` in the configuration file.

**Actual behavior:**

Teku is trying to use the current folder for debugging purposes.

**Frequency:**

Always

### Versions
* Software version: `teku/v24.4.0/linux-x86_64/-privatebuild-openjdk64bitservervm-java-17`
* Java version: `OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-122.04.1)`
* OS Name & Version: `Ubuntu 22.04.4 LTS`

**Comment by StefanBratanov** [comment]
Hi @Neurone thanks for raising this.  By default dumping `p2p` debug data is disabled and teku was creating the debug directories in the current directory in this case. This behaviour is fixed in https://github.com/Consensys/teku/pull/8258, so will be part of the next release. For the moment, it is safe to ignore this error message. In case you want to enable `p2p` debug data, can use `--Xp2p-dumps-to-file-enabled=true`. In that case, the correct `data-base-path` will be used.
