### ISSUE TITLE
Add automatic reset for  Ephemery Network

### ISSUE THREAD

**Issue by gconnect** [Consensys-Incorporated/teku#8589]
### Description
Ephemery network have a reset period. As a node runner/validator, I would want my db to be automatically deleted and the update to happen automatically without manually restarting and deleting the old db.

**Expected behavior:** [What you expect to happen]
- DB should be automatically deleted when update is due
- When an update is due config should be updated automatically without manually stopping and restarting
- Update check should happen on running node and not just on start

**Actual behavior:** [What actually happens]
- Manual delete of db
- Check for update only happens on start. 

**Frequency:** [How regularly does it occur?]
Always

### Versions (Add all that apply)
* Software version: [`teku --version` or look for log lines starting with `Teku version:`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by gconnect** [comment]
@rolfyone please assign this issue to me and let me know what you think on possible best steps to achieve this.

**Comment by rolfyone** [comment]
I think the easiest will be more like what I had messaged, but to reiterate,
 - firstly on startup, check the fork against the fork of the database, and if it's not matching, rather than fail to start if ephemery, delete the netowrk.yaml and db folder and initialise the database fresh
 - during epoch processing or slot processing, we check the slot is less than the max, otherwise we throw `IllegalStateException` and let the system crash
 - Then what will happen if its wrapped in a service is it'll automatically restart, and that'll run our startup logic to clean the database...
 i'd see points 1 and 2 as their own PRs for sanity...

**Comment by gconnect** [comment]
> I think the easiest will be more like what I had messaged, but to reiterate,
> 
> * firstly on startup, check the fork against the fork of the database, and if it's not matching, rather than fail to start if ephemery, delete the netowrk.yaml and db folder and initialise the database fresh
> * during epoch processing or slot processing, we check the slot is less than the max, otherwise we throw `IllegalStateException` and let the system crash
> * Then what will happen if its wrapped in a service is it'll automatically restart, and that'll run our startup logic to clean the database...
>   i'd see points 1 and 2 as their own PRs for sanity...

Thanks for this. I will look into it.
